### ISSUE TITLE
Assertion fail when network doing forward 

### ISSUE THREAD

**Issue by Eralien** [traveller59/spconv#100]
I encounter this issue when trying to run a small network with SparseSequential, and this error pops up when doing the forward:

```bash
Traceback (most recent call last):
  File "train.py", line 64, in <module>
    train()
  File "train.py", line 56, in train
    output = net_cuda(spTensor)
  File "/home/eralienf/.conda/envs/lyft/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/eralienf/Project/Lyft/carlaok/src/__init__.py", line 41, in forward
    output = self.whatever(features)
  File "/home/eralienf/.conda/envs/lyft/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/eralienf/.conda/envs/lyft/lib/python3.7/site-packages/spconv/modules.py", line 130, in forward
    input = module(input)
  File "/home/eralienf/.conda/envs/lyft/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/eralienf/.conda/envs/lyft/lib/python3.7/site-packages/spconv/conv.py", line 177, in forward
    use_hash=self.use_hash)
  File "/home/eralienf/.conda/envs/lyft/lib/python3.7/site-packages/spconv/ops.py", line 93, in get_indice_pairs
    stride, padding, dilation, out_padding, int(subm), int(transpose), int(use_hash))
RuntimeError: /home/eralienf/lib/spconv/include/torch_utils.h 56
val assert faild. error
```

Within the torch.utils.h, it writes:
```c++
32 template <typename T> void check_torch_dtype(const torch::Tensor &tensor) {
33   switch (tensor.type().scalarType()) {
34   case at::ScalarType::Double: {
35     auto val = std::is_same<std::remove_const_t<T>, double>::value;
36     TV_ASSERT_RT_ERR(val, "error");
37     break;
38   }
39   case at::ScalarType::Float: {
40     auto val = std::is_same<std::remove_const_t<T>, float>::value;
41     TV_ASSERT_RT_ERR(val, "error");
42     break;
43   }
44   case at::ScalarType::Int: {
45     auto val = std::is_same<std::remove_const_t<T>, int>::value;
46     TV_ASSERT_RT_ERR(val, "error");                                                                                                                                                                              
47     break;
48   }
49   case at::ScalarType::Half: {
50     auto val = std::is_same<std::remove_const_t<T>, at::Half>::value;
51     TV_ASSERT_RT_ERR(val, "error");
52     break;
53   }
54   case at::ScalarType::Long: {
55     auto val = std::is_same<std::remove_const_t<T>, long>::value;
56     TV_ASSERT_RT_ERR(val, "error");
57     break;
58   }
59   default:
60     TV_ASSERT_RT_ERR(false, "error");
61   }
62 }
```

It seems like some data type with my sparse tensor is wrong. I am not sure which one does long type scalar type refers to. This happens when creating the SparseTensor with grid=None.

**Comment by Eralien** [comment]
Solved. Turns out that indices passed in when creating a spconv.SparseTensor should be type int rather than long type.
