### ISSUE TITLE
Error: python setup.py bdist_wheel

### ISSUE THREAD

**Issue by 3bobo** [traveller59/spconv#109]
```
(newstarts) zqk@zqk:~/code/point/spconv$ python setup.py bdist_wheel
running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/zqk/anaconda2/envs/newstarts/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/zqk/code/point/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.13 or higher is required.  You are running version 3.5.1


-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "setup.py", line 99, in <module>
    zip_safe=False,
  File "/home/zqk/anaconda2/envs/newstarts/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/zqk/anaconda2/envs/newstarts/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/zqk/anaconda2/envs/newstarts/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/zqk/anaconda2/envs/newstarts/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/zqk/anaconda2/envs/newstarts/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
    self.run_command('build')
  File "/home/zqk/anaconda2/envs/newstarts/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/zqk/anaconda2/envs/newstarts/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/zqk/anaconda2/envs/newstarts/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/zqk/anaconda2/envs/newstarts/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/zqk/anaconda2/envs/newstarts/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 40, in run
    self.build_extension(ext)
  File "setup.py", line 82, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/zqk/anaconda2/envs/newstarts/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/zqk/code/point/spconv', '-DCMAKE_PREFIX_PATH=/home/zqk/anaconda2/envs/newstarts/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/zqk/code/point/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
```
failed to build it, can anyone help me?
My setting:
Ubuntu 16.04
Pytorch 1.0.1
Cmake 3.5.1
Python 3.7.3

**Comment by SimLeek** [comment]
Update cmake. Ubuntu 16 uses an old version.

**Comment by 3bobo** [comment]
> Update cmake. Ubuntu 16 uses an old version.

Thanks! I missed this. The problem has been solved.
