### ISSUE TITLE
spconv/indice.cu 60 cuda execution failed with error 98

### ISSUE THREAD

**Issue by chowkamlee81** [traveller59/spconv#113]
I installed spconv module succesfully. I had ubuntu18.0.4, cuda10.2 , torch=1.20 torch vision=0.4.0,

After installing, i tried execute  python test/test_conv.py , but i got error below.. Kindly help

/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
spconv time nan
Traceback (most recent call last):
  File "test_conv.py", line 619, in <module>
    main()
  File "test_conv.py", line 612, in main
    out = net(features_t, indices_t, bs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "test_conv.py", line 57, in forward
    return self.net(x)# .dense()
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/spconv/modules.py", line 130, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/spconv/conv.py", line 177, in forward
    use_hash=self.use_hash)
  File "/usr/local/lib/python3.6/dist-packages/spconv/ops.py", line 93, in get_indice_pairs
    stride, padding, dilation, out_padding, int(subm), int(transpose), int(use_hash))
RuntimeError: /module/src/lidar_detection/spconv-master/src/spconv/indice.cu 60
cuda execution failed with error 98

**Comment by wdxpython** [comment]
I also encountered this problem, how do you solve it?

**Comment by jayadeepk** [comment]
I got it working using this method: https://github.com/pangsu0613/CLOCs/issues/20#issuecomment-1003668924
