### ISSUE TITLE
error when run setup.py

### ISSUE THREAD

**Issue by Vela-zz** [traveller59/spconv#127]
Stop at [75%] and return
` [/home/unamattina/point-cloud/spconv/src/spconv/all.cc: At global scope:
/home/unamattina/point-cloud/spconv/src/spconv/all.cc:23:12: error: ‘RegisterOperators’ is not a member of ‘torch’
     torch::RegisterOperators()
            ^~~~~~~~~~~~~~~~~
/home/unamattina/point-cloud/spconv/src/spconv/all.cc:23:12: note: suggested alternative:
In file included from /home/unamattina/miniconda2/envs/ppn/lib/python3.6/site-packages/torch/lib/include/torch/script.h:5:0,
                 from /home/unamattina/point-cloud/spconv/src/spconv/all.cc:15:
/home/unamattina/miniconda2/envs/ppn/lib/python3.6/site-packages/torch/lib/include/torch/csrc/jit/custom_operator.h:238:18: note:   ‘torch::jit::RegisterOperators’
 struct TORCH_API RegisterOperators {
                  ^~~~~~~~~~~~~~~~~
src/spconv/CMakeFiles/spconv.dir/build.make:82: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all.cc.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/all.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
src/spconv/CMakeFiles/spconv.dir/build.make:95: recipe for target 'src/spconv/CMakeFiles/spconv.dir/indice.cc.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/indice.cc.o] Error 1
CMakeFiles/Makefile2:155: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all' failed
make[1]: *** [src/spconv/CMakeFiles/spconv.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 99, in <module>
    zip_safe=False,
  File "/home/unamattina/miniconda2/envs/ppn/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/home/unamattina/miniconda2/envs/ppn/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/unamattina/miniconda2/envs/ppn/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/unamattina/miniconda2/envs/ppn/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/unamattina/miniconda2/envs/ppn/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 223, in run
    self.run_command('build')
  File "/home/unamattina/miniconda2/envs/ppn/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/unamattina/miniconda2/envs/ppn/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/unamattina/miniconda2/envs/ppn/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/unamattina/miniconda2/envs/ppn/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/unamattina/miniconda2/envs/ppn/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 40, in run
    self.build_extension(ext)
  File "setup.py", line 83, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/unamattina/miniconda2/envs/ppn/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
`
and before this error happened,
it also raise lots of primary-expression error like this, in torch_utils.h, pool_ops.h, spconv_ops.h

`/home/unamattina/point-cloud/spconv/include/torch_utils.h:96:27: error: expected primary-expression before ‘(’ token
   return tv::TensorView<T>(tensor.data_ptr<std::remove_const_t<T>>(), shape);
                           ^
`

**Comment by Vela-zz** [comment]
Running on:
Ubuntu 18.04
cuda 10.0
cudnn 7.4.2
torch 1.0.1
python 3.6.10

**Comment by qoVA** [comment]
Having same problem.. Appears this library is not currently maintained
