### ISSUE TITLE
Running python setup.py bdist_wheel gives Undefined symbols for architecture x86_64 (Please help)

### ISSUE THREAD

**Issue by MuneebZafar00713** [traveller59/spconv#137]
Undefined symbols for architecture x86_64:
  "spconv::functor::NonMaxSupressionFunctor<tv::CPU, float, long long>::operator()(tv::CPU const&, tv::TensorView<long long, -1>, tv::TensorView<float const, -1>, float, float)", referenced from:
      at::Tensor spconv::nonMaxSuppression<float>(at::Tensor, at::Tensor, long long, long long, double, double) in all.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../lib.macosx-10.9-x86_64-3.6/spconv/libspconv.dylib] Error 1
make[1]: *** [src/spconv/CMakeFiles/spconv.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 101, in <module>
    zip_safe=False,
  File "/Users/asif/opt/anaconda3/envs/py36/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/Users/asif/opt/anaconda3/envs/py36/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/asif/opt/anaconda3/envs/py36/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/asif/opt/anaconda3/envs/py36/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/asif/opt/anaconda3/envs/py36/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 223, in run
    self.run_command('build')
  File "/Users/asif/opt/anaconda3/envs/py36/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/asif/opt/anaconda3/envs/py36/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/asif/opt/anaconda3/envs/py36/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/Users/asif/opt/anaconda3/envs/py36/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/asif/opt/anaconda3/envs/py36/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 42, in run
    self.build_extension(ext)
  File "setup.py", line 85, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/Users/asif/opt/anaconda3/envs/py36/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

`Cuda version: 10.2.89`
`pytorch: 1.4.0`
`torch: 1.1.0`
`python: 3.6.10`
`cmake: 3.16.6`
`boost: 1.72.0_2`

**Comment by harveypham** [comment]
I got the same error, and I traced it down to wrong current directory during the build. The workaround is to modify setup.py:83 from:
```subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)```
to:
```subprocess.check_call(['cmake', '--build', '../..'] + build_args, cwd=self.build_temp)```

You can debug the issue by print out values before the execute cmake:
```
        print("Current working dir:", os.getcwd())
        print(build_args)
        print(self.build_temp)
        print("---")
        subprocess.check_call(['cmake', '--build', '../..'] + build_args, cwd=self.build_temp)
```
