### ISSUE TITLE
OSError: libtorch_cpu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by swwwu** [traveller59/spconv#156]
Hello!
I had installed spconv successfully.But I don't know why it comes out error when import spconv .
Hope for HELP.  Thank you!
>>> import spconv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3/lib/python3.7/site-packages/spconv/__init__.py", line 35, in <module>
    torch.ops.load_library(_LIB_PATH)
  File "/usr/local/python3/lib/python3.7/site-packages/torch/_ops.py", line 106, in load_library
    ctypes.CDLL(path)
  File "/usr/local/python3/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtorch_cpu.so: cannot open shared object file: No such file or directory

**Comment by swwwu** [comment]
I have solved this problem by changing the version to **spconv1.1**

**Comment by deanzhanggit** [comment]
> I have solved this problem by changing the version to **spconv1.1**

It works! Thank you!
