### ISSUE TITLE
python setup.py bdist_wheel error

### ISSUE THREAD

**Issue by fyaft2012** [traveller59/spconv#162]
Hello, any help please. When I use python **setup.py bdist_wheel** , it shows the error message:
----------------------------------------------------------------------
running bdist_wheel
running build
running build_py
running build_ext
/home/lion/FangYang/ADs/second.pytorch/second/spconv/build/lib.linux-x86_64-3.7
Release
-- Caffe2: CUDA detected: 10.0.130
-- Caffe2: CUDA nvcc is: /usr/local/cuda-10.0/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-10.0
-- Caffe2: Header version is: 10.0
-- Found cuDNN: v7.6.0  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Autodetected CUDA architecture(s): 7.5
-- Added CUDA NVCC flags for: -gencode;arch=compute_75,code=sm_75
CMake Error at CMakeLists.txt:28 (add_subdirectory):
  The source directory

    /home/lion/FangYang/ADs/second.pytorch/second/spconv/third_party/pybind11

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
See also "/home/lion/FangYang/ADs/second.pytorch/second/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
See also "/home/lion/FangYang/ADs/second.pytorch/second/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 86, in <module>
    zip_safe=False,
  File "/home/lion/anaconda3/envs/second/lib/python3.7/site-packages/setuptools/__init__.py", line 161, in setup
    return distutils.core.setup(**attrs)
  File "/home/lion/anaconda3/envs/second/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/lion/anaconda3/envs/second/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/lion/anaconda3/envs/second/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/lion/anaconda3/envs/second/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 223, in run
    self.run_command('build')
  File "/home/lion/anaconda3/envs/second/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/lion/anaconda3/envs/second/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/lion/anaconda3/envs/second/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/lion/anaconda3/envs/second/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/lion/anaconda3/envs/second/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 39, in run
    self.build_extension(ext)
  File "setup.py", line 69, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/lion/anaconda3/envs/second/lib/python3.7/subprocess.py", line 341, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/lion/FangYang/ADs/second.pytorch/second/spconv', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/lion/FangYang/ADs/second.pytorch/second/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_PREFIX_PATH=/home/lion/anaconda3/envs/second/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
----------------------------------------------------------
By the way, I use Ubuntu 16.04, cuda 10.0.130, pytorch 1.0.0 (I also tried 1.1.0 and 1.2.0) . Any help is appreciated, thanks.

**Comment by traveller59** [comment]
you forget to add ```--recursive``` when clone repo.
run ```git clone --recursive https://www.github.com/traveller59/spconv.git```

**Comment by fyaft2012** [comment]
Hi @traveller59 , thank you for timely answer! I will follow your way to download the repo. and now I am upgrade the pytorch to 1.3.0. I really hope it can be installed successfully. Since I have been stuck in spconv install problem for a few days. Thanks.
