### ISSUE TITLE
error in python setup.py bdist_wheel

### ISSUE THREAD

**Issue by lgldl** [traveller59/spconv#172]
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/all.cc.o] Error 1
make[2]: *** 正在等待未完成的任务....
CMakeFiles/Makefile2:113: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all' failed
make[1]: *** [src/spconv/CMakeFiles/spconv.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 86, in <module>
    zip_safe=False,
  File "/home/lgl/anaconda3/envs/PCDet/lib/python3.6/site-packages/setuptools/__init__.py", line 161, in setup
    return distutils.core.setup(**attrs)
  File "/home/lgl/anaconda3/envs/PCDet/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/lgl/anaconda3/envs/PCDet/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/lgl/anaconda3/envs/PCDet/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/lgl/anaconda3/envs/PCDet/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 223, in run
    self.run_command('build')
  File "/home/lgl/anaconda3/envs/PCDet/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/lgl/anaconda3/envs/PCDet/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/lgl/anaconda3/envs/PCDet/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/lgl/anaconda3/envs/PCDet/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/lgl/anaconda3/envs/PCDet/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 39, in run
    self.build_extension(ext)
  File "setup.py", line 70, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/lgl/anaconda3/envs/PCDet/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

**Comment by zzq-zzq** [comment]
same

**Comment by zzq-zzq** [comment]
How did you solve it

**Comment by lgldl** [comment]
> How did you solve it

I have solved this problem by changing torch::jit::RegisterOperators() into torch::RegisterOperators() in all.cc.
you can try

**Comment by bixueting** [comment]
> > How did you solve it
> 
> I have solved this problem by changing torch::jit::RegisterOperators() into torch::RegisterOperators() in all.cc.
> you can try

where .cc you say?
