### ISSUE TITLE
error in  python setup.py bdist_wheel

### ISSUE THREAD

**Issue by luzonghao1** [traveller59/spconv#173]
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
CMake Warning (dev) at /home/lzh/mysoft/cmake-3.17.3-Linux-x86_64/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (torch) does
  not match the name of the calling package (Torch).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /home/lzh/anaconda3/envs/pcdet/lib/python3.6/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:130 (find_package_handle_standard_args)
  CMakeLists.txt:22 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Autodetected CUDA architecture(s):  6.1 6.1 6.1 6.1
-- pybind11 v2.5.dev1
-- Configuring done
`**CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_CUBLAS
    linked by target "cuhash" in directory /home/lzh/3dcode/kitti/aux/spconv-master/src/cuhash
    linked by target "spconv" in directory /home/lzh/3dcode/kitti/aux/spconv-master/src/spconv
**`
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
Traceback (most recent call last):
  File "setup.py", line 109, in <module>
    zip_safe=False,
  File "/home/lzh/anaconda3/envs/pcdet/lib/python3.6/site-packages/setuptools/__init__.py", line 161, in setup
    return distutils.core.setup(**attrs)
  File "/home/lzh/anaconda3/envs/pcdet/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/lzh/anaconda3/envs/pcdet/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/lzh/anaconda3/envs/pcdet/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/lzh/anaconda3/envs/pcdet/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 223, in run
    self.run_command('build')
  File "/home/lzh/anaconda3/envs/pcdet/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/lzh/anaconda3/envs/pcdet/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/lzh/anaconda3/envs/pcdet/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/lzh/anaconda3/envs/pcdet/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/lzh/anaconda3/envs/pcdet/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 49, in run
    self.build_extension(ext)
  File "setup.py", line 92, in build_extension

**Comment by MeyLavie** [comment]
Same here.

**Comment by luzonghao1** [comment]
> 
> 
> Same here.

its cudnn not install correctly。CUDA_CUBLAS is  a Acceleration package 。

**Comment by minna-ust** [comment]
come across the same problem.
sudo apt install libcublas-dev

**Comment by dimitree54** [comment]
In my case when I was installing cuda-10-1, cublas had been installed at different directory (`/usr/local/cuda-10-2` instead of main cuda dir `/usr/local/cuda-10-1`). And because of it the spconv installer did not see CUDA_CUBLAS. 

I have tried different solutions (including the @minna-ust 's solution), but the only one that worked is to manually copy cublas from 10-2 to 10-1 (by `sudo cp -rp cuda-10.2/targets/* cuda-10.1/targets/`).

**Comment by swetapriyadarshi** [comment]
I am still getting the same error even after trying the above mentioned suggestions.
