### ISSUE TITLE
subprocess.CalledProcessError

### ISSUE THREAD

**Issue by hughlee815** [traveller59/spconv#181]
`running bdist_wheel
running build
running build_py
running build_ext
/home/adas/congcong.li/spconv1.0/build/lib.linux-x86_64-3.7
Release
-- Caffe2: CUDA detected: 10.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.0
-- Found CUDNN: /usr/local/cuda/lib64/libcudnn.so  
-- Found cuDNN: v7.6.3  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s):  7.5 7.5
-- Added CUDA NVCC flags for: -gencode;arch=compute_75,code=sm_75
CMake Warning (dev) at /home/adas/anaconda3/envs/pcdet/lib/python3.7/site-packages/cmake/data/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (torch) does
  not match the name of the calling package (Torch).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /home/adas/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:122 (find_package_handle_standard_args)
  CMakeLists.txt:23 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:28 (add_subdirectory):
  The source directory

    /home/adas/congcong.li/spconv1.0/third_party/pybind11

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
See also "/home/adas/congcong.li/spconv1.0/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
See also "/home/adas/congcong.li/spconv1.0/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 86, in <module>
    zip_safe=False,
  File "/home/adas/anaconda3/envs/pcdet/lib/python3.7/site-packages/setuptools/__init__.py", line 161, in setup
    return distutils.core.setup(**attrs)
  File "/home/adas/anaconda3/envs/pcdet/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/adas/anaconda3/envs/pcdet/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/adas/anaconda3/envs/pcdet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/adas/anaconda3/envs/pcdet/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 223, in run
    self.run_command('build')
  File "/home/adas/anaconda3/envs/pcdet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/adas/anaconda3/envs/pcdet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/adas/anaconda3/envs/pcdet/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/adas/anaconda3/envs/pcdet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/adas/anaconda3/envs/pcdet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 39, in run
    self.build_extension(ext)
  File "setup.py", line 69, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/adas/anaconda3/envs/pcdet/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/adas/congcong.li/spconv1.0', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/adas/congcong.li/spconv1.0/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_PREFIX_PATH=/home/adas/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
`
because of the env-requist, i must install spconv v1.0. but it seems i cannot use git clone, so i directly download the zip.
but i encounter a problem like this.
is this because that i dont use --recursive or other reason?
thank you so much for your attention

**Comment by traveller59** [comment]
they are submodules and will be cloned when add ```--recursive``` to ```git clone```.
you can clone them manually.

**Comment by hughlee815** [comment]
i see...when i run "git clone https://github.com/traveller59/spconv.git --recursive", i will clone all the repo to my computer. but how can i know which submodules are the modules i want, namely v1.0? 
and should i delete other directories if i only want the submodules?
thank you so much for your patience
