### ISSUE TITLE
running example mnist_sparse.py

### ISSUE THREAD

**Issue by jelomic** [traveller59/spconv#187]
while running# python mnist_sparse.py in example directory this error show up

What could be done to correct this error ?

"Extracting ../data/MNIST/raw/train-images-idx3-ubyte.gz
Traceback (most recent call last):
  File "mnist_sparse.py", line 139, in <module>
    main()
  File "mnist_sparse.py", line 112, in main
    transforms.ToTensor(),
  File "/usr/local/lib/python3.6/dist-packages/torchvision/datasets/mnist.py", line 68, in __init__
    self.download()
  File "/usr/local/lib/python3.6/dist-packages/torchvision/datasets/mnist.py", line 146, in download
    self.extract_gzip(gzip_path=file_path, remove_finished=True)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/datasets/mnist.py", line 127, in extract_gzip
    gzip.GzipFile(gzip_path) as zip_f:
  File "/usr/lib/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '../data/MNIST/raw/train-images-idx3-ubyte.gz'"

**Comment by traveller59** [comment]
you may need to run the script inside a folder which allow writing to ```../data```. this script is modified from pytorch official example, it will create a folder ```../data``` and download mnist to it.
