### ISSUE TITLE
can I get a docker spconv for python 3.7 or lower?

### ISSUE THREAD

**Issue by Shawn-Zhuang** [traveller59/spconv#189]
I use the scrin/dev-spconv, but the python is v3.8, which is not supported by module "mayavi"
Can I ask for a spconv for python 3.7 or lower?

Of course the best thing is to compile spconv in my own system, but it fail and fail.

```
shawn@shawn-HP:~/spconv$ python3 setup.py bdist_wheel
/usr/local/lib/python3.6/dist-packages/setuptools/dist.py:705: UserWarning: Module torch was already imported from /home/shawn/.local/lib/python3.6/site-packages/torch/__init__.py, but /home/shawn/spconv/.eggs/torch-1.5.1-py3.6-linux-x86_64.egg is being added to sys.path
  pkg_resources.working_set.add(dist, replace=True)
running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/shawn/.local/lib/python3.6/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10100', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/shawn/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- Caffe2: CUDA detected: 10.2
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.2
-- Found cuDNN: v7.6.5  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Autodetected CUDA architecture(s):  6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- Autodetected CUDA architecture(s):  6.1
-- pybind11 v2.5.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/shawn/spconv/build/temp.linux-x86_64-3.6
[  8%] Built target spconv_nms
[ 32%] Built target cuhash
[ 44%] Built target spconv_utils
[ 52%] Building CXX object src/spconv/CMakeFiles/spconv.dir/indice.cc.o
[ 52%] Building CXX object src/spconv/CMakeFiles/spconv.dir/all.cc.o
[ 56%] Building CXX object src/spconv/CMakeFiles/spconv.dir/reordering.cc.o
[ 60%] Building CXX object src/spconv/CMakeFiles/spconv.dir/maxpool.cc.o
In file included from /home/shawn/spconv/include/spconv/fused_spconv_ops.h:20:0,
                 from /home/shawn/spconv/src/spconv/all.cc:15:
/home/shawn/spconv/include/tensorview/torch_utils.h: In function ‘tv::TensorView<T, Rank, PtrTraits, Tindex> tv::torch2tv(const at::Tensor&)’:
/home/shawn/spconv/include/tensorview/torch_utils.h:125:52: error: expected primary-expression before ‘(’ token
   return tv::TensorView<T, Rank, PtrTraits, Tindex>(
                                                    ^
/home/shawn/spconv/include/tensorview/torch_utils.h:126:44: error: expected primary-expression before ‘>’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                            ^~
/home/shawn/spconv/include/tensorview/torch_utils.h:126:47: error: expected primary-expression before ‘)’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                               ^
In file included from /home/shawn/spconv/src/spconv/all.cc:15:0:
/home/shawn/spconv/include/spconv/fused_spconv_ops.h: In function ‘at::Tensor spconv::fusedIndiceConvBatchNorm(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int64_t, int64_t, int64_t)’:
/home/shawn/spconv/include/spconv/fused_spconv_ops.h:41:50: error: expected primary-expression before ‘int’
       std::max_element(indicePairNumCpu.data_ptr<int>(),
                                                  ^~~
/home/shawn/spconv/include/spconv/fused_spconv_ops.h:42:50: error: expected primary-expression before ‘int’
                        indicePairNumCpu.data_ptr<int>() + kernelVolume);
                                                  ^~~
/home/shawn/spconv/include/spconv/fused_spconv_ops.h:44:57: error: expected primary-expression before ‘int’
       indicePairMaxSizeIter - indicePairNumCpu.data_ptr<int>();
                                                         ^~~
/home/shawn/spconv/include/spconv/fused_spconv_ops.h:77:43: error: expected primary-expression before ‘int’
     auto nHot = indicePairNumCpu.data_ptr<int>()[i];
                                           ^~~
/home/shawn/spconv/include/spconv/fused_spconv_ops.h:83:75: error: no matching function for call to ‘from_blob(void*, <brace-enclosed initializer list>, c10::TensorOptions&)’
                                              {nHot, numOutPlanes}, options);
                                                                           ^
In file included from /home/shawn/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:7:0,
                 from /home/shawn/.local/lib/python3.6/site-packages/torch/include/torch/script.h:3,
                 from /home/shawn/spconv/include/spconv/indice.h:18,
                 from /home/shawn/spconv/include/spconv/fused_spconv_ops.h:18,
                 from /home/shawn/spconv/src/spconv/all.cc:15:
/home/shawn/.local/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:53:19: note: candidate: at::Tensor torch::from_blob(void*, c10::IntArrayRef, c10::IntArrayRef, const Deleter&, const c10::TensorOptions&)
 inline at::Tensor from_blob(
                   ^~~~~~~~~
/home/shawn/.local/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:53:19: note:   candidate expects 5 arguments, 3 provided
/home/shawn/.local/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:69:19: note: candidate: at::Tensor torch::from_blob(void*, c10::IntArrayRef, c10::IntArrayRef, const c10::TensorOptions&)
 inline at::Tensor from_blob(
                   ^~~~~~~~~
/home/shawn/.local/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:69:19: note:   no known conversion for argument 2 from ‘<brace-enclosed initializer list>’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
/home/shawn/.local/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:88:19: note: candidate: at::Tensor torch::from_blob(void*, c10::IntArrayRef, const Deleter&, const c10::TensorOptions&)
 inline at::Tensor from_blob(
                   ^~~~~~~~~
/home/shawn/.local/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:88:19: note:   no known conversion for argument 2 from ‘<brace-enclosed initializer list>’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
/home/shawn/.local/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:102:19: note: candidate: at::Tensor torch::from_blob(void*, c10::IntArrayRef, const c10::TensorOptions&)
 inline at::Tensor from_blob(
                   ^~~~~~~~~
/home/shawn/.local/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:102:19: note:   no known conversion for argument 2 from ‘<brace-enclosed initializer list>’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
In file included from /home/shawn/spconv/src/spconv/all.cc:15:0:
/home/shawn/spconv/include/spconv/fused_spconv_ops.h:85:78: error: no matching function for call to ‘from_blob(void*, <brace-enclosed initializer list>, c10::TensorOptions&)’
         torch::from_blob(inputBuffer.data_ptr(), {nHot, numInPlanes}, options);
                                                                              ^
In file included from /home/shawn/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:7:0,
                 from /home/shawn/.local/lib/python3.6/site-packages/torch/include/torch/script.h:3,
                 from /home/shawn/spconv/include/spconv/indice.h:18,
                 from /home/shawn/spconv/include/spconv/fused_spconv_ops.h:18,
                 from /home/shawn/spconv/src/spconv/all.cc:15:
/home/shawn/.local/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:53:19: note: candidate: at::Tensor torch::from_blob(void*, c10::IntArrayRef, c10::IntArrayRef, const Deleter&, const c10::TensorOptions&)
 inline at::Tensor from_blob(
                   ^~~~~~~~~
/home/shawn/.local/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:53:19: note:   candidate expects 5 arguments, 3 provided
/home/shawn/.local/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:69:19: note: candidate: at::Tensor torch::from_blob(void*, c10::IntArrayRef, c10::IntArrayRef, const c10::TensorOptions&)
 inline at::Tensor from_blob(
                   ^~~~~~~~~
/home/shawn/.local/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:69:19: note:   no known conversion for argument 2 from ‘<brace-enclosed initializer list>’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
/home/shawn/.local/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:88:19: note: candidate: at::Tensor torch::from_blob(void*, c10::IntArrayRef, const Deleter&, const c10::TensorOptions&)
 inline at::Tensor from_blob(
                   ^~~~~~~~~
/home/shawn/.local/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:88:19: note:   no known conversion for argument 2 from ‘<brace-enclosed initializer list>’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
/home/shawn/.local/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:102:19: note: candidate: at::Tensor torch::from_blob(void*, c10::IntArrayRef, const c10::TensorOptions&)
 inline at::Tensor from_blob(
                   ^~~~~~~~~
/home/shawn/.local/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:102:19: note:   no known conversion for argument 2 from ‘<brace-enclosed initializer list>’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
In file included from /home/shawn/spconv/src/spconv/all.cc:17:0:
/home/shawn/spconv/include/spconv/pillar_scatter_ops.h: In function ‘at::Tensor spconv::pointPillarScatter(at::Tensor, at::Tensor, at::Tensor)’:
/home/shawn/spconv/include/spconv/pillar_scatter_ops.h:40:35: error: expected primary-expression before ‘int’
   auto shapeData = shape.data_ptr<int>();
                                   ^~~
/home/shawn/spconv/include/spconv/pillar_scatter_ops.h:43:38: error: could not convert ‘{<expression error>, <expression error>, <expression error>, <expression error>}’ from ‘<brace-enclosed initializer list>’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
                    features.options());
                                      ^
In file included from /home/shawn/spconv/src/spconv/reordering.cc:17:0:
/home/shawn/spconv/include/tensorview/torch_utils.h: In function ‘tv::TensorView<T, Rank, PtrTraits, Tindex> tv::torch2tv(const at::Tensor&)’:
/home/shawn/spconv/include/tensorview/torch_utils.h:125:52: error: expected primary-expression before ‘(’ token
   return tv::TensorView<T, Rank, PtrTraits, Tindex>(
                                                    ^
/home/shawn/spconv/include/tensorview/torch_utils.h:126:44: error: expected primary-expression before ‘>’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                            ^~
/home/shawn/spconv/include/tensorview/torch_utils.h:126:47: error: expected primary-expression before ‘)’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                               ^
/home/shawn/spconv/src/spconv/reordering.cc: In lambda function:
/home/shawn/spconv/src/spconv/reordering.cc:32:51: error: expected primary-expression before ‘>’ token
       Index *indices_data = indices.data_ptr<Index>();
                                                   ^
/home/shawn/spconv/src/spconv/reordering.cc:32:53: error: expected primary-expression before ‘)’ token
       Index *indices_data = indices.data_ptr<Index>();
                                                     ^
/home/shawn/spconv/src/spconv/reordering.cc:33:41: error: expected primary-expression before ‘>’ token
       T *buffer_data = buffer.data_ptr<T>();
                                         ^
/home/shawn/spconv/src/spconv/reordering.cc:33:43: error: expected primary-expression before ‘)’ token
       T *buffer_data = buffer.data_ptr<T>();
                                           ^
/home/shawn/spconv/src/spconv/reordering.cc:34:51: error: expected primary-expression before ‘>’ token
       const T *features_data = features.data_ptr<T>();
                                                   ^
/home/shawn/spconv/src/spconv/reordering.cc:34:53: error: expected primary-expression before ‘)’ token
       const T *features_data = features.data_ptr<T>();
                                                     ^
/home/shawn/spconv/src/spconv/reordering.cc: In lambda function:
/home/shawn/spconv/src/spconv/reordering.cc:56:51: error: expected primary-expression before ‘>’ token
       Index *indices_data = indices.data_ptr<Index>();
                                                   ^
/home/shawn/spconv/src/spconv/reordering.cc:56:53: error: expected primary-expression before ‘)’ token
       Index *indices_data = indices.data_ptr<Index>();
                                                     ^
/home/shawn/spconv/src/spconv/reordering.cc:57:47: error: expected primary-expression before ‘>’ token
       const T *buffer_data = buffer.data_ptr<T>();
                                               ^
/home/shawn/spconv/src/spconv/reordering.cc:57:49: error: expected primary-expression before ‘)’ token
       const T *buffer_data = buffer.data_ptr<T>();
                                                 ^
/home/shawn/spconv/src/spconv/reordering.cc:58:48: error: expected primary-expression before ‘>’ token
       T *features_data = outFeatures.data_ptr<T>();
                                                ^
/home/shawn/spconv/src/spconv/reordering.cc:58:50: error: expected primary-expression before ‘)’ token
       T *features_data = outFeatures.data_ptr<T>();
                                                  ^
/home/shawn/spconv/src/spconv/reordering.cc: In lambda function:
/home/shawn/spconv/src/spconv/reordering.cc:60:41: error: expected primary-expression before ‘>’ token
         const T *buf = buffer.data_ptr<T>();
                                         ^
/home/shawn/spconv/src/spconv/reordering.cc:60:43: error: expected primary-expression before ‘)’ token
         const T *buf = buffer.data_ptr<T>();
                                           ^
/home/shawn/spconv/src/spconv/reordering.cc:61:40: error: expected primary-expression before ‘>’ token
         T *out = outFeatures.data_ptr<T>();
                                        ^
/home/shawn/spconv/src/spconv/reordering.cc:61:42: error: expected primary-expression before ‘)’ token
         T *out = outFeatures.data_ptr<T>();
                                          ^
In file included from /home/shawn/spconv/include/spconv/maxpool.h:19:0,
                 from /home/shawn/spconv/src/spconv/maxpool.cc:15:
/home/shawn/spconv/include/tensorview/torch_utils.h: In function ‘tv::TensorView<T, Rank, PtrTraits, Tindex> tv::torch2tv(const at::Tensor&)’:
/home/shawn/spconv/include/tensorview/torch_utils.h:125:52: error: expected primary-expression before ‘(’ token
   return tv::TensorView<T, Rank, PtrTraits, Tindex>(
                                                    ^
/home/shawn/spconv/include/tensorview/torch_utils.h:126:44: error: expected primary-expression before ‘>’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                            ^~
/home/shawn/spconv/include/tensorview/torch_utils.h:126:47: error: expected primary-expression before ‘)’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                               ^
/home/shawn/spconv/src/spconv/maxpool.cc: In lambda function:
/home/shawn/spconv/src/spconv/maxpool.cc:35:52: error: expected primary-expression before ‘>’ token
       auto outFeaturesData = outFeatures.data_ptr<T>();
                                                    ^
/home/shawn/spconv/src/spconv/maxpool.cc:35:54: error: expected primary-expression before ‘)’ token
       auto outFeaturesData = outFeatures.data_ptr<T>();
                                                      ^
/home/shawn/spconv/src/spconv/maxpool.cc:36:50: error: expected primary-expression before ‘>’ token
       auto inFeaturesData = inFeatures.data_ptr<T>();
                                                  ^
/home/shawn/spconv/src/spconv/maxpool.cc:36:52: error: expected primary-expression before ‘)’ token
       auto inFeaturesData = inFeatures.data_ptr<T>();
                                                    ^
/home/shawn/spconv/src/spconv/maxpool.cc:37:52: error: expected primary-expression before ‘>’ token
       auto indicesInData = indicesIn.data_ptr<Index>();
                                                    ^
/home/shawn/spconv/src/spconv/maxpool.cc:37:54: error: expected primary-expression before ‘)’ token
       auto indicesInData = indicesIn.data_ptr<Index>();
                                                      ^
/home/shawn/spconv/src/spconv/maxpool.cc:38:54: error: expected primary-expression before ‘>’ token
       auto indicesOutData = indicesOut.data_ptr<Index>();
                                                      ^
/home/shawn/spconv/src/spconv/maxpool.cc:38:56: error: expected primary-expression before ‘)’ token
       auto indicesOutData = indicesOut.data_ptr<Index>();
                                                        ^
/home/shawn/spconv/src/spconv/maxpool.cc: In lambda function:
/home/shawn/spconv/src/spconv/maxpool.cc:64:52: error: expected primary-expression before ‘>’ token
       auto outFeaturesData = outFeatures.data_ptr<T>();
                                                    ^
/home/shawn/spconv/src/spconv/maxpool.cc:64:54: error: expected primary-expression before ‘)’ token
       auto outFeaturesData = outFeatures.data_ptr<T>();
                                                      ^
/home/shawn/spconv/src/spconv/maxpool.cc:65:50: error: expected primary-expression before ‘>’ token
       auto inFeaturesData = inFeatures.data_ptr<T>();
                                                  ^
/home/shawn/spconv/src/spconv/maxpool.cc:65:52: error: expected primary-expression before ‘)’ token
       auto inFeaturesData = inFeatures.data_ptr<T>();
                                                    ^
/home/shawn/spconv/src/spconv/maxpool.cc:66:38: error: expected primary-expression before ‘>’ token
       auto doutData = dout.data_ptr<T>();
                                      ^
/home/shawn/spconv/src/spconv/maxpool.cc:66:40: error: expected primary-expression before ‘)’ token
       auto doutData = dout.data_ptr<T>();
                                        ^
/home/shawn/spconv/src/spconv/maxpool.cc:67:36: error: expected primary-expression before ‘>’ token
       auto dinData = din.data_ptr<T>();
                                    ^
/home/shawn/spconv/src/spconv/maxpool.cc:67:38: error: expected primary-expression before ‘)’ token
       auto dinData = din.data_ptr<T>();
                                      ^
/home/shawn/spconv/src/spconv/maxpool.cc:68:52: error: expected primary-expression before ‘>’ token
       auto indicesInData = indicesIn.data_ptr<Index>();
                                                    ^
/home/shawn/spconv/src/spconv/maxpool.cc:68:54: error: expected primary-expression before ‘)’ token
       auto indicesInData = indicesIn.data_ptr<Index>();
                                                      ^
/home/shawn/spconv/src/spconv/maxpool.cc:69:54: error: expected primary-expression before ‘>’ token
       auto indicesOutData = indicesOut.data_ptr<Index>();
                                                      ^
/home/shawn/spconv/src/spconv/maxpool.cc:69:56: error: expected primary-expression before ‘)’ token
       auto indicesOutData = indicesOut.data_ptr<Index>();
                                                        ^
In file included from /home/shawn/spconv/include/spconv/spconv_ops.h:20:0,
                 from /home/shawn/spconv/src/spconv/indice.cc:18:
/home/shawn/spconv/include/tensorview/torch_utils.h: In function ‘tv::TensorView<T, Rank, PtrTraits, Tindex> tv::torch2tv(const at::Tensor&)’:
/home/shawn/spconv/include/tensorview/torch_utils.h:125:52: error: expected primary-expression before ‘(’ token
   return tv::TensorView<T, Rank, PtrTraits, Tindex>(
                                                    ^
/home/shawn/spconv/include/tensorview/torch_utils.h:126:44: error: expected primary-expression before ‘>’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                            ^~
/home/shawn/spconv/include/tensorview/torch_utils.h:126:47: error: expected primary-expression before ‘)’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                               ^
/home/shawn/spconv/src/spconv/all.cc: At global scope:
/home/shawn/spconv/src/spconv/all.cc:23:12: error: ‘RegisterOperators’ is not a member of ‘torch’
     torch::RegisterOperators()
            ^~~~~~~~~~~~~~~~~
/home/shawn/spconv/src/spconv/all.cc:23:12: note: suggested alternative:
In file included from /home/shawn/.local/lib/python3.6/site-packages/torch/include/torch/script.h:5:0,
                 from /home/shawn/spconv/include/spconv/indice.h:18,
                 from /home/shawn/spconv/include/spconv/fused_spconv_ops.h:18,
                 from /home/shawn/spconv/src/spconv/all.cc:15:
/home/shawn/.local/lib/python3.6/site-packages/torch/include/torch/csrc/jit/custom_operator.h:221:18: note:   ‘torch::jit::RegisterOperators’
 struct TORCH_API RegisterOperators {
                  ^~~~~~~~~~~~~~~~~
src/spconv/CMakeFiles/spconv.dir/build.make:88: recipe for target 'src/spconv/CMakeFiles/spconv.dir/reordering.cc.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/reordering.cc.o] Error 1
make[2]: *** 正在等待未完成的任务....
src/spconv/CMakeFiles/spconv.dir/build.make:101: recipe for target 'src/spconv/CMakeFiles/spconv.dir/maxpool.cc.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/maxpool.cc.o] Error 1
src/spconv/CMakeFiles/spconv.dir/build.make:62: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all.cc.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/all.cc.o] Error 1
src/spconv/CMakeFiles/spconv.dir/build.make:75: recipe for target 'src/spconv/CMakeFiles/spconv.dir/indice.cc.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/indice.cc.o] Error 1
CMakeFiles/Makefile2:163: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all' failed
make[1]: *** [src/spconv/CMakeFiles/spconv.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 109, in <module>
    zip_safe=False,
  File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/dist-packages/wheel/bdist_wheel.py", line 223, in run
    self.run_command('build')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 49, in run
    self.build_extension(ext)
  File "setup.py", line 93, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
```

**Comment by traveller59** [comment]
the error is due to pytorch version, your pytorch version is too low, the master branch requires torch >= 1.3.

**Comment by Shawn-Zhuang** [comment]
> the error is due to pytorch version, your pytorch version is too low, the master branch requires torch >= 1.3.

It works!!!!!!!BUT when I install pytorch 1.5, I have to remove the whole line containing the Flags "-Wall".\

Thank you for the kind help!!!
