### ISSUE TITLE
python setup.py bdist_wheel error

### ISSUE THREAD

**Issue by halostorm** [traveller59/spconv#201]
### Envs
Python 3.7.4
CUDA 10.0
Pytorch 1.2.0
Ubuntu 16.04
cmake 3.15.4
gcc 5.4.0

### Error logs
```
/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/setuptools/dist.py:720: UserWarning: Module torch was already imported from /usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch
/__init__.py, but /home/duwenwen/Workspace/spconv/.eggs/torch-1.5.1-py3.7-linux-x86_64.egg is being added to sys.path
  pkg_resources.working_set.add(dist, replace=True)
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.7
creating build/lib.linux-x86_64-3.7/spconv
copying spconv/__init__.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/conv.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/functional.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/identity.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/modules.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/ops.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/pool.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/tables.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/test_utils.py -> build/lib.linux-x86_64-3.7/spconv
creating build/lib.linux-x86_64-3.7/spconv/utils
copying spconv/utils/__init__.py -> build/lib.linux-x86_64-3.7/spconv/utils
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10200', '-DCM
AKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/duwenwen/Workspace/spconv/build/lib.linux-x86_64-3.7/spconv',
 '-DCMAKE_BUILD_TYPE=Release']
-- The CXX compiler identification is GNU 5.4.0
-- The CUDA compiler identification is NVIDIA 10.0.130
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Looking for pthread_create in pthread                                                                                                                                                            [177/282]
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "10.0") 
-- Caffe2: CUDA detected: 10.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.0
-- Found CUDNN: /usr/include  
-- Found cuDNN: v7.6.2  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Autodetected CUDA architecture(s):  7.5 7.5
-- Added CUDA NVCC flags for: -gencode;arch=compute_75,code=sm_75
-- Found torch: /usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/lib/libtorch.so  
-- Autodetected CUDA architecture(s):  7.5 7.5
-- Found PythonInterp: /usr/local/anaconda3/envs/pytorch/bin/python3.7 (found suitable version "3.7.4", minimum required is "3.7") 
-- Found PythonLibs: /usr/local/anaconda3/envs/pytorch/lib/libpython3.7m.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- pybind11 v2.5.0
-- Found OpenMP_CXX: -fopenmp (found version "4.0") 
-- Found OpenMP: TRUE (found version "4.0")  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/duwenwen/Workspace/spconv/build/temp.linux-x86_64-3.7
Scanning dependencies of target cuhash
Scanning dependencies of target spconv_nms
[  4%] Building CUDA object src/utils/CMakeFiles/spconv_nms.dir/nms.cu.o
[ 12%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cu.o
[ 12%] Building CXX object src/cuhash/CMakeFiles/cuhash.dir/hash_table.cpp.o
[ 16%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_table.cu.o
[ 20%] Building CXX object src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cpp.o
/home/duwenwen/Workspace/spconv/include/tensorview/tensorview.h(1055): warning: integer conversion resulted in a change of sign

/home/duwenwen/Workspace/spconv/include/tensorview/tensorview.h(1055): warning: integer conversion resulted in a change of sign

[ 25%] Linking CUDA static library libspconv_nms.a
[ 25%] Built target spconv_nms
Scanning dependencies of target spconv_utils
[ 29%] Building CXX object src/utils/CMakeFiles/spconv_utils.dir/all.cc.o
/home/duwenwen/Workspace/spconv/include/tensorview/tensorview.h(1055): warning: integer conversion resulted in a change of sign

/home/duwenwen/Workspace/spconv/include/tensorview/tensorview.h(1067): warning: integer conversion resulted in a change of sign

/home/duwenwen/Workspace/spconv/include/tensorview/tensorview.h(1055): warning: integer conversion resulted in a change of sign

/home/duwenwen/Workspace/spconv/include/tensorview/tensorview.h(1067): warning: integer conversion resulted in a change of sign

[ 33%] Linking CUDA device code CMakeFiles/cuhash.dir/cmake_device_link.o
[ 37%] Linking CXX static library libcuhash.a
[ 37%] Built target cuhash
Scanning dependencies of target spconv
[ 50%] Building CXX object src/spconv/CMakeFiles/spconv.dir/all.cc.o
[ 50%] Building CXX object src/spconv/CMakeFiles/spconv.dir/indice.cc.o
[ 50%] Building CXX object src/spconv/CMakeFiles/spconv.dir/reordering.cc.o
In file included from /home/duwenwen/Workspace/spconv/src/spconv/reordering.cc:17:0:
/home/duwenwen/Workspace/spconv/include/tensorview/torch_utils.h: In function ‘tv::TensorView<T, Rank, PtrTraits, Tindex> tv::torch2tv(const at::Tensor&)’:
/home/duwenwen/Workspace/spconv/include/tensorview/torch_utils.h:125:52: error: expected primary-expression before ‘(’ token
   return tv::TensorView<T, Rank, PtrTraits, Tindex>(
                                                    ^
/home/duwenwen/Workspace/spconv/include/tensorview/torch_utils.h:126:44: error: expected primary-expression before ‘>’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
/home/duwenwen/Workspace/spconv/include/tensorview/torch_utils.h:126:44: error: expected primary-expression before ‘>’ token                                                                        [118/282]
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                            ^
/home/duwenwen/Workspace/spconv/include/tensorview/torch_utils.h:126:47: error: expected primary-expression before ‘)’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                               ^
/home/duwenwen/Workspace/spconv/src/spconv/reordering.cc: In lambda function:
/home/duwenwen/Workspace/spconv/src/spconv/reordering.cc:32:51: error: expected primary-expression before ‘>’ token
       Index *indices_data = indices.data_ptr<Index>();
                                                   ^
/home/duwenwen/Workspace/spconv/src/spconv/reordering.cc:32:53: error: expected primary-expression before ‘)’ token
       Index *indices_data = indices.data_ptr<Index>();
                                                     ^
/home/duwenwen/Workspace/spconv/src/spconv/reordering.cc:33:41: error: expected primary-expression before ‘>’ token
       T *buffer_data = buffer.data_ptr<T>();
                                         ^
/home/duwenwen/Workspace/spconv/src/spconv/reordering.cc:33:43: error: expected primary-expression before ‘)’ token
       T *buffer_data = buffer.data_ptr<T>();
                                           ^
/home/duwenwen/Workspace/spconv/src/spconv/reordering.cc:34:51: error: expected primary-expression before ‘>’ token
       const T *features_data = features.data_ptr<T>();
                                                   ^
/home/duwenwen/Workspace/spconv/src/spconv/reordering.cc:34:53: error: expected primary-expression before ‘)’ token
       const T *features_data = features.data_ptr<T>();
                                                     ^
/home/duwenwen/Workspace/spconv/src/spconv/reordering.cc: In lambda function:
/home/duwenwen/Workspace/spconv/src/spconv/reordering.cc:56:51: error: expected primary-expression before ‘>’ token
       Index *indices_data = indices.data_ptr<Index>();
                                                   ^
/home/duwenwen/Workspace/spconv/src/spconv/reordering.cc:56:53: error: expected primary-expression before ‘)’ token
       Index *indices_data = indices.data_ptr<Index>();
                                                     ^
/home/duwenwen/Workspace/spconv/src/spconv/reordering.cc:57:47: error: expected primary-expression before ‘>’ token
       const T *buffer_data = buffer.data_ptr<T>();
                                               ^
/home/duwenwen/Workspace/spconv/src/spconv/reordering.cc:57:49: error: expected primary-expression before ‘)’ token
       const T *buffer_data = buffer.data_ptr<T>();
                                                 ^
/home/duwenwen/Workspace/spconv/src/spconv/reordering.cc:58:48: error: expected primary-expression before ‘>’ token
       T *features_data = outFeatures.data_ptr<T>();
                                                ^
/home/duwenwen/Workspace/spconv/src/spconv/reordering.cc:58:50: error: expected primary-expression before ‘)’ token
       T *features_data = outFeatures.data_ptr<T>();
                                                  ^
/home/duwenwen/Workspace/spconv/src/spconv/reordering.cc: In lambda function:
/home/duwenwen/Workspace/spconv/src/spconv/reordering.cc:60:41: error: expected primary-expression before ‘>’ token
         const T *buf = buffer.data_ptr<T>();
                                         ^
/home/duwenwen/Workspace/spconv/src/spconv/reordering.cc:60:43: error: expected primary-expression before ‘)’ token
         const T *buf = buffer.data_ptr<T>();
                                           ^
/home/duwenwen/Workspace/spconv/src/spconv/reordering.cc:61:40: error: expected primary-expression before ‘>’ token
         T *out = outFeatures.data_ptr<T>();
                                        ^
/home/duwenwen/Workspace/spconv/src/spconv/reordering.cc:61:42: error: expected primary-expression before ‘)’ token
         T *out = outFeatures.data_ptr<T>();
                                          ^
In file included from /home/duwenwen/Workspace/spconv/include/spconv/fused_spconv_ops.h:20:0,
                 from /home/duwenwen/Workspace/spconv/src/spconv/all.cc:15:
/home/duwenwen/Workspace/spconv/include/tensorview/torch_utils.h: In function ‘tv::TensorView<T, Rank, PtrTraits, Tindex> tv::torch2tv(const at::Tensor&)’:
/home/duwenwen/Workspace/spconv/include/tensorview/torch_utils.h:125:52: error: expected primary-expression before ‘(’ token
/home/duwenwen/Workspace/spconv/include/tensorview/torch_utils.h: In function ‘tv::TensorView<T, Rank, PtrTraits, Tindex> tv::torch2tv(const at::Tensor&)’:                                          [59/282]
/home/duwenwen/Workspace/spconv/include/tensorview/torch_utils.h:125:52: error: expected primary-expression before ‘(’ token
   return tv::TensorView<T, Rank, PtrTraits, Tindex>(
                                                    ^
/home/duwenwen/Workspace/spconv/include/tensorview/torch_utils.h:126:44: error: expected primary-expression before ‘>’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                            ^
/home/duwenwen/Workspace/spconv/include/tensorview/torch_utils.h:126:47: error: expected primary-expression before ‘)’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                               ^
In file included from /home/duwenwen/Workspace/spconv/src/spconv/all.cc:15:0:
/home/duwenwen/Workspace/spconv/include/spconv/fused_spconv_ops.h: In function ‘at::Tensor spconv::fusedIndiceConvBatchNorm(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int64_t, int64_t, int
64_t)’:
/home/duwenwen/Workspace/spconv/include/spconv/fused_spconv_ops.h:41:50: error: expected primary-expression before ‘int’
       std::max_element(indicePairNumCpu.data_ptr<int>(),
                                                  ^
/home/duwenwen/Workspace/spconv/include/spconv/fused_spconv_ops.h:42:50: error: expected primary-expression before ‘int’
                        indicePairNumCpu.data_ptr<int>() + kernelVolume);
                                                  ^
/home/duwenwen/Workspace/spconv/include/spconv/fused_spconv_ops.h:44:57: error: expected primary-expression before ‘int’
       indicePairMaxSizeIter - indicePairNumCpu.data_ptr<int>();
                                                         ^
/home/duwenwen/Workspace/spconv/include/spconv/fused_spconv_ops.h:77:43: error: expected primary-expression before ‘int’
     auto nHot = indicePairNumCpu.data_ptr<int>()[i];
                                           ^
/home/duwenwen/Workspace/spconv/include/spconv/fused_spconv_ops.h:83:75: error: no matching function for call to ‘from_blob(void*, <brace-enclosed initializer list>, c10::TensorOptions&)’
                                              {nHot, numOutPlanes}, options);
                                                                           ^
In file included from /usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:7:0,
                 from /usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/include/torch/script.h:3,
                 from /home/duwenwen/Workspace/spconv/include/spconv/indice.h:18,
                 from /home/duwenwen/Workspace/spconv/include/spconv/fused_spconv_ops.h:18,
                 from /home/duwenwen/Workspace/spconv/src/spconv/all.cc:15:
/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:61:19: note: candidate: at::Tensor torch::from_blob(void*, c10::IntArrayRef, c
10::IntArrayRef, const Deleter&, const c10::TensorOptions&)
 inline at::Tensor from_blob(
                   ^
/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:61:19: note:   candidate expects 5 arguments, 3 provided
/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:79:19: note: candidate: at::Tensor torch::from_blob(void*, c10::IntArrayRef, c
10::IntArrayRef, const c10::TensorOptions&)
 inline at::Tensor from_blob(
                   ^
/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:79:19: note:   no known conversion for argument 2 from ‘<brace-enclosed initia
lizer list>’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:98:19: note: candidate: at::Tensor torch::from_blob(void*, c10::IntArrayRef, c
onst Deleter&, const c10::TensorOptions&)
 inline at::Tensor from_blob(
                   ^
/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:98:19: note:   no known conversion for argument 2 from ‘<brace-enclosed initia
lizer list>’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:114:19: note: candidate: at::Tensor torch::from_blob(void*, c10::IntArrayRef, 
const c10::TensorOptions&)
 inline at::Tensor from_blob(
                   ^
/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:114:19: note:   no known conversion for argument 2 from ‘<brace-enclosed initi
alizer list>’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
In file included from /home/duwenwen/Workspace/spconv/src/spconv/all.cc:15:0:
/home/duwenwen/Workspace/spconv/include/spconv/fused_spconv_ops.h:85:78: error: no matching function for call to ‘from_blob(void*, <brace-enclosed initializer list>, c10::TensorOptions&)’
         torch::from_blob(inputBuffer.data_ptr(), {nHot, numInPlanes}, options);
                                                                              ^
In file included from /usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:7:0,
                 from /usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/include/torch/script.h:3,
                 from /home/duwenwen/Workspace/spconv/include/spconv/indice.h:18,
                 from /home/duwenwen/Workspace/spconv/include/spconv/fused_spconv_ops.h:18,
                 from /home/duwenwen/Workspace/spconv/src/spconv/all.cc:15:
/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:61:19: note: candidate: at::Tensor torch::from_blob(void*, c10::IntArrayRef, c
10::IntArrayRef, const Deleter&, const c10::TensorOptions&)
 inline at::Tensor from_blob(
                   ^
/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:61:19: note:   candidate expects 5 arguments, 3 provided
/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:79:19: note: candidate: at::Tensor torch::from_blob(void*, c10::IntArrayRef, c
10::IntArrayRef, const c10::TensorOptions&)
 inline at::Tensor from_blob(
                   ^
/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:79:19: note:   no known conversion for argument 2 from ‘<brace-enclosed initia
lizer list>’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:98:19: note: candidate: at::Tensor torch::from_blob(void*, c10::IntArrayRef, c
onst Deleter&, const c10::TensorOptions&)
 inline at::Tensor from_blob(
                   ^
/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:98:19: note:   no known conversion for argument 2 from ‘<brace-enclosed initia
lizer list>’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:114:19: note: candidate: at::Tensor torch::from_blob(void*, c10::IntArrayRef, 
const c10::TensorOptions&)
 inline at::Tensor from_blob(
                   ^
/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:114:19: note:   no known conversion for argument 2 from ‘<brace-enclosed initi
alizer list>’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
In file included from /home/duwenwen/Workspace/spconv/src/spconv/all.cc:17:0:
/home/duwenwen/Workspace/spconv/include/spconv/pillar_scatter_ops.h: In function ‘at::Tensor spconv::pointPillarScatter(at::Tensor, at::Tensor, at::Tensor)’:
/home/duwenwen/Workspace/spconv/include/spconv/pillar_scatter_ops.h:40:35: error: expected primary-expression before ‘int’
   auto shapeData = shape.data_ptr<int>();
                                   ^
/home/duwenwen/Workspace/spconv/include/spconv/pillar_scatter_ops.h:43:38: error: could not convert ‘{<expression error>, <expression error>, <expression error>, <expression error>}’ from ‘<brace-enclosed 
initializer list>’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
                    features.options());
                                      ^
In file included from /home/duwenwen/Workspace/spconv/include/spconv/spconv_ops.h:20:0,
                 from /home/duwenwen/Workspace/spconv/src/spconv/indice.cc:18:
/home/duwenwen/Workspace/spconv/include/tensorview/torch_utils.h: In function ‘tv::TensorView<T, Rank, PtrTraits, Tindex> tv::torch2tv(const at::Tensor&)’:
/home/duwenwen/Workspace/spconv/include/tensorview/torch_utils.h:125:52: error: expected primary-expression before ‘(’ token
   return tv::TensorView<T, Rank, PtrTraits, Tindex>(
                                                    ^
/home/duwenwen/Workspace/spconv/include/tensorview/torch_utils.h:126:44: error: expected primary-expression before ‘>’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                            ^
/home/duwenwen/Workspace/spconv/include/tensorview/torch_utils.h:126:47: error: expected primary-expression before ‘)’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                               ^
src/spconv/CMakeFiles/spconv.dir/build.make:88: recipe for target 'src/spconv/CMakeFiles/spconv.dir/reordering.cc.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/reordering.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
src/spconv/CMakeFiles/spconv.dir/build.make:75: recipe for target 'src/spconv/CMakeFiles/spconv.dir/indice.cc.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/indice.cc.o] Error 1
src/spconv/CMakeFiles/spconv.dir/build.make:62: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all.cc.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/all.cc.o] Error 1
CMakeFiles/Makefile2:164: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all' failed
make[1]: *** [src/spconv/CMakeFiles/spconv.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 54%] Linking CXX shared library ../../../lib.linux-x86_64-3.7/spconv/spconv_utils.cpython-37m-x86_64-linux-gnu.so
[ 54%] Built target spconv_utils
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 109, in <module>
    zip_safe=False,
  File "/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/anaconda3/envs/pytorch/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/anaconda3/envs/pytorch/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/anaconda3/envs/pytorch/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
    self.run_command('build')
  File "/usr/local/anaconda3/envs/pytorch/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/anaconda3/envs/pytorch/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/anaconda3/envs/pytorch/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/local/anaconda3/envs/pytorch/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/anaconda3/envs/pytorch/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 49, in run
    self.build_extension(ext)
  File "setup.py", line 93, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/usr/local/anaconda3/envs/pytorch/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

**Comment by sarimmehdi** [comment]
Hi. Did you solve this problem?

**Comment by haige-algo** [comment]
i get the same error, any  suggestion to solve it?

**Comment by oreo-lp** [comment]
i have solved this problem
reference: https://github.com/traveller59/spconv/issues/209#issuecomment-691739469
