### ISSUE TITLE
CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by miraliahmadli** [traveller59/spconv#216]
I am having very strange problem. When I try to pass inputs that is ceated using torch.randn function, I am facing with the issue above in any model I have built. But when I use coords that is returned by the VoxelGenerator, model works just as expected.

System:

- GPU: GTX 1080 Ti  
- CUDA: 10.2
- cuDNN: 8.0
- PyTorch: 1.6.0

Steps to reproduce:

1. Build any model (f.e ExampleNet provided in the README.md)
2. 
```
features = torch.randn(# shape) 
coords = torch.randn(# shape)
output = net(features, coords)
```

When I try like that, it gives `RuntimeError: CUDA error: an illegal memory access was encountered`
```
Traceback (most recent call last):
  File "models/horizon.py", line 184, in <module>
    outputs = net(inputs)
  File "/home/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "models/horizon.py", line 44, in forward
    feature_map = self.layer(features, coors, self.batch_size, self.input_shape)
  File "/home/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xxx.py", line 192, in forward
    ret = self.conv(ret)
  File "/home/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/venv/lib/python3.6/site-packages/spconv/modules.py", line 134, in forward
    input = module(input)
  File "/home/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/venv/lib/python3.6/site-packages/spconv/conv.py", line 181, in forward
    use_hash=self.use_hash)
  File "/home/venv/lib/python3.6/site-packages/spconv/ops.py", line 95, in get_indice_pairs
    int(use_hash))
RuntimeError: CUDA error: an illegal memory access was encountered
```

**Comment by miraliahmadli** [comment]
Oops! I forgot to include coords.int() in the forward function.
