### ISSUE TITLE
Make failed

### ISSUE THREAD

**Issue by dhingratul** [traveller59/spconv#22]
Pytorch: 1.0
Cuda: 9.0
Cmake 3.13

```
[ 35%] Linking CUDA device code CMakeFiles/spconv_nms.dir/cmake_device_link.o
[ 42%] Linking CUDA shared library ../../../lib.linux-x86_64-2.7/spconv/libspconv_nms.so
[ 42%] Built target spconv_nms
[ 50%] Building CXX object src/spconv/CMakeFiles/spconv.dir/reordering.cc.o
92 errors detected in the compilation of "/tmp/tmpxft_000020f5_00000000-6_indice.cpp1.ii".
src/spconv/CMakeFiles/spconv.dir/build.make:88: recipe for target 'src/spconv/CMakeFiles/spconv.dir/indice.cu.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/indice.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Scanning dependencies of target spconv_utils
[ 57%] Building CXX object src/utils/CMakeFiles/spconv_utils.dir/all.cc.o
CMakeFiles/Makefile2:108: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all' failed
make[1]: *** [src/spconv/CMakeFiles/spconv.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 64%] Linking CXX shared library ../../../lib.linux-x86_64-2.7/spconv/spconv_utils.so
[ 64%] Built target spconv_utils
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 86, in <module>
    zip_safe=False,
  File "/home/dhingratul/.virtualenvs/spconv/local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/dhingratul/.virtualenvs/spconv/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 192, in run
    self.run_command('build')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 39, in run
    self.build_extension(ext)
  File "setup.py", line 70, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2

```

**Comment by dhingratul** [comment]
Works with the foll specs:
python 3.5, gcc 6.5(Ubuntu 16.04), nvidia-396, pytorch 1.0, cuda 9.2

**Comment by jianingq** [comment]
Same error

**Comment by venbalas** [comment]
Same error.. Authors please help

**Comment by traveller59** [comment]
@venbalas @jianingq you need to provide more information to solve this problem. this issue looks like python problem, this project don't support python 2.

**Comment by gehuageyan** [comment]
Same error. You can use  '$ python setup.py bdist_wheel  2>&1|tee ./setup.log ' to locate the errors in ./setup.log. I find out that cmake cann't find boost files, so my solution is:
 'sudo apt-get install libboostall-dev or download compressed files from boost official website and copy headers to include path'

**Comment by orthogonal1** [comment]
same error，please help @traveller59

**Comment by Zoe-Yan123** [comment]
same erroe
