### ISSUE TITLE
Error when running python setup.py bdist_wheel

### ISSUE THREAD

**Issue by AngYikHong** [traveller59/spconv#227]
running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/bb1/YikHong/miniconda3/envs/second2/lib/python3.8/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.8', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10600', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/bb1/YikHong/second.pytorch/second/spconv/build/lib.linux-x86_64-3.8/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- Caffe2: CUDA detected: 10.2
-- Caffe2: CUDA nvcc is: /usr/local/cuda-10.2/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-10.2
-- Caffe2: Header version is: 10.2
-- Found cuDNN: v7.6.5  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Autodetected CUDA architecture(s):  7.5
-- Added CUDA NVCC flags for: -gencode;arch=compute_75,code=sm_75
-- Autodetected CUDA architecture(s):  7.5
-- pybind11 v2.5.0
-- Configuring done
CMake Warning at src/spconv/CMakeLists.txt:5 (add_library):
  Cannot generate a safe runtime search path for target spconv because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libnvToolsExt.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda-10.2/lib64

  Some of these libraries may not be found correctly.

CMake Warning at src/spconv/CMakeLists.txt:5 (add_library):
  Cannot generate a safe runtime search path for target spconv because there
  is a cycle in the constraint graph:

    dir 0 is [/home/bb1/YikHong/miniconda3/envs/second2/lib/python3.8/site-packages/torch/lib]
      dir 3 must precede it due to runtime library [libtorch.so]
    dir 1 is [/usr/local/cuda-10.2/lib64/stubs]
    dir 2 is [/usr/local/cuda-10.2/lib64]
    dir 3 is [/home/bb1/YikHong/second/lib/python3.6/site-packages/torch/lib]
      dir 0 must precede it due to runtime library [libc10.so]

  Some of these libraries may not be found correctly.

-- Generating done
-- Build files have been written to: /home/bb1/YikHong/second.pytorch/second/spconv
Error: could not load cache
Traceback (most recent call last):
  File "setup.py", line 97, in <module>
    setup(
  File "/home/bb1/YikHong/miniconda3/envs/second2/lib/python3.8/site-packages/setuptools/__init__.py", line 163, in setup
    return distutils.core.setup(**attrs)
  File "/home/bb1/YikHong/miniconda3/envs/second2/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/bb1/YikHong/miniconda3/envs/second2/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/bb1/YikHong/miniconda3/envs/second2/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/bb1/YikHong/miniconda3/envs/second2/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 290, in run
    self.run_command('build')
  File "/home/bb1/YikHong/miniconda3/envs/second2/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/bb1/YikHong/miniconda3/envs/second2/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/bb1/YikHong/miniconda3/envs/second2/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/bb1/YikHong/miniconda3/envs/second2/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/bb1/YikHong/miniconda3/envs/second2/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 49, in run
    self.build_extension(ext)
  File "setup.py", line 93, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/bb1/YikHong/miniconda3/envs/second2/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 1.

**Comment by zjuwjk** [comment]
hi, @AngYikHong    have you solved this？ I caught the same issue.

**Comment by wu-zhonghua** [comment]
Have you solve this error?
