### ISSUE TITLE
tensorview.h error [python setup.py bdist_wheel failed]

### ISSUE THREAD

**Issue by Angericky** [traveller59/spconv#236]
Hello, thanks for your code and generous sharing!
However, I met some problem during installation, which I thought maybe incorrect use of C++ environment?
```
/anaconda3/lib/python3.7/site-packages/setuptools/dist.py:705: UserWarning: Module torch was already imported from /anaconda3/lib/python3.7/site-packages/torch/__init__.py, but /spconv/.eggs/torch-1.6.0-py3.7-linux-x86_64.egg is being added to sys.path
  pkg_resources.working_set.add(dist, replace=True)
running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/anaconda3/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10100', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- Caffe2: CUDA detected: 9.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda-9.0/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-9.0
-- Caffe2: Header version is: 9.0
-- Found cuDNN: v7.0.4  (include: /usr/local/cuda-9.0/include, library: /usr/local/cuda-9.0/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s):  6.1 6.1 6.1 6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- Autodetected CUDA architecture(s):  6.1 6.1 6.1 6.1
-- pybind11 v2.5.0
-- Configuring done
-- Generating done
-- Build files have been written to: /spconv
[  8%] Built target spconv_nms
[ 12%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cu.o
[ 20%] Building CXX object src/cuhash/CMakeFiles/cuhash.dir/hash_table.cpp.o
[ 20%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_table.cu.o
[ 32%] Built target spconv_utils
In file included from /spconv/include/cuhash/definitions.h:23:0,
                 from /spconv/include/cuhash/debugging.h:21,
                 from /spconv/src/cuhash/hash_table.cpp:17:
/spconv/include/tensorview/tensorview.h:741:23: error: template declaration of ‘constexpr const char* const tv::type_s’
 constexpr const char *type_s = detail::TypeToString<T>::value;
                       ^
/spconv/include/tensorview/tensorview.h: In member function ‘std::string tv::TensorView<T, Rank, PtrTraits, Tindex>::repr(Os&) const’:
/spconv/include/tensorview/tensorview.h:1124:26: error: ‘type_s’ was not declared in this scope
       ss << "Tensor[" << type_s<T> << "]" << std::endl;
                          ^
/spconv/include/tensorview/tensorview.h:1124:34: error: expected primary-expression before ‘>’ token
       ss << "Tensor[" << type_s<T> << "]" << std::endl;
                                  ^
/spconv/include/tensorview/tensorview.h:1124:36: error: expected primary-expression before ‘<<’ token
       ss << "Tensor[" << type_s<T> << "]" << std::endl;
                                    ^
/spconv/include/tensorview/tensorview.h:1135:24: error: ‘type_s’ was not declared in this scope
     ss << "Tensor[" << type_s<T> << "]: shape=" << shape()
                        ^
/spconv/include/tensorview/tensorview.h:1135:32: error: expected primary-expression before ‘>’ token
     ss << "Tensor[" << type_s<T> << "]: shape=" << shape()
                                ^
/spconv/include/tensorview/tensorview.h:1135:34: error: expected primary-expression before ‘<<’ token
     ss << "Tensor[" << type_s<T> << "]: shape=" << shape()
                                  ^
/spconv/include/tensorview/tensorview.h: At global scope:
/spconv/include/tensorview/tensorview.h:1270:23: error: template declaration of ‘constexpr const char* const tv::detail::type_printf_format_v’
 constexpr const char *type_printf_format_v = TypePrintfFormat<T>::value;
                       ^
/spconv/include/tensorview/tensorview.h: In function ‘void tv::printTensorView(tv::TensorView<T, Rank, PtrTraits, Tindex>)’:
/spconv/include/tensorview/tensorview.h:1343:34: error: ‘type_printf_format_v’ is not a member of ‘tv::detail’
   return printTensorView(tensor, detail::type_printf_format_v<Traw>);
                                  ^
/spconv/include/tensorview/tensorview.h:1343:67: error: expected primary-expression before ‘>’ token
   return printTensorView(tensor, detail::type_printf_format_v<Traw>);
                                                                   ^
/spconv/include/tensorview/tensorview.h:1343:68: error: expected primary-expression before ‘)’ token
   return printTensorView(tensor, detail::type_printf_format_v<Traw>);
                                                                    ^
/spconv/include/tensorview/tensorview.h: In function ‘void tv::printTensorView(const T*, tv::Shape)’:
/spconv/include/tensorview/tensorview.h:1349:26: error: ‘type_printf_format_v’ is not a member of ‘tv::detail’
                          detail::type_printf_format_v<Traw>);
                          ^
/spconv/include/tensorview/tensorview.h:1349:59: error: expected primary-expression before ‘>’ token
                          detail::type_printf_format_v<Traw>);
                                                           ^
/spconv/include/tensorview/tensorview.h:1349:60: error: expected primary-expression before ‘)’ token
                          detail::type_printf_format_v<Traw>);
                                                            ^
gmake[2]: *** [src/cuhash/CMakeFiles/cuhash.dir/hash_table.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
/spconv/include/tensorview/tensorview.h(152): warning: extra ";" ignored

/spconv/include/tensorview/tensorview.h(152): warning: extra ";" ignored

/spconv/include/tensorview/tensorview.h(741): error: "type_s" is not a function or static data member

/spconv/include/tensorview/tensorview.h(741): error: "constexpr" is not valid here

/spconv/include/tensorview/tensorview.h(1055): warning: integer conversion resulted in a change of sign

/spconv/include/tensorview/tensorview.h(1270): error: "type_printf_format_v" is not a function or static data member

/spconv/include/tensorview/tensorview.h(1270): error: "constexpr" is not valid here

/spconv/include/tensorview/tensorview.h(741): error: "type_s" is not a function or static data member

/spconv/include/tensorview/tensorview.h(741): error: "constexpr" is not valid here

/spconv/include/tensorview/tensorview.h(1055): warning: integer conversion resulted in a change of sign

/spconv/include/tensorview/tensorview.h(1270): error: "type_printf_format_v" is not a function or static data member

/spconv/include/tensorview/tensorview.h(1270): error: "constexpr" is not valid here

4 errors detected in the compilation of "/tmp/tmpxft_0022989c_00000000-7_hash_functions.cpp1.ii".
4 errors detected in the compilation of "/tmp/tmpxft_002298f5_00000000-7_hash_table.cpp1.ii".
gmake[2]: *** [src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cu.o] Error 2
gmake[2]: *** [src/cuhash/CMakeFiles/cuhash.dir/hash_table.cu.o] Error 2
gmake[1]: *** [src/cuhash/CMakeFiles/cuhash.dir/all] Error 2
gmake: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 109, in <module>
    zip_safe=False,
  File "anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in setup
    return distutils.core.setup(**attrs)
  File "/anaconda3/envs/pt1.4-share/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/anaconda3/envs/pt1.4-share/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/anaconda3/envs/pt1.4-share/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/anaconda3/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 290, in run
    self.run_command('build')
  File "/anaconda3/envs/pt1.4-share/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/anaconda3/envs/pt1.4-share/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/anaconda3/envs/pt1.4-share/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/anaconda3/envs/pt1.4-share/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/anaconda3/envs/pt1.4-share/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 49, in run
    self.build_extension(ext)
  File "setup.py", line 93, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/anaconda3/envs/pt1.4-share/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
```

**Comment by oreo-lp** [comment]
me too! but i don't to how to solve this problems

**Comment by oreo-lp** [comment]
i have sloved this problem
reference:https://github.com/traveller59/spconv/issues/209#issuecomment-691739469
