### ISSUE TITLE
python setup.py bdist_wheel failed

### ISSUE THREAD

**Issue by snslmi** [traveller59/spconv#239]
running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/lotte_fashion_ai/anaconda3/lib/python3.6/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10600', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/lotte_fashion_ai/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- Caffe2: CUDA detected: 10.1
-- Caffe2: CUDA nvcc is: /usr/local/cuda-10.1/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-10.1
-- Caffe2: Header version is: 10.1
-- Found cuDNN: v7.6.5  (include: /usr/local/cuda-10.1/include, library: /usr/local/cuda-10.1/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s):  7.5
-- Added CUDA NVCC flags for: -gencode;arch=compute_75,code=sm_75
-- Autodetected CUDA architecture(s):  7.5
-- pybind11 v2.5.0
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP: TRUE   
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_CUBLAS
    linked by target "cuhash" in directory /home/lotte_fashion_ai/spconv/src/cuhash
    linked by target "spconv" in directory /home/lotte_fashion_ai/spconv/src/spconv

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
Traceback (most recent call last):
  File "setup.py", line 114, in <module>
    zip_safe=False,
  File "/home/lotte_fashion_ai/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/lotte_fashion_ai/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/lotte_fashion_ai/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/lotte_fashion_ai/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/lotte_fashion_ai/.local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 290, in run
    self.run_command('build')
  File "/home/lotte_fashion_ai/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/lotte_fashion_ai/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/lotte_fashion_ai/anaconda3/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/lotte_fashion_ai/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/lotte_fashion_ai/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 54, in run
    self.build_extension(ext)
  File "setup.py", line 97, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/lotte_fashion_ai/anaconda3/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/lotte_fashion_ai/spconv', '-DCMAKE_PREFIX_PATH=/home/lotte_fashion_ai/anaconda3/lib/python3.6/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10600', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/lotte_fashion_ai/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

did anyone solve this problem??plz help..

**Comment by arxidinakbar** [comment]
You may try this configurations, in my case, it is caused by wrong pytorch version.
### configurations:

python=3.7.0
pytorch=1.3.0 # the most important one, has to be 1.3.0 version
torchvision=0.4.0 # if you use conda install, it would install the version suits your pytorch.
CUDA 10.1
cmake=3.13.2 # I used conda install, NO need for PATH adding. And make sure it is the same version.

**Comment by snslmi** [comment]
solved the error by reinstalling pytorch 1.3.0 version thankyou!
but i've got another error please help!



running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/lotte_fashion_ai/anaconda3/envs/OpenPCDet/lib/python3.6/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10301', '-DSPCONV_BuildCUDA=OFF', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/lotte_fashion_ai/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- Caffe2: CUDA detected: 10.1
-- Caffe2: CUDA nvcc is: /usr/local/cuda-10.1/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-10.1
-- Caffe2: Header version is: 10.1
-- Found cuDNN: v7.6.5  (include: /usr/local/cuda-10.1/include, library: /usr/local/cuda-10.1/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s):  7.5
-- Added CUDA NVCC flags for: -gencode;arch=compute_75,code=sm_75
CMake Warning (dev) at /usr/local/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (torch) does
  not match the name of the calling package (Torch).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /home/lotte_fashion_ai/anaconda3/lib/python3.6/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:103 (find_package_handle_standard_args)
  CMakeLists.txt:22 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- pybind11 v2.5.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lotte_fashion_ai/spconv/build/temp.linux-x86_64-3.6
Scanning dependencies of target spconv_utils
[ 10%] Building CXX object src/utils/CMakeFiles/spconv_utils.dir/all.cc.o
Scanning dependencies of target spconv
[ 20%] Building CXX object src/spconv/CMakeFiles/spconv.dir/indice.cc.o
[ 30%] Building CXX object src/spconv/CMakeFiles/spconv.dir/all.cc.o
[ 40%] Building CXX object src/spconv/CMakeFiles/spconv.dir/reordering.cc.o
[ 50%] Building CXX object src/spconv/CMakeFiles/spconv.dir/maxpool.cc.o
[ 60%] Building CXX object src/spconv/CMakeFiles/spconv.dir/nms.cc.o
[ 70%] Building CXX object src/spconv/CMakeFiles/spconv.dir/spconv_ops.cc.o
[ 80%] Building CXX object src/spconv/CMakeFiles/spconv.dir/pool_ops.cc.o
[ 90%] Linking CXX shared library ../../../lib.linux-x86_64-3.6/spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so
[ 90%] Built target spconv_utils
[100%] Linking CXX shared library ../../../lib.linux-x86_64-3.6/spconv/libspconv.so
/usr/bin/ld: cannot find -lCUDA_cublas_LIBRARY-NOTFOUND
collect2: error: ld returned 1 exit status
src/spconv/CMakeFiles/spconv.dir/build.make:211: recipe for target '../lib.linux-x86_64-3.6/spconv/libspconv.so' failed
make[2]: *** [../lib.linux-x86_64-3.6/spconv/libspconv.so] Error 1
CMakeFiles/Makefile2:155: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all' failed
make[1]: *** [src/spconv/CMakeFiles/spconv.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 114, in <module>
    zip_safe=False,
  File "/home/lotte_fashion_ai/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/lotte_fashion_ai/anaconda3/envs/OpenPCDet/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/lotte_fashion_ai/anaconda3/envs/OpenPCDet/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/lotte_fashion_ai/anaconda3/envs/OpenPCDet/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/lotte_fashion_ai/.local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 290, in run
    self.run_command('build')
  File "/home/lotte_fashion_ai/anaconda3/envs/OpenPCDet/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/lotte_fashion_ai/anaconda3/envs/OpenPCDet/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/lotte_fashion_ai/anaconda3/envs/OpenPCDet/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/lotte_fashion_ai/anaconda3/envs/OpenPCDet/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/lotte_fashion_ai/anaconda3/envs/OpenPCDet/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 54, in run
    self.build_extension(ext)
  File "setup.py", line 98, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/lotte_fashion_ai/anaconda3/envs/OpenPCDet/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

**Comment by snslmi** [comment]
> You may try this configurations, in my case, it is caused by wrong pytorch version.
> 
> ### configurations:
> python=3.7.0
> pytorch=1.3.0 # the most important one, has to be 1.3.0 version
> torchvision=0.4.0 # if you use conda install, it would install the version suits your pytorch.
> CUDA 10.1
> cmake=3.13.2 # I used conda install, NO need for PATH adding. And make sure it is the same version.


pytorch 1.3.0 version 
cmake 3.18.2 # conda install -c anaconda cmake

this helped me solve the problem 
thankyou!:)
