### ISSUE TITLE
I got a problem when running  "sudo python spconv/setup.py bdist_wheel", help me plz

### ISSUE THREAD

**Issue by ButtercatT** [traveller59/spconv#249]
ERROR: Exception:
Traceback (most recent call last):
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 437, in _error_catcher
    yield
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""          
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read   
    data = self.__fp.read(amt)                                   
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/http/client.py", line 457, in read                                         
    n = self.readinto(b)                                         
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/http/client.py", line 501, in readinto                                     
    n = self.fp.readinto(b)                                      
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/socket.py", line 589, in readinto                                          
    return self._sock.recv_into(b)                               
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/ssl.py", line 1071, in recv_into                                           
    return self.read(nbytes, buffer)                             
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/ssl.py", line 929, in read                                                 
    return self._sslobj.read(len, buffer)                        
socket.timeout: The read operation timed out                     

During handling of the above exception, another exception occurred:                                                               

Traceback (most recent call last):                               
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 228, in _main       
    status = self.run(options, args)                             
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper      
    return func(self, options, args)                             
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/site-packages/pip/_internal/commands/wheel.py", line 156, in run           
    reqs, check_supported_wheels=True                            
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve                                                            
    discovered_reqs.extend(self._resolve_one(requirement_set, req))                                                               
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one                                                       
    abstract_dist = self._get_abstract_dist_for(req_to_install)  
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 340, in _get_abstract_dist_for                                             
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 469, in prepare_linked_requirement                                                 
    hashes=self._get_linked_req_hashes(req)                      
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 259, in unpack_url
    hashes=hashes,                                               
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 130, in get_http_url                                                               
    link, downloader, temp_dir.path, hashes                      
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 282, in _download_http_url                                                         
    for chunk in download.chunks:                                
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/site-packages/pip/_internal/network/utils.py", line 88, in response_chunks 
    decode_content=False,                                        
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 576, in stream        
    data = self.read(amt=amt, decode_content=decode_content)     
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 541, in read          
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)                                                              
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/contextlib.py", line 130, in __exit__                                      
    self.gen.throw(type, value, traceback)                       
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 442, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")  
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.    
Traceback (most recent call last):
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/site-packages/setuptools/installer.py", line 126, in fetch_build_egg
    subprocess.check_call(cmd)
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/satoya/.conda/envs/Pcdet10/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp6mfwiawj', '--quiet', 'torch>=1.3.0']' returned non-zero exit status 2.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "spconv/setup.py", line 108, in <module>
    zip_safe=False,
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/site-packages/setuptools/__init__.py", line 152, in setup
    _install_setup_requires(attrs)
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/site-packages/setuptools/dist.py", line 676, in fetch_build_eggs
    replace_conflicting=True,
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/site-packages/pkg_resources/__init__.py", line 766, in resolve
    replace_conflicting=replace_conflicting
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1049, in best_match
    return self.obtain(req, installer)
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1061, in obtain
    return installer(requirement)
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/site-packages/setuptools/dist.py", line 732, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/home/satoya/.conda/envs/Pcdet10/lib/python3.7/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
    raise DistutilsError(str(e)) from e
distutils.errors.DistutilsError: Command '['/home/satoya/.conda/envs/Pcdet10/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp6mfwiawj', '--quiet', 'torch>=1.3.0']' returned non-zero exit status 2.
(Pcdet10)

**Comment by ButtercatT** [comment]
pytorch ver.1.2.0
cuda 10.0
cmake ver.3.19.0-rc

tried everything to solve it ,bt didn't work at all.

**Comment by tojimahammatov** [comment]
increase your torch version higher than 1.3, for example 1.5.

**Comment by sioan** [comment]
torch 1.6.0. works for this
