### ISSUE TITLE
Failed: python bdist wheel

### ISSUE THREAD

**Issue by Xelawk** [traveller59/spconv#264]
### What's wrong with that???
```sh
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/spconv
copying spconv/ops.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/conv.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/pool.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/tables.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/modules.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/__init__.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/identity.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/functional.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/test_utils.py -> build/lib.linux-x86_64-3.6/spconv
creating build/lib.linux-x86_64-3.6/spconv/utils
copying spconv/utils/__init__.py -> build/lib.linux-x86_64-3.6/spconv/utils
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/anaconda3/envs/dev/lib/python3.6/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10301', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Dev/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- The CXX compiler identification is GNU 5.4.0
-- The CUDA compiler identification is NVIDIA 10.1.243
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "10.1") 
-- Caffe2: CUDA detected: 10.1
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.1
-- Found CUDNN: //usr/lib/x86_64-linux-gnu/libcudnn.so  
-- Found cuDNN: v7.6.5  (include: //usr/include, library: //usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Autodetected CUDA architecture(s):  6.0
-- Added CUDA NVCC flags for: -gencode;arch=compute_60,code=sm_60
CMake Warning (dev) at /home/anaconda3/envs/dev/lib/python3.6/site-packages/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (torch) does
  not match the name of the calling package (Torch).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /home/anaconda3/envs/dev/lib/python3.6/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:103 (find_package_handle_standard_args)
  CMakeLists.txt:22 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found torch: /home/anaconda3/envs/dev/lib/python3.6/site-packages/torch/lib/libtorch.so  
-- Autodetected CUDA architecture(s):  6.0
CMake Error at CMakeLists.txt:41 (add_subdirectory):
  add_subdirectory given source "third_party/pybind11" which is not an
  existing directory.


-- Found OpenMP_CXX: -fopenmp (found version "4.0") 
-- Found OpenMP: TRUE (found version "4.0")  
-- Configuring incomplete, errors occurred!
See also "/Dev/spconv/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
See also "/Dev/spconv/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 108, in <module>
    zip_safe=False,
  File "/home/anaconda3/envs/dev/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/anaconda3/envs/dev/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/anaconda3/envs/dev/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/anaconda3/envs/dev/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/anaconda3/envs/dev/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/home/anaconda3/envs/dev/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/anaconda3/envs/dev/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/anaconda3/envs/dev/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/anaconda3/envs/dev/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/anaconda3/envs/dev/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 48, in run
    self.build_extension(ext)
  File "setup.py", line 91, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/anaconda3/envs/dev/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/Dev/spconv', '-DCMAKE_PREFIX_PATH=/home/anaconda3/envs/dev/lib/python3.6/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10301', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Dev/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
```

**Comment by sainisanjay** [comment]
@Xelawk I am also getting same error. Did you able to solve the issue?

**Comment by Xelawk** [comment]
> @Xelawk I am also getting same error. Did you able to solve the issue?

Yep, I have solve it. Before you install the setup.py, you need to clone the repo with --recursive, because the third_party direcotory need to be cloned completely.

**Comment by sainisanjay** [comment]
Thanks @Xelawk but while i am installing i am getting below error. Could you help me to solve this:
`ERROR: spconv-1.2.1-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.`

**Comment by Xelawk** [comment]
> Thanks @Xelawk but while i am installing i am getting below error. Could you help me to solve this:
> `ERROR: spconv-1.2.1-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.`
> 
> My anaconda environment is with Python 3.7 but when i install using command `sudo pip install spconv-1.2.1-cp37-cp37m-linux_x86_64.whl` it look like uses Python 3.5.
> 
> ```
> DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
> ERROR: spconv-1.2.1-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.
> WARNING: You are using pip version 20.2.4; however, version 20.3.1 is available.
> You should consider upgrading via the '/usr/local/bin/python3.5 -m pip install --upgrade pip' command.
> ```

You should check python version by command ｀conda list｀

**Comment by ReunionJ** [comment]
> Thanks @Xelawk but while i am installing i am getting below error. Could you help me to solve this:
> `ERROR: spconv-1.2.1-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.`
> 
> My anaconda environment is with Python 3.7 but when i install using command `sudo pip install spconv-1.2.1-cp37-cp37m-linux_x86_64.whl` it look like uses Python 3.5.
> 
> ```
> DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
> ERROR: spconv-1.2.1-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.
> WARNING: You are using pip version 20.2.4; however, version 20.3.1 is available.
> You should consider upgrading via the '/usr/local/bin/python3.5 -m pip install --upgrade pip' command.
> ```

https://blog.csdn.net/happywlg123/article/details/107281936

**Comment by smallzm** [comment]
> > @Xelawk我也遇到同样的错误。你能解决问题吗？
> 
> 是的，我已经解决了。在安装 setup.py 之前，需要使用 --recursive 克隆 repo，因为需要完全克隆第三方目录。

hello, Since I didn't clone SPconv from GitHub, I downloaded spconv directly to use, so which directory should I put the subproject in
