### ISSUE TITLE
No CUDA toolset found. - win10, cuda-v9.1

### ISSUE THREAD

**Issue by ghimiredhikura** [traveller59/spconv#27]
```ruby
PS F:\3D-Object-Detection\spconv> python .\setup.py bdist_wheel
running bdist_wheel
running build
running build_py
creating build
creating build\lib.win-amd64-3.6
creating build\lib.win-amd64-3.6\spconv
copying spconv\conv.py -> build\lib.win-amd64-3.6\spconv
copying spconv\functional.py -> build\lib.win-amd64-3.6\spconv
copying spconv\modules.py -> build\lib.win-amd64-3.6\spconv
copying spconv\ops.py -> build\lib.win-amd64-3.6\spconv
copying spconv\pool.py -> build\lib.win-amd64-3.6\spconv
copying spconv\test_utils.py -> build\lib.win-amd64-3.6\spconv
copying spconv\__init__.py -> build\lib.win-amd64-3.6\spconv
creating build\lib.win-amd64-3.6\spconv\utils
copying spconv\utils\__init__.py -> build\lib.win-amd64-3.6\spconv\utils
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=C:\\ProgramData\\Anaconda3\\lib\\site-packages\\torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=F:\\3D-Object-Detection\\spconv\\build\\lib.win-amd64-3.6\\spconv', '-DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=F:\\3D-Object-Detection\\spconv\\build\\lib.win-amd64-3.6\\spconv', '-A', 'x64']
-- Building for: Visual Studio 15 2017
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
-- The CXX compiler identification is MSVC 19.16.27026.1
CMake Error at C:/Program Files/CMake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:271 (message):
  No CUDA toolset found.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  C:/Program Files/CMake/share/cmake-3.13/Modules/CMakeDetermineCUDACompiler.cmake:72 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!
See also "F:/3D-Object-Detection/spconv/build/temp.win-amd64-3.6/Release/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File ".\setup.py", line 89, in <module>
    zip_safe=False,
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "C:\ProgramData\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 202, in run
    self.run_command('build')
  File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File ".\setup.py", line 40, in run
    self.build_extension(ext)
  File ".\setup.py", line 72, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', 'F:\\3D-Object-Detection\\spconv', '-DCMAKE_PREFIX_PATH=C:\\ProgramData\\Anaconda3\\lib\\site-packages\\torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=F:\\3D-Object-Detection\\spconv\\build\\lib.win-amd64-3.6\\spconv', '-DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=F:\\3D-Object-Detection\\spconv\\build\\lib.win-amd64-3.6\\spconv', '-A', 'x64']' returned non-zero exit status 1.
```
Does it only supports cuda-v10? Thanks.

**Comment by traveller59** [comment]
Where is your cuda install location? This is a cmake problem, it can't find your cuda installation.
I need content of CMakeError.log to get more information of this error.

**Comment by ghimiredhikura** [comment]
This is output log. 
[CMakeOutput.log](https://github.com/traveller59/spconv/files/3005977/CMakeOutput.log)

My cuda installation location is 
```
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1
```

Note: I am using anaconda.

**Comment by traveller59** [comment]
this isn't the error log file...
I guess this problem is that cuda 9.x don't support newest visual studio, check the "build from source" part of this [page](https://github.com/pytorch/pytorch), you may need to install toolset 14.11 and follow some commands in that page to compile spconv with cuda 9.x. This is why I recommend to use cuda 10.

**Comment by ghimiredhikura** [comment]
Now I'm using cuda 10, but got another error. It says that it can't find cudnn

[CMakeError.log](https://github.com/traveller59/spconv/files/3007106/CMakeError.log)

```
PS G:\3D-Object-Detection\second-v1.5.1\spconv> python setup.py bdist_wheel
running bdist_wheel
running build
running build_py
creating build
creating build\lib.win-amd64-3.6
creating build\lib.win-amd64-3.6\spconv
copying spconv\conv.py -> build\lib.win-amd64-3.6\spconv
copying spconv\functional.py -> build\lib.win-amd64-3.6\spconv
copying spconv\modules.py -> build\lib.win-amd64-3.6\spconv
copying spconv\ops.py -> build\lib.win-amd64-3.6\spconv
copying spconv\pool.py -> build\lib.win-amd64-3.6\spconv
copying spconv\test_utils.py -> build\lib.win-amd64-3.6\spconv
copying spconv\__init__.py -> build\lib.win-amd64-3.6\spconv
creating build\lib.win-amd64-3.6\spconv\utils
copying spconv\utils\__init__.py -> build\lib.win-amd64-3.6\spconv\utils
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=C:\\Users\\user\\Anaconda3\\lib\\site-packages\\torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=G:\\3D-Object-Detection\\second-v1.5.1\\spconv\\build\\lib.win-amd64-3.6\\spconv', '-DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=G:\\3D-Object-Detection\\second-v1.5.1\\spconv\\build\\lib.win-amd64-3.6\\spconv', '-A', 'x64']
-- Building for: Visual Studio 14 2015
-- Selecting Windows SDK version  to target Windows 10.0.17134.
-- The CXX compiler identification is MSVC 19.0.24215.1
-- The CUDA compiler identification is NVIDIA 10.1.105
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/bin/nvcc.exe
-- Check for working CUDA compiler: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/bin/nvcc.exe -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - not found
-- Found Threads: TRUE
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1 (found suitable version "10.1", minimum required is "7.0")
-- Caffe2: CUDA detected: 10.1.105
-- Caffe2: CUDA nvcc is: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/bin/nvcc.exe
-- Caffe2: CUDA toolkit directory: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1
-- Caffe2: Header version is: 10.1
-- Could NOT find CUDNN (missing: CUDNN_INCLUDE_DIR CUDNN_LIBRARY)
CMake Warning at C:/Users/user/Anaconda3/Lib/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:110 (message):
  Caffe2: Cannot find cuDNN library.  Turning the option off
Call Stack (most recent call first):
  C:/Users/user/Anaconda3/Lib/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  C:/Users/user/Anaconda3/Lib/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:39 (find_package)
  CMakeLists.txt:23 (find_package)


-- Autodetected CUDA architecture(s): 6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
CMake Error at C:/Users/user/Anaconda3/Lib/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:96 (message):
  Your installed Caffe2 version uses cuDNN but I cannot find the cuDNN
  libraries.  Please set the proper cuDNN prefixes and / or install cuDNN.
Call Stack (most recent call first):
  C:/Users/user/Anaconda3/Lib/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:39 (find_package)
  CMakeLists.txt:23 (find_package)


-- Configuring incomplete, errors occurred!
See also "G:/3D-Object-Detection/second-v1.5.1/spconv/build/temp.win-amd64-3.6/Release/CMakeFiles/CMakeOutput.log".
See also "G:/3D-Object-Detection/second-v1.5.1/spconv/build/temp.win-amd64-3.6/Release/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 89, in <module>
    zip_safe=False,
  File "C:\Users\user\Anaconda3\lib\site-packages\setuptools\__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\user\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\user\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\user\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\user\Anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 204, in run
    self.run_command('build')
  File "C:\Users\user\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\user\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\user\Anaconda3\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Users\user\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\user\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 40, in run
    self.build_extension(ext)
  File "setup.py", line 72, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "C:\Users\user\Anaconda3\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', 'G:\\3D-Object-Detection\\second-v1.5.1\\spconv', '-DCMAKE_PREFIX_PATH=C:\\Users\\user\\Anaconda3\\lib\\site-packages\\torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=G:\\3D-Object-Detection\\second-v1.5.1\\spconv\\build\\lib.win-amd64-3.6\\spconv', '-DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=G:\\3D-Object-Detection\\second-v1.5.1\\spconv\\build\\lib.win-amd64-3.6\\spconv', '-A', 'x64']' returned non-zero exit status 1.
PS G:\3D-Object-Detection\second-v1.5.1\spconv>
```

**Comment by traveller59** [comment]
have you installed cudnn? download cudnn files, extract and copy libraries and includes to cuda installation directory.
The error in your log file looks not important.

**Comment by ghimiredhikura** [comment]
@traveller59 
My bad, cudnn was not installed! 
After Installing cudnn and adding boost library files it works without any error. 
Thanks for your help. ^^
