### ISSUE TITLE
Build files written, but no make files found ??

### ISSUE THREAD

**Issue by triple-tam** [traveller59/spconv#271]
Hello, I'm running `python setup.py bdist_wheel` and am confused by the error output. It says `build files have been written` AND `no makefile found` AND `Command cmake ... returned non-zero exit status 2`. 
What could all this mean?

Here is my output:

> (venv_centerpoint) tranthi@atcremers45:~/thesis/00_repos/spconv$ python setup.py bdist_wheel
> running bdist_wheel
> running build
> running build_py
> running build_ext
> Release
> |||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/usr/stud/tranthi/thesis/01_venvs/venv_centerpoint/lib/python3.6/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/usr/stud/tranthi/thesis/00_repos/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_BUILD_TYPE=Release']
> -- Caffe2: CUDA detected: 10.2
> -- Caffe2: CUDA nvcc is: /usr/local/cuda-10.2/bin/nvcc
> -- Caffe2: CUDA toolkit directory: /usr/local/cuda-10.2
> -- Caffe2: Header version is: 10.2
> -- Found cuDNN: v7.4.2  (include: /usr/stud/tranthi/cuda/include, library: /usr/stud/tranthi/cuda/lib64/libcudnn.so)
> -- Autodetected CUDA architecture(s):  6.1
> -- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
> -- pybind11 v2.5.0
> -- Configuring done
> CMake Warning (dev) in src/spconv/CMakeLists.txt:
>   Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
>   empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
>   for policy details.  Use the cmake_policy command to set the policy and
>   suppress this warning.
> 
>   CUDA_ARCHITECTURES is empty for target "spconv".
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) in src/spconv/CMakeLists.txt:
>   Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
>   empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
>   for policy details.  Use the cmake_policy command to set the policy and
>   suppress this warning.
> 
>   CUDA_ARCHITECTURES is empty for target "spconv".
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) in src/utils/CMakeLists.txt:
>   Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
>   empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
>   for policy details.  Use the cmake_policy command to set the policy and
>   suppress this warning.
> 
>   CUDA_ARCHITECTURES is empty for target "spconv_nms".
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) in src/utils/CMakeLists.txt:
>   Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
>   empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
>   for policy details.  Use the cmake_policy command to set the policy and
>   suppress this warning.
> 
>   CUDA_ARCHITECTURES is empty for target "spconv_nms".
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Generating done
> -- Build files have been written to: /usr/stud/tranthi/thesis/00_repos/spconv
> make: *** No targets specified and no makefile found.  Stop.
> Traceback (most recent call last):
>   File "setup.py", line 89, in <module>
>     zip_safe=False,
>   File "/usr/stud/tranthi/thesis/01_venvs/venv_centerpoint/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
>     return distutils.core.setup(**attrs)
>   File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
>     self.run_command(cmd)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/stud/tranthi/thesis/01_venvs/venv_centerpoint/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 290, in run
>     self.run_command('build')
>   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
>     self.run_command(cmd_name)
>   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "setup.py", line 40, in run
>     self.build_extension(ext)
>   File "setup.py", line 73, in build_extension
>     subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
>   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

Ubuntu 18.04
Python 3.6.9
Pytorch 1.7.1
CUDA 10.2.89
Cmake 3.19.1
GCC 7.5.0
I also set $cmake -DCMAKE_CXX_FLAGS="-I /usr/include", which is where my boost headers are located.

Would appreciate any thoughts! Thanks :)

**Comment by triple-tam** [comment]
These are also the contents of my `spconv` directory, showing that the makefiles are there
build

> CMakeFiles
> CMakeLists.txt
> detect_cuda_version.cc 
> LICENSE
> README.md
> spconv
> test
> CMakeCache.txt
> cmake_install.cmake
> detect_cuda_compute_capabilities.cu
> include
> Makefile
> setup.py
> src
> third_party

**Comment by triple-tam** [comment]
I was able to install successfully - by using the ultimate tech solution of all - restarting! I made a new clone of spconv and did the installation steps from the beginning. And now it works ^_^
