### ISSUE TITLE
python setup.py bdist_wheel

### ISSUE THREAD

**Issue by TimGor1997** [traveller59/spconv#286]
I am getting the above error, when trying to run python setup.py bdist_wheel.
I am using Ubuntu 16.04, cuda 8.0
I have create a conda environment called PVRCNN, cuda 9.2, torch 1.3.0, but it doesn't work

(PVRCNN) zzq@zzq:~/spconv$ python setup.py bdist_wheel
running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/zzq/anaconda3/envs/PVRCNN/lib/python3.6/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10300', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/zzq/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- **Caffe2: CUDA detected: 8.0**
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
CMake Error at /home/zzq/anaconda3/envs/PVRCNN/lib/python3.6/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:42 (message):
  **PyTorch requires CUDA 9.0 and above**.
Call Stack (most recent call first):
  /home/zzq/anaconda3/envs/PVRCNN/lib/python3.6/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /home/zzq/anaconda3/envs/PVRCNN/lib/python3.6/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
  CMakeLists.txt:24 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/zzq/spconv/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
See also "/home/zzq/spconv/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 108, in <module>
    zip_safe=False,
  File "/home/zzq/anaconda3/envs/PVRCNN/lib/python3.6/site-packages/setuptools/__init__.py", line 163, in setup
    return distutils.core.setup(**attrs)
  File "/home/zzq/anaconda3/envs/PVRCNN/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/zzq/anaconda3/envs/PVRCNN/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/zzq/anaconda3/envs/PVRCNN/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/zzq/anaconda3/envs/PVRCNN/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/home/zzq/anaconda3/envs/PVRCNN/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/zzq/anaconda3/envs/PVRCNN/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/zzq/anaconda3/envs/PVRCNN/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/zzq/anaconda3/envs/PVRCNN/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/zzq/anaconda3/envs/PVRCNN/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 48, in run
    self.build_extension(ext)
  File "setup.py", line 91, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/zzq/anaconda3/envs/PVRCNN/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/zzq/spconv', '-DCMAKE_PREFIX_PATH=/home/zzq/anaconda3/envs/PVRCNN/lib/python3.6/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10300', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/zzq/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

**Comment by rttariverdi67** [comment]
@TimGor1997 have you solved this error? I face with same problem!

**Comment by twn29004** [comment]
have you solved this error? I face with same problem!

**Comment by ReunionJ** [comment]
have you solved this error? I face with same problem!

**Comment by ReunionJ** [comment]
git clone https://github.com/traveller59/spconv.git --recursive
or (chinese)
git clone https://github.com.cnpmjs.org/traveller59/spconv.git --recursive

**Comment by turtleMaster20** [comment]
Update your cmake>=3.13 [here](https://askubuntu.com/questions/355565/how-do-i-install-the-latest-version-of-cmake-from-the-command-line)
