### ISSUE TITLE
cuda runtime error

### ISSUE THREAD

**Issue by bigsheep2012** [traveller59/spconv#29]
Hello Yan @traveller59 ,

I got the following error when I try to increase the batch size. 
I am trying to add branches to middle sparse layers.  I can train the network when batch size <=3, while get errors when batch size >=4.
Environment:
GPU: 1080ti
OS: Ubuntu 16.04
Cuda 10.0, pytorch 1.0, python 2.7

The network structure is like:

```
def forward(self, voxel_features, coors, self.sparse_shape, batch_size):
ret0 = spconv.SparseConvTensor(voxel_features, coors, self.sparse_shape, batch_size)
ret1 = self.middle_conv_block1(ret0)   ##spconv.SparseSequential
ret2 = self.middle_conv_block2(ret1)   ##spconv.SparseSequential
ret3 = self.middle_conv_block3(ret2)   ##spconv.SparseSequential
ret4 = self.middle_conv_block3(ret3)   ##spconv.SparseSequential

branch_feature_2 = self.sparse_branch_1(ret2)  ##spconv.SparseSequential
branch_feature_3 = self.sparse_branch_2(ret3)  ##spconv.SparseSequential

predict1 = self.rpn1(branch_feature_2.dense())   ##  nn.conv2d
predict2 = self.rpn2(branch_feature_3.dense())   ##  nn.conv2d
predict3 = self.rpn3(ret4.dense())                         ##  nn.conv2d

return predict1, predict2, predict3
```
The error is:
```
Traceback (most recent call last):
  File "main.py", line 238, in <module>
    main()
  File "main.py", line 234, in main
    exp.run()
  File "main.py", line 180, in run
    self.trainer.run(epoch, mode="train")
  File "/media/DataCenter/deeplearningoflidar/YL/mjj2/projects/anchor_based/apollo_spenet/trainer.py", line 396, in run
    predict = self.model(voxels,coors,num_points, batch_size)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/DataCenter/deeplearningoflidar/YL/mjj2/projects/anchor_based/apollo_spenet/model/SPENet/spenet.py", line 294, in forward
    sparse_feature = self.middle_sparse(vfe_feature,coors,batch_size)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/DataCenter/deeplearningoflidar/YL/mjj2/projects/anchor_based/apollo_spenet/model/SPENet/spenet.py", line 264, in forward
    branch_feature3 = self.sparse_branch_2(ret3)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spconv/modules.py", line 127, in forward
    input.features = module(input.features)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/batchnorm.py", line 76, in forward
    exponential_average_factor, self.eps)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py", line 1623, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: cuda runtime error (9) : invalid configuration argument at /pytorch/aten/src/ATen/native/cuda/Normalization.cuh:459
```

Any idea why this is happening? 
Thanks in advance.

**Comment by wangfudong** [comment]
@bigsheep2012 
Hi, I also meet similar issues when 'batch_size > 1', have you fixed it? Tks~
