### ISSUE TITLE
Install successfully but import issue

### ISSUE THREAD

**Issue by LeopoldACC** [traveller59/spconv#312]
hi, @xmyqsh  @traveller59  @dev-fennek 
I installed successfully but can not import
My environment is 
```shell
ubuntu20.04
cuda11.1
pytorch 1.8.1
```
The error info is as below.
```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gz/桌面/spconv/spconv/spconv/__init__.py", line 21, in <module>
    from spconv import ops, utils
  File "/home/gz/桌面/spconv/spconv/spconv/utils/__init__.py", line 17, in <module>
    from spconv import spconv_utils
ImportError: cannot import name 'spconv_utils' from partially initialized module 'spconv' (most likely due to a circular import) (/home/gz/桌面/spconv/spconv/spconv/__init__.py)
```

**Comment by LeopoldACC** [comment]
Sorry to interrupt.I forget the command `cd ./dist && pip install xxx.whl`
