### ISSUE TITLE
CMake Error after running `python setup.py bdist_wheel`

### ISSUE THREAD

**Issue by RawHeatG** [traveller59/spconv#315]
CMake Error after running `python setup.py bdist_wheel` 
Environment: python 3.7, PyTorch 1.6.0, cmake 3.20
Here's the error log it generates
```
Error:
python setup                                                                  .py bdist_wheel
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.7
creating build/lib.linux-x86_64-3.7/spconv
copying spconv/ops.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/tables.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/modules.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/__init__.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/identity.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/functional.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/pool.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/test_utils.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/conv.py -> build/lib.linux-x86_64-3.7/spconv
creating build/lib.linux-x86_64-3.7/spconv/utils
copying spconv/utils/__init__.py -> build/lib.linux-x86_64-3.7/spconv/utils
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/das/anaconda3/envs/secdet/lib/p                                                                  ython3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildT                                                                  ests=OFF', '-DPYTORCH_VERSION=10600', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-conste                                                                  xpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBR                                                                  ARY_OUTPUT_DIRECTORY=/home/das/SecDet/second.pytorch/second/spconv/build/lib.lin                                                                  ux-x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- The CXX compiler identification is GNU 7.5.0
-- The CUDA compiler identification is unknown
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:6 (project):
  No CMAKE_CUDA_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/home/das/SecDet/second.pytorch/second/spconv/build/temp.linux-x86_64-                                                                  3.7/CMakeFiles/CMakeOutput.log".
See also "/home/das/SecDet/second.pytorch/second/spconv/build/temp.linux-x86_64-                                                                  3.7/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 108, in <module>
    zip_safe=False,
  File "/home/das/anaconda3/envs/secdet/lib/python3.7/site-packages/setuptools/_                                                                  _init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/das/anaconda3/envs/secdet/lib/python3.7/distutils/core.py", line 1                                                                  48, in setup
    dist.run_commands()
  File "/home/das/anaconda3/envs/secdet/lib/python3.7/distutils/dist.py", line 9                                                                  66, in run_commands
    self.run_command(cmd)
  File "/home/das/anaconda3/envs/secdet/lib/python3.7/distutils/dist.py", line 9                                                                  85, in run_command
    cmd_obj.run()
  File "/home/das/anaconda3/envs/secdet/lib/python3.7/site-packages/wheel/bdist_                                                                  wheel.py", line 299, in run
    self.run_command('build')
  File "/home/das/anaconda3/envs/secdet/lib/python3.7/distutils/cmd.py", line 31                                                                  3, in run_command
    self.distribution.run_command(command)
  File "/home/das/anaconda3/envs/secdet/lib/python3.7/distutils/dist.py", line 9                                                                  85, in run_command
    cmd_obj.run()
  File "/home/das/anaconda3/envs/secdet/lib/python3.7/distutils/command/build.py                                                                  ", line 135, in run
    self.run_command(cmd_name)
  File "/home/das/anaconda3/envs/secdet/lib/python3.7/distutils/cmd.py", line 31                                                                  3, in run_command
    self.distribution.run_command(command)
  File "/home/das/anaconda3/envs/secdet/lib/python3.7/distutils/dist.py", line 9                                                                  85, in run_command
    cmd_obj.run()
  File "setup.py", line 48, in run
    self.build_extension(ext)
  File "setup.py", line 91, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_                                                                  temp, env=env)
  File "/home/das/anaconda3/envs/secdet/lib/python3.7/subprocess.py", line 363,                                                                   in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/das/SecDet/second.pytor                                                                  ch/second/spconv', '-DCMAKE_PREFIX_PATH=/home/das/anaconda3/envs/secdet/lib/pyth                                                                  on3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTest                                                                  s=OFF', '-DPYTORCH_VERSION=10600', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr                                                                  " -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY                                                                  _OUTPUT_DIRECTORY=/home/das/SecDet/second.pytorch/second/spconv/build/lib.linux-                                                                  x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status             
```

**Comment by RawHeatG** [comment]
This is how the env PATH looks like ```/home/das/miniconda3/bin:/home/das/anaconda3/envs/secdet/bin:/home/das/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin```
Output of nvcc -V:
```nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85```

**Comment by shanniruo** [comment]
@RawHeatG I have the same problem. Have you solved it？

**Comment by arsalan311** [comment]
@RawHeatG were you able to solve it?... I am also having the same problem...Tried a lot of things

**Comment by t2wang** [comment]
Same problem here. Any ideas why?
