### ISSUE TITLE
AttributeError: module 'spconv' has no attribute 'SparseModule'

### ISSUE THREAD

**Issue by mc171819** [traveller59/spconv#324]
hi, i have fully install spconv-1.2.1 and i can import correctly. But it showed an error like this:
Traceback (most recent call last):
  File "train.py", line 6, in <module>
    from test import repeat_eval_ckpt
  File "/home/mc/Project/Voxel-R-CNN-main/tools/test.py", line 13, in <module>
    from eval_utils import eval_utils
  File "/home/mc/Project/Voxel-R-CNN-main/tools/eval_utils/eval_utils.py", line 8, in <module>
    from pcdet.models import load_data_to_gpu
  File "/home/mc/Project/OpenPCDet/pcdet/models/__init__.py", line 6, in <module>
    from .detectors import build_detector
  File "/home/mc/Project/OpenPCDet/pcdet/models/detectors/__init__.py", line 1, in <module>
    from .detector3d_template import Detector3DTemplate
  File "/home/mc/Project/OpenPCDet/pcdet/models/detectors/detector3d_template.py", line 7, in <module>
    from .. import backbones_2d, backbones_3d, dense_heads, roi_heads
  File "/home/mc/Project/OpenPCDet/pcdet/models/backbones_3d/__init__.py", line 2, in <module>
    from .spconv_backbone import VoxelBackBone8x, VoxelResBackBone8x
  File "/home/mc/Project/OpenPCDet/pcdet/models/backbones_3d/spconv_backbone.py", line 29, in <module>
    class SparseBasicBlock(spconv.SparseModule):
AttributeError: module 'spconv' has no attribute 'SparseModule'

can you give me some suggestion to resolve this?

**Comment by abreu4** [comment]
I'm having a similar issue 

```
Traceback (most recent call last):
  File "src/train.py", line 273, in <module>
    main()
  File "src/train.py", line 63, in main
    main_worker(configs.gpu_idx, configs)
  File "src/train.py", line 97, in main_worker
    model = create_model(configs)
  File "/home/tiago_cronai_ai/cron/centernet3d-pytorch/src/models/model_utils.py", line 24, in create_model
    model = CenterNet3D(configs.sparse_shape, configs.heads, configs.head_conv, configs.num_input_features)
  File "/home/tiago_cronai_ai/cron/centernet3d-pytorch/src/models/centernet3d.py", line 28, in __init__
    self.net3d = spconv.SparseSequential(
AttributeError: module 'spconv' has no attribute 'SparseSequential'
```

Ive compiled the library on an environment with PyTorch 1.6.0, CUDA 11.4 and cuDNN 8. Any idea what might be causing this?

**Comment by mjmjeong** [comment]
`from spconv.pytorch import ops
from spconv.pytorch.conv import (SparseConv2d, SparseConv3d, SparseConvTranspose2d,
                         SparseConvTranspose3d, SparseInverseConv2d,
                         SparseInverseConv3d, SubMConv2d, SubMConv3d)
from spconv.pytorch.core import SparseConvTensor
from spconv.pytorch.identity import Identity
from spconv.pytorch.modules import SparseModule, SparseSequential
from spconv.pytorch.ops import ConvAlgo
from spconv.pytorch.pool import SparseMaxPool2d, SparseMaxPool3d
from spconv.pytorch.tables import AddTable, ConcatTable`

I am not sure you have already solved it or not. 
As the version was updated, the path was changed.
I solved this problem by changing spconv.SparseSequential -> SparseSequential & import module with proper path as shown in upper snippet. 
Thank you.

**Comment by stu-zhangxl** [comment]
Hello, I have also encountered this issue. I would like to deploy this environment using Github instead of directly using pip installation The spconv 2.2.0 version has been selected here I have tried to directly install spconv 2.3.6 version through pip, but this issue also exists May I ask, what method is used to solve this problem? thanks~
![image](https://github.com/traveller59/spconv/assets/67547959/221e8ebd-bb4d-4426-b620-09eed9abc3ee)

**Comment by yingqianxian** [comment]
open OpenPCDet/pcdet/models/backbones_3d/spconv_backbone.py
change as follow
![openpcdet_demo](https://github.com/traveller59/spconv/assets/101318500/03a99749-5944-4dff-a560-b9f8d8dd4635)

**Comment by VLadImirluren** [comment]
Have you solve this problem?I meet the same problem as yours
