### ISSUE TITLE
RuntimeError: derivative for to_sparse is not implemented

### ISSUE THREAD

**Issue by peddivarunkumar99** [traveller59/spconv#334]
Traceback (most recent call last):
  File "main.py", line 113, in <module>
    main(config)
  File "main.py", line 73, in main
    solver.train()
  File "/home/snap_user/Image_Segmentation/solver1.py", line 162, in train
    loss.backward()
  File "/home/snap_user/anaconda3/lib/python3.8/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/snap_user/anaconda3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
RuntimeError: derivative for to_sparse is not implemented

Any clue of how this can be solved?

**Comment by Haoran-P** [comment]
Hi, I met the same problem. Is it solved?

**Comment by peddivarunkumar99** [comment]
Unfortunately no.

**Comment by hh-xiaohu** [comment]
the same problem....
