### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by xiaobaishu0097** [traveller59/spconv#340]
Thanks for your excellent work!

I am trying to install Spconv 2.0 with the latest pytorch 1.10.0 and Cuda 11.4 or Cuda 11.5. However, I meet different errors when I try to install Spconv with ``pip install spconv-cu114`` or building from source.

If I use ``pip install spconv-cu114``, when I try to run ``import spconv.pytorch as spconv``, I met the following error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/du014/anaconda3/envs/pointcloud-mk2/lib/python3.8/site-packages/spconv/pytorch/__init__.py", line 8, in <module>
    from spconv.pytorch.conv import (SparseConv2d, SparseConv3d, SparseConvTranspose2d,
  File "/home/du014/anaconda3/envs/pointcloud-mk2/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 29, in <module>
    from spconv.pytorch.core import IndiceData, SparseConvTensor
  File "/home/du014/anaconda3/envs/pointcloud-mk2/lib/python3.8/site-packages/spconv/pytorch/core.py", line 17, in <module>
    from .core_fx import *
  File "/home/du014/anaconda3/envs/pointcloud-mk2/lib/python3.8/site-packages/spconv/pytorch/core_fx.py", line 20, in <module>
    from torch.fx.symbolic_trace import ProxyableClassMeta
ModuleNotFoundError: No module named 'torch.fx.symbolic_trace'
```

But when I turn to building spconv from source, I met another import error as following:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/du014/anaconda3/envs/pointcloud-mk2/lib/python3.8/site-packages/spconv/pytorch/__init__.py", line 7, in <module>
    from spconv.pytorch import ops
  File "/home/du014/anaconda3/envs/pointcloud-mk2/lib/python3.8/site-packages/spconv/pytorch/ops.py", line 22, in <module>
    from spconv.algo import AlgoHint, ConvAlgo
  File "/home/du014/anaconda3/envs/pointcloud-mk2/lib/python3.8/site-packages/spconv/algo.py", line 18, in <module>
    from spconv.core_cc.cumm.gemm.main import GemmAlgoDesp, GemmMainUnitTest, GemmParams
ModuleNotFoundError: No module named 'spconv.core_cc'
```
BTW, I have already install ``cum-cu114``.

Could you help me with this import bug?

**Comment by FindDefinition** [comment]
If you encounter any problem, just submit a issue or put log here, I have enough time today.

**Comment by mengshiyu0109** [comment]
looking forward to a new version ,I also have this issue ,
  File "D:\pythoncoder\Anaconda3\lib\site-packages\spconv\algo.py", line 18, in <module>
    from spconv.core_cc.cumm.gemm.main import GemmAlgoDesp, GemmMainUnitTest, GemmParams
ModuleNotFoundError: No module named 'spconv.core_cc'

**Comment by sidml** [comment]
Putting my solution for reference.

    File "/opt/conda/lib/python3.7/site-packages/spconv/conv.py", line 181, in forward
    use_hash=self.use_hash)
    File "/opt/conda/lib/python3.7/site-packages/spconv/ops.py", line 95, in get_indice_pairs
    int(use_hash))
    ValueError: /home/sid/spconv/src/spconv/spconv_ops.cc 87
    unknown device type

I got this error because I had previously compiled a different version of spconv and was reusing the build folder. Removing the build folder and building the wheel again from scratch solved the issue.

**Comment by sunwenzhang1996** [comment]
> looking forward to a new version ,I also have this issue , File "D:\pythoncoder\Anaconda3\lib\site-packages\spconv\algo.py", line 18, in from spconv.core_cc.cumm.gemm.main import GemmAlgoDesp, GemmMainUnitTest, GemmParams ModuleNotFoundError: No module named 'spconv.core_cc'

have you slove this problem?

**Comment by sharknow** [comment]
1987年9月14日21时07分 中国第一封电子邮件 从北京发往德国 "越过长城,走向世界" QQ邮箱,常联系!您好，这是来自QQ邮箱的自动回复邮件。
