### ISSUE TITLE
IndexError: list index out of range using SubMConv3d with spconv 2.0.2

### ISSUE THREAD

**Issue by abhinavagarwalla** [traveller59/spconv#353]
I came across the same issue as [this](https://github.com/traveller59/spconv/issues/73), and decided to upgrade spconv from 1.2.1 to 2.0.2.
After updating and making the necessary architecture changes, I encounter this: 
``IndexError: list index out of range``.
The error is encountered at this [line](https://github.com/hongfz16/DS-Net/blob/004fb2cc5366754d4135afb8b2777e4c4e0029a7/network/modules/spconv_unet.py#L222), while upsampling the input using convolutions. The same code runs smoothly for 1.2.1. Is there a breaking change here that I missed?

I did follow the mentioned changes in the README.

**Comment by FindDefinition** [comment]
Could you please provide full traceback? I can't determine the error line in spconv.

**Comment by abhinavagarwalla** [comment]
Yes, sure. I was also wondering if I should share the traceback.

Traceback (most recent call last):
  File "cfg_train.py", line 368, in <module>
    PolarOffsetMain(args, cfg)
  File "cfg_train.py", line 234, in PolarOffsetMain
    ret_dict = model(inputs)
  File "anaconda3/envs/spconv2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "anaconda3/envs/spconv2/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 705, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "anaconda3/envs/spconv2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "src/DS-Net/network/model_zoo.py", line 434, in forward
    sem_fea, ins_fea = self.backbone(feature_3d, coor, len(batch['grid']))
  File "anaconda3/envs/spconv2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "src/DS-Net/network/modules/spconv_unet.py", line 340, in forward
    up4e = self.upBlock0(down4c, down4b)
  File "anaconda3/envs/spconv2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "src/DS-Net/network/modules/spconv_unet.py", line 221, in forward
    upE = self.conv3(upE)
  File "anaconda3/envs/spconv2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "anaconda3/envs/spconv2/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 247, in forward
    out_features = Fsp.indice_subm_conv(features, self.weight,
  File "anaconda3/envs/spconv2/lib/python3.8/site-packages/spconv/pytorch/functional.py", line 87, in forward
    return ops.indice_conv(features,
  File "anaconda3/envs/spconv2/lib/python3.8/site-packages/spconv/pytorch/ops.py", line 222, in indice_conv
    nhot_profile = indice_pair_num_cpu[profile_idx]
IndexError: list index out of range


Here, conv3 = spconv.SubMConv3d(in_planes, out_planes, kernel_size=3, stride=stride,
                     padding=1, bias=False, indice_key=indice_key)

**Comment by FindDefinition** [comment]
This error shouldn't happen. Could you add a debug line ```print(filters.shape,indice_pair_num_cpu )``` to anaconda3/envs/spconv2/lib/python3.8/site-packages/spconv/pytorch/ops.py before the error line, then post the print content here?
 ​

**Comment by abhinavagarwalla** [comment]
Hi! I rechecked the code. For submconv, the stride is always 1.
Output of the debug line just before the erro: ``torch.Size([27, 512, 512]) [4017, 4874, 4046, 4832, 0, 0, 0, 0, 0]``

**Comment by FindDefinition** [comment]
You need to check your filter size and indice key, i think your indice key is wrong. Input filter ksize is 3x3x3, but prod of ksize of shared indice data is 9.

**Comment by abhinavagarwalla** [comment]
I will check the filter size and indice key once. I think that that shouldn't be an issue since the code works for spconv 1.2.1. 
I do use asymmetrical kernel size as (3, 1, 3) or (1, 3, 3) for some layers. Do you think that could be an issue?

**Comment by abhinavagarwalla** [comment]
It turned out the indice key was being reused from another conv3d which had kernel size as (1,3,3). On fixing the indice key, the error disappeared.

**Comment by MissShihongHowRU** [comment]
@abhinavagarwalla  Hi, I encountered the same error. How do you fix the bug?

**Comment by MissShihongHowRU** [comment]
I just fixed the error by assigning a unique indice_key for each SubMConv3d.

**Comment by FindDefinition** [comment]
@MissShihongHowRU you shouldn't assign unique id for each submconv3d, subm3d with same spatial structure (for example, all subm layers between two pooling operation) can use same id to improve performance.

**Comment by louzq16** [comment]
@FindDefinition, I also faced that problem when using SubMconv2d. Only assigning unique id  can solve my problem....
