### ISSUE TITLE
idx < int(shape_.ndim()) assert faild. 1 [994717]

### ISSUE THREAD

**Issue by SienChen1997** [traveller59/spconv#354]
I installed pre-built spconv-cu111, and get a strange RuntimeError as below, it works well when trainning, but when testing, it breaks a bug,don't know what the reason. Below is the trceback:
```

(PIFu) cse@4-way-2080Ti-Server:/home/8T/cse/tocsn/PIFu$ sh scripts/test.sh 
+ GPU_ID=0
+ DISPLAY_ID=10
+ NAME=126111535847796
+ BATCH_SIZE=1
+ MLP_DIM=288 1024 512 256 128 1
+ MLP_DIM_COLOR=513 1024 512 256 128 3
+ VOL_RES=256
+ CHECKPOINTS_NETG_PATH=./checkpoints/test/netG_epoch_3
+ CHECKPOINTS_NETC_PATH=./checkpoints/net_C
+ TEST_FOLDER_PATH=126111535847796
+ CUDA_VISIBLE_DEVICES=0 python ./apps/eval.py --name 126111535847796 --batch_size 1 --mlp_dim 288 1024 512 256 128 1 --mlp_dim_color 513 1024 512 256 128 3 --num_stack 4 --num_hourglass 2 --resolution 256 --hg_down ave_pool --norm group --norm_color group --test_folder_path 126111535847796 --load_netG_checkpoint_path ./checkpoints/test/netG_epoch_3
initialize network with normal
Using Network:  hgpifu
0it [00:00, ?it/s]/mnt/8T/cse/dataset/twindom/image/126111535847796/000_000_001.png /mnt/8T/cse/dataset/twindom/mask/126111535847796/000_000_001.png
save to ./results/126111535847796
generate mesh...
0it [00:01, ?it/s]
Traceback (most recent call last):
  File "./apps/eval.py", line 159, in <module>
    evaluator.eval(data, True)
  File "./apps/eval.py", line 142, in eval
    gen_mesh(opt, self.netG, self.cuda, data, save_path, use_octree=use_octree)
  File "/mnt/8T/cse/tocsn/PIFu/lib/train_util.py", line 49, in gen_mesh
    net.filter(image_tensor, heatmap_tensor)
  File "/mnt/8T/cse/tocsn/PIFu/lib/model/HGPIFuNet.py", line 142, in filter
    self.vol_feat = self.volume_filter(features, indices)
  File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/8T/cse/tocsn/PIFu/lib/model/VolumeEncoder.py", line 31, in forward
    out = self.net(x)
  File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/site-packages/spconv/pytorch/modules.py", line 137, in forward
    input = module(input)
  File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/site-packages/spconv/pytorch/conv.py", line 260, in forward
    outids.shape[0], self.algo)
  File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/site-packages/spconv/pytorch/functional.py", line 34, in forward
    algo=algo)
  File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/site-packages/spconv/pytorch/ops.py", line 270, in indice_conv
    stream=stream)
  File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/site-packages/spconv/algo.py", line 323, in profile_and_cache
    arch, shuffle_type)
  File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/site-packages/spconv/algo.py", line 133, in get_all_available
    lda = a.dim(1)
RuntimeError: /tmp/pip-req-build-6pwqe0kz/include/tensorview/tensor.h(729)
idx < int(shape_.ndim()) assert faild. 1 [994717]
```

**Comment by FindDefinition** [comment]
this error means the shape of your features of SparseConvTensor become [994717], could you please find out when does features become 1d tensor?

**Comment by SienChen1997** [comment]
Ah that's my problem, the input data of testing didn't include N dimnesion and it works well now :D
