### ISSUE TITLE
IndexError with GEMM and float16 in spconv 2.0.2

### ISSUE THREAD

**Issue by abhinavagarwalla** [traveller59/spconv#356]
I am trying to train a model with spconv layers using `torch.cuda.amp.autocast`.
The model runs fine with full-precision but leads to the following error on half-precision.

```
Traceback (most recent call last):
  File "cfg_train_half.py", line 375, in <module>
    PolarOffsetMain(args, cfg)
  File "cfg_train_half.py", line 238, in PolarOffsetMain
    ret_dict = model(inputs)
  File "anaconda3/envs/spconv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "anaconda3/envs/spconv/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 705, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "anaconda3/envs/spconv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "anaconda3/envs/spconv/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 138, in decorate_autocast
    return func(*args, **kwargs)
  File "network/model_zoo.py", line 438, in forward
    sem_fea, ins_fea = self.backbone(feature_3d, coor, len(batch['grid']))
  File "anaconda3/envs/spconv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "network/modules/spconv_unet.py", line 337, in forward
    ret = self.downCntx(ret)
  File "anaconda3/envs/spconv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "network/modules/spconv_unet.py", line 72, in forward
    shortcut = self.conv1(x)
  File "anaconda3/envs/spconv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "anaconda3/envs/spconv/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 251, in forward
    out_features = Fsp.indice_subm_conv(features, self.weight,
  File "anaconda3/envs/spconv/lib/python3.8/site-packages/spconv/pytorch/functional.py", line 87, in forward
    return ops.indice_conv(features,
  File "anaconda3/envs/spconv/lib/python3.8/site-packages/spconv/pytorch/ops.py", line 259, in indice_conv
    profile_res, min_time = GEMM.profile_and_cache(
  File "anaconda3/envs/spconv/lib/python3.8/site-packages/spconv/algo.py", line 459, in profile_and_cache
    res = all_profile_res[min_idx]
IndexError: list index out of range
```

`print(len(all_profile_res), min_idx)` gives '0 -1'

**Comment by FindDefinition** [comment]
could you provide num input channels and out channels of this error layer?

**Comment by abhinavagarwalla** [comment]
GPU Name: 3090
input channels: 16
output channels: 32

More context:
This layer is the very first layer that's applied to the input voxel grid after converting the tensor into `SparseConvTensor`.

**Comment by FindDefinition** [comment]
This will be fixed in spconv 2.1.
the amp auto-cast looks a little complex, we may delay spconv 2.1 release date again.

**Comment by FindDefinition** [comment]
you can 1. ```import torch.cuda.amp as amp``` 2. add decorators ```@amp.custom_fwd(cast_inputs=torch.float16)``` to all forward and ```@amp.custom_bwd``` to all backward functions in spconv/pytorch/functional.py to have a try on mixed training.
but we have a bug with fp16, you also must need to use float16 in inference. this bug is due to wrong gemm algo cache, will be fixed in next release.

**Comment by abhinavagarwalla** [comment]
I tried training using the mixed training suggested by you. But that resulted in the network not learning. I am not sure if this is due to the fp16 bug? Did you fix it?
