### ISSUE TITLE
python setup.py bdist_wheel error

### ISSUE THREAD

**Issue by alukade** [traveller59/spconv#361]
(second) root@alukade-System-Product-Name:/home/alukade/spconv-8da6f967fb9a054d8870c3515b1b44eca2103634# python setup.py bdist_wheel
running bdist_wheel
running build
running build_py
running build_ext
/home/alukade/spconv-8da6f967fb9a054d8870c3515b1b44eca2103634/build/lib.linux-x86_64-3.6
Release
CMake Error at /home/alukade/anaconda3/envs/second/lib/python3.6/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package):
  Found package configuration file:

    /home/alukade/anaconda3/envs/second/lib/python3.6/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake

  but it set Caffe2_FOUND to FALSE so package "Caffe2" is considered to be
  NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing: gloo_hip

Call Stack (most recent call first):
  CMakeLists.txt:23 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/alukade/spconv-8da6f967fb9a054d8870c3515b1b44eca2103634/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
See also "/home/alukade/spconv-8da6f967fb9a054d8870c3515b1b44eca2103634/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 86, in <module>
    zip_safe=False,
  File "/home/alukade/anaconda3/envs/second/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/alukade/anaconda3/envs/second/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/alukade/anaconda3/envs/second/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/alukade/anaconda3/envs/second/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/alukade/anaconda3/envs/second/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/home/alukade/anaconda3/envs/second/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/alukade/anaconda3/envs/second/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/alukade/anaconda3/envs/second/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/alukade/anaconda3/envs/second/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/alukade/anaconda3/envs/second/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 39, in run
    self.build_extension(ext)
  File "setup.py", line 69, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/alukade/anaconda3/envs/second/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/alukade/spconv-8da6f967fb9a054d8870c3515b1b44eca2103634', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/alukade/spconv-8da6f967fb9a054d8870c3515b1b44eca2103634/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_PREFIX_PATH=/home/alukade/anaconda3/envs/second/lib/python3.6/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

and my cuda version is 11.0
howt to fix it?

**Comment by Ymr-zyh** [comment]
did you fix it?  I have the same problem as you

**Comment by alukade** [comment]
> did you fix it? I have the same problem as you

Not yet,I tried cuda10.0 before,it can be installed. I update the cuda version to 11.1,it failed.

**Comment by Ymr-zyh** [comment]
hey boy  look at issue#305. there's a reply by DipDipPotatoChips 28 days ago. i fixed the problem by following the txt and i think it may help you to fix this problem.
