### ISSUE TITLE
CUDA error: too many resources requested for launch at spconv/ops.py indice_conv() using spconv 1.2.1

### ISSUE THREAD

**Issue by jonasmeyer1** [traveller59/spconv#362]
I want to use OpenPCDet v0.3 on a NVIDIA Jetson TX2 with the following specifications:

Ubuntu 18.04
JetPack 4.4
CUDA 10.2
CuDNN 8.0
Python 3.6.9
pytorch 1.6.0
spconv 1.2.1

All the 3D object detection methods which relies on spconv (SECOND, PartA2 etc.) failed due to a CUDA error ```RuntimeError: CUDA error: too many resources requested for launch```. The other methods, like PointRCNN or PointPillars worked properly.  Since there is no JetPack version which supports CUDA 11, I can not update spconv to version 2.x. Does anyone know how to solve this issue?

Thanks

```
Traceback (most recent call last):
  File "extract_bb.py", line 146, in <module>
    main()
  File "extract_bb.py", line 116, in main
    pred_dicts, _ = model.forward(data_dict)
  File "/home/nvidia/MTh_meyj/Software/OpenPCDet/pcdet/models/detectors/voxel_rcnn.py", line 11, in forward
    batch_dict = cur_module(batch_dict)
  File "/home/nvidia/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/nvidia/MTh_meyj/Software/OpenPCDet/pcdet/models/backbones_3d/spconv_backbone.py", line 147, in forward
    x = self.conv_input(input_sp_tensor)
  File "/home/nvidia/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/nvidia/.local/lib/python3.6/site-packages/spconv/modules.py", line 134, in forward
    input = module(input)
  File "/home/nvidia/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/nvidia/.local/lib/python3.6/site-packages/spconv/conv.py", line 199, in forward
    outids.shape[0], self.algo)
  File "/home/nvidia/.local/lib/python3.6/site-packages/spconv/functional.py", line 94, in forward
    algo=algo)
  File "/home/nvidia/.local/lib/python3.6/site-packages/spconv/ops.py", line 120, in indice_conv
    int(inverse), int(subm), algo)
RuntimeError: CUDA error: too many resources requested for launch
```

**Comment by FindDefinition** [comment]
spconv 2.1 will support cuda 10.2 and add greatly faster fp16 inference, will be released in this weekend.

**Comment by jonasmeyer1** [comment]
Thanks for the information, I will try to use this version with OpenPCDet.

**Comment by jonasmeyer1** [comment]
Finally, I got it work.

The update to spconv 2.1 is not necessary.
Since the Jetson TX2 is based on cuda sm_1x, only the number of threads per block has to be adjusted.

Therefore go to https://github.com/traveller59/spconv/blob/v1.2.1/include/tensorview/cuda_utils.h#L13

Change ```CUDA_NUM_THREADS = 1024``` to ```CUDA_NUM_THREADS = 512``

Note that these changes are also relevant for the Pytorch installation. See https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-10-now-available/72048
