### ISSUE TITLE
issues when running bdist_wheel

### ISSUE THREAD

**Issue by lawrencekiba** [traveller59/spconv#37]
running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/anaconda3/envs/pointpillars/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/Desktop/second.pytorch/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- The CUDA compiler identification is unknown
-- Check for working CUDA compiler: /usr/bin/nvcc
-- Check for working CUDA compiler: /usr/bin/nvcc -- broken
CMake Error at /usr/local/share/cmake-3.14/Modules/CMakeTestCUDACompiler.cmake:46 (message):
  The CUDA compiler

    "/usr/bin/nvcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/Desktop/second.pytorch/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make cmTC_2019f/fast 
    /usr/bin/make -f CMakeFiles/cmTC_2019f.dir/build.make CMakeFiles/cmTC_2019f.dir/build
    make[1]: Entering directory '/home/Desktop/second.pytorch/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeTmp'
    Building CUDA object CMakeFiles/cmTC_2019f.dir/main.cu.o
    /usr/bin/nvcc    "--expt-relaxed-constexpr"    -x cu -c /home/Desktop/second.pytorch/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_2019f.dir/main.cu.o
    ptxas fatal   : Value 'sm_20' is not defined for option 'gpu-name'
    CMakeFiles/cmTC_2019f.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_2019f.dir/main.cu.o' failed
    make[1]: *** [CMakeFiles/cmTC_2019f.dir/main.cu.o] Error 255
    make[1]: Leaving directory '/home/Desktop/second.pytorch/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeTmp'
    Makefile:121: recipe for target 'cmTC_2019f/fast' failed
    make: *** [cmTC_2019f/fast] Error 2
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

-- Configuring incomplete, errors occurred!
See also "/home/Desktop/second.pytorch/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
See also "/home/Desktop/second.pytorch/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 89, in <module>
    zip_safe=False,
  File "/home/anaconda3/envs/pointpillars/lib/python3.7/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/home/anaconda3/envs/pointpillars/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/anaconda3/envs/pointpillars/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/anaconda3/envs/pointpillars/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/anaconda3/envs/pointpillars/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 188, in run
    self.run_command('build')
  File "/home/anaconda3/envs/pointpillars/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/anaconda3/envs/pointpillars/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/anaconda3/envs/pointpillars/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/anaconda3/envs/pointpillars/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/anaconda3/envs/pointpillars/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 40, in run
    self.build_extension(ext)
  File "setup.py", line 72, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/anaconda3/envs/pointpillars/lib/python3.7/subprocess.py", line 341, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/Desktop/second.pytorch/spconv', '-DCMAKE_PREFIX_PATH=/home/anaconda3/envs/pointpillars/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/Desktop/second.pytorch/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

**Comment by zarev** [comment]
Make sure you have installed the cuda toolkit

**Comment by lawrencekiba** [comment]
I have CUDA 10 installed., 

> Make sure you have installed the cuda toolkit

**Comment by ZwwWayne** [comment]
Actually I meet the same problem as you do, and I can use CUDA-9.0 to run the samples.

**Comment by binlidaily** [comment]
Same problem, is there any suggestion?
