### ISSUE TITLE
ValueError: your out spatial shape [22, 15, 0] reach zero!!! input shape: [22, 15, 0]

### ISSUE THREAD

**Issue by MissShihongHowRU** [traveller59/spconv#370]
Hi, thanks for your great work! 

My code runs with no problem in spconv2.0.2, but after upgrading to spconv2.1, I encounter the following error:

Traceback (most recent call last):
  File "train.py", line 195, in <module>
    main()
  File "train.py", line 191, in main
    raise e
  File "train.py", line 188, in main
    MyTrainer.run(distributed=distributed, timestamp=timestamp, meta=meta, **vars(args))
  File "/boostai/boost/main/trainer/base_trainer.py", line 104, in run
    raise e
  File "/boostai/boost/main/trainer/base_trainer.py", line 98, in run
    self.train(**kwargs)
  File "/boostai/boost/main/trainer/semantic3d_trainer.py", line 42, in train
    meta=kwargs['meta'],
  File "/mmdetection3d/mmdet3d/apis/train.py", line 35, in train_model
    meta=meta)
  File "/opt/conda/lib/python3.7/site-packages/mmdet/apis/train.py", line 174, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 238, in train_step
    losses = self(**data)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/mmdetection3d/mmdet3d/models/detectors/base.py", line 59, in forward
    return self.forward_train(**kwargs)
  File "/boostai/models/semantic_segmentation_3d/CyAs_net.py", line 74, in forward_train
    outputs = self.init_outputs(inputs)
  File "/boostai/models/semantic_segmentation_3d/CyAs_net.py", line 60, in init_outputs
    outputs = self.extract_feat(pt_fea_ten, vox_ten)
  File "/boostai/models/semantic_segmentation_3d/CyAs_net.py", line 40, in extract_feat
    spatial_features = self.spconv_segmentor(features_3d, coords, self.batch_size)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/boostai/models/semantic_segmentation_3d/asymm_spconv_backbone.py", line 340, in forward
    up1e = self.upBlock3(up2e, down1b)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/boostai/models/semantic_segmentation_3d/asymm_spconv_backbone.py", line 211, in forward
    upE = self.conv1(upA)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/spconv/pytorch/conv.py", line 364, in forward
    alloc=input.thrust_allocator)
  File "/opt/conda/lib/python3.7/site-packages/spconv/pytorch/ops.py", line 291, in get_indice_pairs_implicit_gemm
    f"your out spatial shape {out_shape} reach zero!!! input shape: {spatial_shape}"
ValueError: your out spatial shape [22, 15, 0] reach zero!!! input shape: [22, 15, 0]

**Comment by FindDefinition** [comment]
this means one of your dim reach zero during downsample, your network shouldn't work in spconv 2.0. you need to check your downsample layers.

**Comment by MissShihongHowRU** [comment]
Hi, @FindDefinition. Thank you for your quick response. 

I've printed the spatial_shape of each layer's tensor, and found that after a spconv.SparseInverseConv3d() layer with kernel_size=3, the spatial_shape decrease by 2 for each dimension.

I used the following block:

========================================================================================

class UpBlock(nn.Module):

      def __init__(self, in_filters, out_filters, kernel_size=(3, 3, 3), indice_key=None, up_key=None, num_groups=32):
          super(UpBlock, self).__init__()
          self.trans_dilao = conv3x3(in_filters, out_filters, indice_key=indice_key + "new_up")
          self.trans_act = nn.LeakyReLU()
          self.trans_bn = nn.BatchNorm1d(out_filters)
  
          self.conv1 = conv1x3(out_filters, out_filters, indice_key=indice_key)   # + "_1by3")
          self.act1 = nn.LeakyReLU()
          self.bn1 = nn.BatchNorm1d(out_filters)
  
          self.conv2 = conv3x1(out_filters, out_filters, indice_key=indice_key + "_3by1")
          self.act2 = nn.LeakyReLU()
          self.bn2 = nn.BatchNorm1d(out_filters)
  
          self.conv3 = conv3x3(out_filters, out_filters, indice_key=indice_key + "_3by3")
          self.act3 = nn.LeakyReLU()
          self.bn3 = nn.BatchNorm1d(out_filters)
          #self.gn3 = nn.GroupNorm(num_groups, out_filters)
  
          self.up_subm = spconv.SparseInverseConv3d(out_filters, out_filters, kernel_size=3, indice_key=up_key,
                                                    bias=False)
  
          self.weight_initialization()
  
      def weight_initialization(self):
          for m in self.modules():
              if isinstance(m, nn.BatchNorm1d):
                  nn.init.constant_(m.weight, 1)
                  nn.init.constant_(m.bias, 0)
  
      def forward(self, x, skip):
          upA = self.trans_dilao(x)
          upA = upA.replace_feature(self.trans_act(upA.features))
          upA = upA.replace_feature(self.trans_bn(upA.features))
          print("After trans_dilao:", upA.spatial_shape)
  
          ## upsample
          upA = self.up_subm(upA)
          print("After up_subm:", upA.spatial_shape)
  
          upA = upA.replace_feature(upA.features + skip.features)
          print("After add:", upA.spatial_shape)
  
          upE = self.conv1(upA)
          upE = upE.replace_feature(self.act1(upE.features))
          upE = upE.replace_feature(self.bn1(upE.features))
          print("After conv1:", upE.spatial_shape)
  
          upE = self.conv2(upE)
          upE = upE.replace_feature(self.act2(upE.features))
          upE = upE.replace_feature(self.bn2(upE.features))
          print("After conv2:", upE.spatial_shape)
  
          upE = self.conv3(upE)
          upE = upE.replace_feature(self.act3(upE.features))
          upE = upE.replace_feature(self.bn3(upE.features))
          print("After conv3:", upE.spatial_shape)
  
          return upE

========================================================================================

And got the following output:

After trans_dilao: [25, 20, 8]
After up_subm: [23, 18, 6]
After add: [23, 18, 6]
After conv1: [23, 18, 6]
After conv2: [23, 18, 6]
After conv3: [23, 18, 6]

After trans_dilao: [23, 18, 6]
After up_subm: [21, 16, 4]
After add: [21, 16, 4]
After conv1: [21, 16, 4]
After conv2: [21, 16, 4]
After conv3: [21, 16, 4]

After trans_dilao: [21, 16, 4]
After up_subm: [19, 14, 2]
After add: [19, 14, 2]
After conv1: [19, 14, 2]
After conv2: [19, 14, 2]
After conv3: [19, 14, 2]

After trans_dilao: [19, 14, 2]
After up_subm: [17, 12, 0]
After add: [17, 12, 0]
Traceback (most recent call last):
...


The code runs with no error in spconv2.0.2;  Does the spconv.SparseInverseConv3d() changed it's behavior since 2.1?  Can I explicitly specify padding=1?

**Comment by FindDefinition** [comment]
This is a serious bug and will be fixed as quickly as possible, please wait for new prebuilts ready (need 2-3 hours)

**Comment by MissShihongHowRU** [comment]
Thank you so much.

**Comment by FuzhiYang** [comment]
@FindDefinition  Have you solved this bug? I tried spconv-cu111 today and I've met the same error today

**Comment by FindDefinition** [comment]
@FuzhiYang this should be fixed in spconv >=2.1.4. if still exists, you need to check your downsample layers first.

**Comment by FuzhiYang** [comment]
> @FuzhiYang this should be fixed in spconv >=2.1.4. if still exists, you need to check your downsample layers first.

Thank you very much. I installed spconv==2.1.6 and this bug is fixed.
