### ISSUE TITLE
Some bugs with the newest prebuilt spconv

### ISSUE THREAD

**Issue by ShengqiWang** [traveller59/spconv#385]
Hello, I discover some bugs with the newest prebuilt spconv on windows and linux.

1. 
Environment:
cuda11.3, windows, pytorch 1.10.0
When I run the code:

```
from torch import nn
import torch
import spconv.pytorch as spconv

if __name__=='__main__':
    device = torch.device('cuda:0')

    net = spconv.SparseConv2d(8, 16, 2, 2, 0)
    net.to(device)
    dense = spconv.ToDense()
    dense.to(device)

    features = torch.ones(1, 8).to(device)
    coors = 2*torch.ones(1, 3).to(device).int()
    x = spconv.SparseConvTensor(features, coors, (4, 4), 10)
    y = net(x)
    y = dense(y)
    print(y.shape)
```
The outcome is expected to be torch.Size([10, 16, 2, 2]), but the outcome outputs torch.Size([10, 16, 4, 4]). This bug only appear when kernel size=1.

2.
When I run the code 
```
from torch import nn
import torch
import spconv.pytorch as spconv
if __name__=='__main__':
    device = torch.device('cuda:0')

    net = spconv.SparseSequential(spconv.SparseConv2d(8, 16, 2, 2, 0),
                        nn.BatchNorm1d(16),
                        nn.ReLU())
    net.to(device)
    dense = spconv.ToDense()
    dense.to(device)

    features = torch.ones(1, 8).to(device)
    coors = 2*torch.ones(1, 3).to(device).int()
    x = spconv.SparseConvTensor(features, coors, (4, 4), 10)
    y = net(x)
    y = dense(y)
    print(y.shape)
```
It reports an error
```
Traceback (most recent call last):
  File "C:\Users\haoru\Documents\repo\traj\debug3.py", line 17, in <module>
    y = net(x)
  File "C:\Users\haoru\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\haoru\AppData\Local\Programs\Python\Python39\lib\site-packages\spconv\pytorch\modules.py", line 141, in forward
    input = input.replace_feature(module(input.features))
  File "C:\Users\haoru\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\haoru\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\batchnorm.py", line 168, in forward
    return F.batch_norm(
  File "C:\Users\haoru\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\functional.py", line 2280, in batch_norm
    _verify_batch_size(input.size())
  File "C:\Users\haoru\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\functional.py", line 2248, in _verify_batch_size
    raise ValueError("Expected more than 1 value per channel when training, got input size {}".format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 16])

Process finished with exit code 1
```
But when I change the stride to 1 in `spconv.SparseConv2d(8, 16, 2, 1, 0)`, there is no error.

The two bugs can be recurrented on different computers with different OS. (Linux and windows)  Please tell me whether the code itself is wrong or it's a bug for spconv.

**Comment by FindDefinition** [comment]
1. this case is due to we only use prod of kernel size to determine whether the layer is 1x1 conv, we should add stride too. see [this](https://github.com/traveller59/spconv/blob/master/spconv/pytorch/conv.py#L237). since this problem is a rare corner case, it won't be fixed immediately, will be fixed in next major update or next bug fix release.
2. this isn't our problem, that error means batchnorm requires your batch size > 1 to calculate running var during training.
