### ISSUE TITLE
gcc: fatal error: cannot execute ‘cc1plus’ when building wheel from source

### ISSUE THREAD

**Issue by jonasmeyer1** [traveller59/spconv#388]
I try to build a wheel from source on a Jetson TX2 with the following specifications:

Ubuntu 18.04
CUDA 10.2
cuDNN 8.0.0

I installed pythorch 1.6.0  and cumm 0.2.4 before, by building a wheel from source.

I ran ```export CUMM_CUDA_VERSION="10.2" ``` and ``` export SPCONV_DISABLE_JIT="1"``` before running ```python3 setup.py bdist_wheel```

I got a ```gcc: fatal error: cannot execute ‘cc1plus’: execvp: No such file ordirectory compilation terminated.'``` error (see below).

```
[21/431] nvcc -MMD -MT objects/GemmKernel_gemm_kernel.cu.o -MF objects/GemmKernel_gemm_kernel.cu.o.d -I "/media/7c1b8284-04e8-4feb-9dce-c3ceeda85c2e/MTH_meyj/Software/spconv_2.1.11/build/temp.linux-aarch64-3.6/spconv/build/include" -I "/usr/local/cuda-10.2/targets/aarch64-linux/include" -I "/home/nvidia/.local/lib/python3.6/site-packages/cumm/include" -I "/home/nvidia/.local/lib/python3.6/site-packages/pybind11/include" -I "/usr/include/python3.6m" -I "/usr/include/python3.6m" -gencode=arch=compute_62,code=sm_62 -Xcudafe "--diag_suppress=implicit_return_from_non_void_function" -Xcompiler -fno-gnu-unique -std=c++14 -O3 -DTV_CUDA -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -Xcompiler="-fPIC" -Xcompiler='-O3' -c /media/7c1b8284-04e8-4feb-9dce-c3ceeda85c2e/MTH_meyj/Software/spconv_2.1.11/build/temp.linux-aarch64-3.6/spconv/build/src/cumm/gemm/main/SimtDP4A_s8s8s32s32s32ttt_m64n128k32m32n64k32_2_SAC00/GemmKernel/GemmKernel_gemm_kernel.cu -o objects/GemmKernel_gemm_kernel.cu.o 
FAILED: objects/GemmKernel_gemm_kernel.cu.o 
nvcc -MMD -MT objects/GemmKernel_gemm_kernel.cu.o -MF objects/GemmKernel_gemm_kernel.cu.o.d -I "/media/7c1b8284-04e8-4feb-9dce-c3ceeda85c2e/MTH_meyj/Software/spconv_2.1.11/build/temp.linux-aarch64-3.6/spconv/build/include" -I "/usr/local/cuda-10.2/targets/aarch64-linux/include" -I "/home/nvidia/.local/lib/python3.6/site-packages/cumm/include" -I "/home/nvidia/.local/lib/python3.6/site-packages/pybind11/include" -I "/usr/include/python3.6m" -I "/usr/include/python3.6m" -gencode=arch=compute_62,code=sm_62 -Xcudafe "--diag_suppress=implicit_return_from_non_void_function" -Xcompiler -fno-gnu-unique -std=c++14 -O3 -DTV_CUDA -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -Xcompiler="-fPIC" -Xcompiler='-O3' -c /media/7c1b8284-04e8-4feb-9dce-c3ceeda85c2e/MTH_meyj/Software/spconv_2.1.11/build/temp.linux-aarch64-3.6/spconv/build/src/cumm/gemm/main/SimtDP4A_s8s8s32s32s32ttt_m64n128k32m32n64k32_2_SAC00/GemmKernel/GemmKernel_gemm_kernel.cu -o objects/GemmKernel_gemm_kernel.cu.o 
gcc: fatal error: cannot execute ‘cc1plus’: execvp: No such file or directory
compilation terminated.
[22/431] g++ -MMD -MT objects/GemmParams_a_set.cc.o -MF objects/GemmParams_a_set.cc.o.d -I "/media/7c1b8284-04e8-4feb-9dce-c3ceeda85c2e/MTH_meyj/Software/spconv_2.1.11/build/temp.linux-aarch64-3.6/spconv/build/include" -I "/usr/local/cuda-10.2/targets/aarch64-linux/include" -I "/home/nvidia/.local/lib/python3.6/site-packages/cumm/include" -I "/home/nvidia/.local/lib/python3.6/site-packages/pybind11/include" -I "/usr/include/python3.6m" -I "/usr/include/python3.6m" -DTV_CUDA -std=c++14 -O3 -fPIC -c /media/7c1b8284-04e8-4feb-9dce-c3ceeda85c2e/MTH_meyj/Software/spconv_2.1.11/build/temp.linux-aarch64-3.6/spconv/build/src/cumm/gemm/main/GemmParams/GemmParams_a_set.cc -o objects/GemmParams_a_set.cc.o 
[23/431] g++ -MMD -MT objects/GemmParams_b_get.cc.o -MF objects/GemmParams_b_get.cc.o.d -I "/media/7c1b8284-04e8-4feb-9dce-c3ceeda85c2e/MTH_meyj/Software/spconv_2.1.11/build/temp.linux-aarch64-3.6/spconv/build/include" -I "/usr/local/cuda-10.2/targets/aarch64-linux/include" -I "/home/nvidia/.local/lib/python3.6/site-packages/cumm/include" -I "/home/nvidia/.local/lib/python3.6/site-packages/pybind11/include" -I "/usr/include/python3.6m" -I "/usr/include/python3.6m" -DTV_CUDA -std=c++14 -O3 -fPIC -c /media/7c1b8284-04e8-4feb-9dce-c3ceeda85c2e/MTH_meyj/Software/spconv_2.1.11/build/temp.linux-aarch64-3.6/spconv/build/src/cumm/gemm/main/GemmParams/GemmParams_b_get.cc -o objects/GemmParams_b_get.cc.o 
[24/431] g++ -MMD -MT objects/GemmParams_a_get.cc.o -MF objects/GemmParams_a_get.cc.o.d -I "/media/7c1b8284-04e8-4feb-9dce-c3ceeda85c2e/MTH_meyj/Software/spconv_2.1.11/build/temp.linux-aarch64-3.6/spconv/build/include" -I "/usr/local/cuda-10.2/targets/aarch64-linux/include" -I "/home/nvidia/.local/lib/python3.6/site-packages/cumm/include" -I "/home/nvidia/.local/lib/python3.6/site-packages/pybind11/include" -I "/usr/include/python3.6m" -I "/usr/include/python3.6m" -DTV_CUDA -std=c++14 -O3 -fPIC -c /media/7c1b8284-04e8-4feb-9dce-c3ceeda85c2e/MTH_meyj/Software/spconv_2.1.11/build/temp.linux-aarch64-3.6/spconv/build/src/cumm/gemm/main/GemmParams/GemmParams_a_get.cc -o objects/GemmParams_a_get.cc.o 
[25/431] g++ -MMD -MT objects/GemmParams_c_get.cc.o -MF objects/GemmParams_c_get.cc.o.d -I "/media/7c1b8284-04e8-4feb-9dce-c3ceeda85c2e/MTH_meyj/Software/spconv_2.1.11/build/temp.linux-aarch64-3.6/spconv/build/include" -I "/usr/local/cuda-10.2/targets/aarch64-linux/include" -I "/home/nvidia/.local/lib/python3.6/site-packages/cumm/include" -I "/home/nvidia/.local/lib/python3.6/site-packages/pybind11/include" -I "/usr/include/python3.6m" -I "/usr/include/python3.6m" -DTV_CUDA -std=c++14 -O3 -fPIC -c /media/7c1b8284-04e8-4feb-9dce-c3ceeda85c2e/MTH_meyj/Software/spconv_2.1.11/build/temp.linux-aarch64-3.6/spconv/build/src/cumm/gemm/main/GemmParams/GemmParams_c_get.cc -o objects/GemmParams_c_get.cc.o 
[26/431] g++ -MMD -MT objects/GemmParams_c_set.cc.o -MF objects/GemmParams_c_set.cc.o.d -I "/media/7c1b8284-04e8-4feb-9dce-c3ceeda85c2e/MTH_meyj/Software/spconv_2.1.11/build/temp.linux-aarch64-3.6/spconv/build/include" -I "/usr/local/cuda-10.2/targets/aarch64-linux/include" -I "/home/nvidia/.local/lib/python3.6/site-packages/cumm/include" -I "/home/nvidia/.local/lib/python3.6/site-packages/pybind11/include" -I "/usr/include/python3.6m" -I "/usr/include/python3.6m" -DTV_CUDA -std=c++14 -O3 -fPIC -c /media/7c1b8284-04e8-4feb-9dce-c3ceeda85c2e/MTH_meyj/Software/spconv_2.1.11/build/temp.linux-aarch64-3.6/spconv/build/src/cumm/gemm/main/GemmParams/GemmParams_c_set.cc -o objects/GemmParams_c_set.cc.o 
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 220, in <module>
    ext_modules=ext_modules,
  File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 204, in run
    self.run_command('build')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/nvidia/.local/lib/python3.6/site-packages/pccm/extension.py", line 59, in run
    self.build_extension(ext)
  File "/home/nvidia/.local/lib/python3.6/site-packages/pccm/extension.py", line 90, in build_extension
    debug_file_gen=ext.debug_file_gen)
  File "/home/nvidia/.local/lib/python3.6/site-packages/pccm/builder/pybind.py", line 141, in build_pybind
    objects_folder=objects_folder)
  File "/home/nvidia/.local/lib/python3.6/site-packages/ccimport/core.py", line 178, in ccimport
    objects_folder=objects_folder)
  File "/home/nvidia/.local/lib/python3.6/site-packages/ccimport/buildtools/writer.py", line 960, in build_simple_ninja
    raise subprocess.CalledProcessError(proc.returncode, cmds)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.


```

**Comment by jonasmeyer1** [comment]
I solved it by installing g++ 8

**Comment by SmBito** [comment]
@jonasmeyer1 I have the same problem and can not solve it. Could you please upload the wheel file (.whl)?  Thanks
