### ISSUE TITLE
I get RuntimeError when I use 3d convolution (Sparse or SubM)

### ISSUE THREAD

**Issue by pelegn1** [traveller59/spconv#398]
Environment:
GPU RTX2080TI
Cuda driver: 465.31
spconv-cu111: 2.1.16 
torch: 1.9.1

When using spconv1 everything works fine (also when using `ConvAlgo.Native`), but when using `ConvAlgo.MaskImplicitGemm` (default algo) I get a runtime error thrown from `SpconvOps.sort_1d_by_key_allocator`

Am getting the error when doing forward of `SubMConv3d`, managed to narrow it down to the following function (with args to reproduce):

get_indice_pairs_implicit_gemm(x.indices[:2], batch_size=x.batch_size, spatial_shape=x.spatial_shape, algo=ConvAlgo.MaskSplitImplicitGemm, ksize=(1, 1, 1), stride=(1,1,1), padding=(0,1,1), dilation=(0,0,0), out_padding=(0,0,0), subm=True, transpose=False, is_train=False, alloc=x.thrust_allocator, timer=x._timer)

x.indices[:2]=tensor([[ 0,  9, 54, 19],
        [ 0,  9, 55, 19]], device='cuda:0', dtype=torch.int32) 
x.batch_size=1, 
x.spatial_shape=[480 360  32], 
x.thrust_allocator=None, 
x._timer=<spconv.tools.CUDAKernelTimer object at 0x7f6de080c220>)

**Comment by FindDefinition** [comment]
Could you provide the full traceback log, especially [here](https://github.com/traveller59/spconv/blob/v2.1.16/spconv/pytorch/conv.py#L403)? I can't reproduce your bug with your code.

**Comment by pelegn1** [comment]
here is the error that is printed:

[Exception|implicit_gemm_pair]indices=torch.Size([43788, 4]),bs=1,ss=[480 360  32],algo=ConvAlgo.MaskImplicitGemm,ksize=(1, 3, 3),stride=[1, 1, 1],padding=(0, 1, 1),dilation=[1, 1, 1],subm=False,transpose=False

The error log that spconv saved:
[error.log](https://github.com/traveller59/spconv/files/7626675/error.log)


I didn't understand what I should do with 'here', is there something you still need?

**Comment by FindDefinition** [comment]
I need the "traceback" like this:
```
Traceback (most recent call last):
  File "/home/yy/Projects/spconv-release/spconv/test/benchmark.py", line 362, in <module>
    main()
  File "/home/yy/Projects/spconv-release/spconv/test/benchmark.py", line 318, in main
    out = net(voxels_th, coors_th, 1)
  File "/home/yy/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yy/Projects/spconv-release/spconv/test/benchmark.py", line 190, in forward
    return self.net(x)
  File "/home/yy/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yy/Projects/spconv-release/spconv/spconv/pytorch/modules.py", line 137, in forward
    input = module(input)
  File "/home/yy/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yy/Projects/spconv-release/spconv/spconv/pytorch/conv.py", line 416, in forward
    raise e 
  File "/home/yy/Projects/spconv-release/spconv/spconv/pytorch/conv.py", line 393, in forward
    res = ops.get_indice_pairs_implicit_gemm(
  File "/home/yy/Projects/spconv-release/spconv/spconv/pytorch/ops.py", line 279, in get_indice_pairs_implicit_gemm
    raise NotImplementedError
NotImplementedError
```
I need to know the exception type.
by the way, I still can't reproduce your bug with your indice data.

**Comment by pelegn1** [comment]
^ this works for me as well :|

But the full program still fails. the full traceback is:

Traceback (most recent call last):
  File "/opt/project/train_cylinder_asym_spconv2.py", line 322, in <module>
    main(args)
  File "/opt/project/train_cylinder_asym_spconv2.py", line 133, in main
    train(load_iter, last_logged_iter, logger, eval_save_dir, loss_func, lovasz_softmax, ignore_label, model_save_dir, my_model, optimizer, pytorch_device, train_batch_size, train_dataset_loader, train_hypers)
  File "/opt/project/train_cylinder_asym_spconv2.py", line 168, in train
    semantic_seg_probs, instance_seg_offsets = my_model(train_pt_fea_ten, train_vox_ten, train_batch_size, cart_xyz_ten)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1080, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/project/network/cylinder_spconv_3d.py", line 44, in forward
    spatial_features = self.cylinder_3d_spconv_seg(features_3d, coords, batch_size, train_vox_ten, cart_xyz)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1080, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/project/network/segmentator_3d_asymm_spconv.py", line 304, in forward
    ret = self.downCntx(ret)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1080, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/project/network/segmentator_3d_asymm_spconv.py", line 83, in forward
    shortcut = self.conv1(x)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1080, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 410, in forward
    raise e 
  File "/opt/conda/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 387, in forward
    res = ops.get_indice_pairs_implicit_gemm(
  File "/opt/conda/lib/python3.8/site-packages/spconv/pytorch/ops.py", line 357, in get_indice_pairs_implicit_gemm
    SpconvOps.sort_1d_by_key_allocator(pair_mask_tv[j],
RuntimeError

**Comment by FindDefinition** [comment]
so this exception doesn't contain any other information? That's strange, you can try to reproduce this in a minimal script first, I need to recheck code and findout where is that runtime error

**Comment by FindDefinition** [comment]
A note: cylinder 3d currently have ill-formed conv and isn't compatible with spconv 2.x yet, have you fixed them in cylinder3d?

**Comment by pelegn1** [comment]
what does it mean that a conv is ill-formed? I did not know about it, can you please explain a bit about what's wrong and how to solve it / refer me to an explanation?

**Comment by FindDefinition** [comment]
see [this issue](https://github.com/xinge008/Cylinder3D/issues/102). I'm not sure if this problem cause your bug, you can remove all non-3x3x3 convs in Cylinder3d.

**Comment by pelegn1** [comment]
thanks for the fast response.

I removed all indice_key s from my layers but nothing seemed to change


```
for key, val in self._modules.items():
    if 'conv' in key:
        print(key, [val.indice_key])
        
conv1 [None]
conv1_2 [None]
conv2 [None]
conv3 [None]

```

```
self.conv1(x)
[Exception|implicit_gemm_pair]indices=torch.Size([44595, 4]),bs=1,ss=[480 360  32],algo=ConvAlgo.MaskImplicitGemm,ksize=(1, 3, 3),stride=[1, 1, 1],padding=(0, 1, 1),dilation=[1, 1, 1],subm=True,transpose=False
spconv save debug data to /homes/pelegn/tmp/cylinder3d/error.log, you can submit issue with log and this debug data attached.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-37bdbeeb21fa>", line 1, in <module>
    self.conv1(x)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1080, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 410, in forward
    raise e
  File "/opt/conda/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 387, in forward
    res = ops.get_indice_pairs_implicit_gemm(
  File "/opt/conda/lib/python3.8/site-packages/spconv/pytorch/ops.py", line 357, in get_indice_pairs_implicit_gemm
    SpconvOps.sort_1d_by_key_allocator(pair_mask_tv[j],
RuntimeError
```

**Comment by FindDefinition** [comment]
your network looks simple, could you write a minimal reproduce script that contains a simple network, pickle your input data and upload here?

**Comment by pelegn1** [comment]
I have very exciting news - importing spconv first thing in the program solved my problems :)

I tried to reproduce my error in a minimal environment and it didn't fail, so i started to figure out what is the difference between the two situations and ended up with this conclusion

**Comment by FindDefinition** [comment]
could you share your python version? I need to investigate this strange problem.

**Comment by pelegn1** [comment]
I'm using python 3.8.10
