### ISSUE TITLE
About the mixed precision training support for Pascal arch GPU

### ISSUE THREAD

**Issue by jihanyang** [traveller59/spconv#403]
Hello,

I follow the guidance in the mixed precision training in example/mnist_sparse.py and successfully run an mixed training code with spconv 2.1.19 on my 2080ti and V100 . Nevertheless, when I try it on 1080ti, it returns the following erros:
```
Traceback (most recent call last):                                                                                                                                                                          
  File "train.py", line 204, in <module>                                                                                                                                                                    
    main()                                                                                                                                                                                                  
  File "train.py", line 155, in main                                                                                                                                                                        
    train_model(                                                                                                                                                                                            
  File "/mnt/lustre/yangjihan/pcdet-jh/tools/train_utils/train_utils.py", line 107, in train_model                                                                                                          
    accumulated_iter = train_one_epoch(                                                                                                                                                                     
  File "/mnt/lustre/yangjihan/pcdet-jh/tools/train_utils/train_utils.py", line 51, in train_one_epoch                                                                                                       
    loss, tb_dict, disp_dict = model_func(model, batch)                                                                                                                                                     
  File "../pcdet/models/__init__.py", line 42, in model_func                                                                                                                                                
    ret_dict, tb_dict, disp_dict = model(batch_dict)                                                                                                                                                        
  File "/mnt/lustre/yangjihan/anaconda3/envs/sspt19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl                                                                       
    return forward_call(*input, **kwargs)                                                                                                                                                                   
  File "/mnt/lustre/yangjihan/anaconda3/envs/sspt19/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 886, in forward                                                                     
    output = self.module(*inputs[0], **kwargs[0])                                                                                                                                                           
  File "/mnt/lustre/yangjihan/anaconda3/envs/sspt19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl                                                                       
    return forward_call(*input, **kwargs)                                                                                                                                                                   
  File "../pcdet/models/detectors/centerpoint.py", line 11, in forward                                                                                                                                      
    batch_dict = cur_module(batch_dict)                                                                                                                                                                     
  File "/mnt/lustre/yangjihan/anaconda3/envs/sspt19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl                                                                       
    return forward_call(*input, **kwargs)                                                                                                                                                                   
  File "../pcdet/models/backbones_3d/spconv_backbone.py", line 260, in forward                                                                                                                              
    x = self.conv_input(input_sp_tensor)                                                                                                                                                                    
  File "/mnt/lustre/yangjihan/anaconda3/envs/sspt19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl                                                                       
    return forward_call(*input, **kwargs)                                                                                                                                                                   
  File "/mnt/lustre/yangjihan/anaconda3/envs/sspt19/lib/python3.8/site-packages/spconv/pytorch/modules.py", line 137, in forward                                                                            
    input = module(input)                                                                                                                                                                                   
  File "/mnt/lustre/yangjihan/anaconda3/envs/sspt19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl                                                                       
    return forward_call(*input, **kwargs)                                                                                                                                                                   
  File "/mnt/lustre/yangjihan/anaconda3/envs/sspt19/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 430, in forward                                                                               
    out_features = Fsp.implicit_gemm(                                                                                                                                                                       
  File "/mnt/lustre/yangjihan/anaconda3/envs/sspt19/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 92, in decorate_fwd                                                                  
    return fwd(*_cast(args, cast_inputs), **_cast(kwargs, cast_inputs))                                                                                                                                     
  File "/mnt/lustre/yangjihan/anaconda3/envs/sspt19/lib/python3.8/site-packages/spconv/pytorch/functional.py", line 198, in forward                                                                         
    raise e                                                                                                                                                                                                 
  File "/mnt/lustre/yangjihan/anaconda3/envs/sspt19/lib/python3.8/site-packages/spconv/pytorch/functional.py", line 184, in forward                                                                         
    out, mask_out, mask_width = ops.implicit_gemm(features, filters,                                                                                                                                        
  File "/mnt/lustre/yangjihan/anaconda3/envs/sspt19/lib/python3.8/site-packages/spconv/pytorch/ops.py", line 1102, in implicit_gemm                                                                         
    tune_res, _ = CONV.tune_and_cache(
  File "/mnt/lustre/yangjihan/anaconda3/envs/sspt19/lib/python3.8/site-packages/spconv/algo.py", line 645, in tune_and_cache
    raise ValueError("can't find suitable algorithm for", op_type)
ValueError: ("can't find suitable algorithm for", <ConvOpType.kForward: 0>)
```
Could you please help me to find some possible reasons for the error?

Environments:
GPU: 1080ti (fail) or 2080ti (success) or V100 (success)
CUDA Version: 10.2
torch version: 1.19
python version: 3.8

**Comment by FindDefinition** [comment]
It's expected because I don't add backward kernels for GPU without Tensor Core (<=GTX 1000 series)
GTX 1000 series don't have hardware fp16/half support, so there is no significant speed improvement in GTX 1080Ti when use mixed precision training.

**Comment by jihanyang** [comment]
Thanks for your helpful feedback! However, it will sill be really helpful if you can support fp16 on GTX 1000 series just for reducing GPU memory consumption. Hope you can consider the supporting for GTX 1000 series for fp16. Thank you!

**Comment by FindDefinition** [comment]
fp16 kernels for pascal will be added in spconv 2.1.20. the only reason I don't want to add them is that more kernels leads to slower build in github actions. currently we need 3 hours to build.
The best solution is use nvrtc to compile kernels in runtime, but this need many changes, will be added in spconv 2.2.

**Comment by jihanyang** [comment]
Many thanks for your constructive work!
