### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by xljsh** [traveller59/spconv#405]
Traceback (most recent call last):
  File "second/pytorch/train.py", line 19, in <module>
    from second.builder import target_assigner_builder, voxel_builder
  File "/home/admin/ysh/CLOCs-master/second/builder/target_assigner_builder.py", line 3, in <module>
    from second.core.target_assigner import TargetAssigner
  File "/home/admin/ysh/CLOCs-master/second/core/target_assigner.py", line 1, in <module>
    from second.core import box_np_ops
  File "/home/admin/ysh/CLOCs-master/second/core/box_np_ops.py", line 5, in <module>
    from second.core.non_max_suppression.nms_gpu import rotate_iou_gpu_eval
  File "/home/admin/ysh/CLOCs-master/second/core/non_max_suppression/__init__.py", line 1, in <module>
    from second.core.non_max_suppression.nms_cpu import nms_jit, soft_nms_jit
  File "/home/admin/ysh/CLOCs-master/second/core/non_max_suppression/nms_cpu.py", line 7, in <module>
    from spconv.utils import (
  File "/home/admin/f211014/anaconda3/envs/CLOC/lib/python3.7/site-packages/spconv/utils/__init__.py",                              line 18, in <module>
    from spconv.cppconstants import CPU_ONLY_BUILD
  File "/home/admin/f211014/anaconda3/envs/CLOC/lib/python3.7/site-packages/spconv/cppconstants.py", l                             ine 15, in <module>
    import spconv.core_cc as _ext
ImportError: arg(): could not convert default argument 'timer: tv::CUDAKernelTimer' in method '<class                              'spconv.core_cc.cumm.gemm.main.GemmParams'>.__init__' into a Python object (type not registered yet?)

**Comment by FindDefinition** [comment]
you need to upgrade your cumm by  ```pip install -U cumm-cuxxx```

**Comment by SaMeEr9597** [comment]
> pip install -U cumm-cuxxx

I am getting the same error even after doing this, 

This is my cuda version and I used pip install -U cumm-cu111
<img width="539" alt="image" src="https://user-images.githubusercontent.com/96261162/158074486-7ace05cb-659d-4c78-8d2d-01f9ff9f9990.png">

**Comment by luyao2001** [comment]
I couldn't solve my problem by this way. Could you provide a new way?
