### ISSUE TITLE
Error when I import spconv

### ISSUE THREAD

**Issue by qiaozhijian** [traveller59/spconv#412]
[31/31] g++ /data0/cumm/cumm/build/src/tensorview_bind/TensorViewBind/TensorViewBind_hello.cc.o /data0/cumm/cumm/build/src/tensorview_bind/TensorViewBind/TensorViewBind_bind_tensorview.cc.o /data0/cumm/cumm/build/src/csrc/arrayref/ArrayPtr/ArrayPtr_ArrayPtr.cc.o /data0/cumm/cumm/build/src/csrc/arrayref/ArrayPtr/ArrayPtr___repr__.cc.o /data0/cumm/cumm/build/src/csrc/arrayref/ArrayPtr/ArrayPtr_clear.cc.o /data0/cumm/cumm/build/src/csrc/arrayref/ArrayPtr/ArrayPtr_shadow_copy.cc.o /data0/cumm/cumm/build/src/csrc/arrayref/ArrayPtr/ArrayPtr_copy.cc.o /data0/cumm/cumm/build/src/csrc/arrayref/ArrayPtr/ArrayPtr_get_length.cc.o /data0/cumm/cumm/build/src/csrc/arrayref/ArrayPtr/ArrayPtr_get_byte_length.cc.o /data0/cumm/cumm/build/src/csrc/arrayref/ArrayPtr/ArrayPtr_get_offset.cc.o /data0/cumm/cumm/build/src/csrc/arrayref/ArrayPtr/ArrayPtr_get_access_offset.cc.o /data0/cumm/cumm/build/src/csrc/arrayref/ArrayPtr/ArrayPtr_get_access_size.cc.o /data0/cumm/cumm/build/src/csrc/arrayref/ArrayPtr/ArrayPtr_get_num_access.cc.o /data0/cumm/cumm/build/src/csrc/arrayref/ArrayPtr/ArrayPtr___add__.cc.o /data0/cumm/cumm/build/src/csrc/arrayref/ArrayPtr/ArrayPtr___iadd__.cc.o /data0/cumm/cumm/build/src/csrc/arrayref/ArrayPtr/ArrayPtr___sub__.cc.o /data0/cumm/cumm/build/src/csrc/arrayref/ArrayPtr/ArrayPtr___isub__.cc.o /data0/cumm/cumm/build/src/csrc/arrayref/ArrayPtr/ArrayPtr_change_access_size.cc.o /data0/cumm/cumm/build/src/csrc/arrayref/ArrayPtr/ArrayPtr_change_access_byte_size.cc.o /data0/cumm/cumm/build/src/csrc/arrayref/ArrayPtr/ArrayPtr___getitem__.cc.o /data0/cumm/cumm/build/src/csrc/arrayref/ArrayPtr/ArrayPtr___setitem__.cc.o /data0/cumm/cumm/build/src/csrc/arrayref/ArrayPtr/ArrayPtr_get_data.cc.o /data0/cumm/cumm/build/src/csrc/arrayref/ArrayPtr/ArrayPtr_get_meta_data.cc.o /data0/cumm/cumm/build/src/csrc/arrayref/ArrayPtr/ArrayPtr_astype.cc.o /data0/cumm/cumm/build/src/csrc/arrayref/ArrayPtr/ArrayPtr_check_smem_bank_conflicit.cc.o /data0/cumm/cumm/build/src/tensorview_bind/PyBindTensorViewBind/PyBindTensorViewBind_bind_TensorViewBind.cc.o /data0/cumm/cumm/build/src/csrc/arrayref/PyBindArrayPtr/PyBindArrayPtr_bind_ArrayPtr.cc.o /data0/cumm/cumm/build/src/core_cc_pybind_main/core_cc_pybind_main.cc.o -lcudart -L "/usr/local/cuda-11.1/targets/x86_64-linux/lib" -shared -o /data0/cumm/cumm/build/core_cc.cpython-38-x86_64-linux-gnu.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data0/spconv/spconv/__init__.py", line 15, in <module>
    from . import build as _build
  File "/data0/spconv/spconv/build.py", line 38, in <module>
    pccm.builder.build_pybind([cu, convcu, SpconvOps()],
  File "/root/anaconda3/lib/python3.8/site-packages/pccm/builder/pybind.py", line 56, in build_pybind
    user_cus = cg.build_graph(cus, namespace_root)
  File "/root/anaconda3/lib/python3.8/site-packages/pccm/core/__init__.py", line 1790, in build_graph
    for decl in self.cached_extract_classunit_methods(cur_cu):
  File "/root/anaconda3/lib/python3.8/site-packages/pccm/core/__init__.py", line 1881, in cached_extract_classunit_methods
    self._get_decls_cache[key] = self.extract_classunit_methods(cu)
  File "/root/anaconda3/lib/python3.8/site-packages/pccm/core/__init__.py", line 1889, in extract_classunit_methods
    code_obj = getattr(cu, k)()  # type: FunctionCode
  File "/data0/cumm/cumm/gemm/output_op/linear.py", line 61, in ctor
    code.arg("alpha_", self.dtype_comp, f"{self.dtype_comp}(1)")
  File "/root/anaconda3/lib/python3.8/site-packages/pccm/core/__init__.py", line 671, in arg
    type = type.strip()
**AttributeError: 'DType' object has no attribute 'strip'**

**Comment by qiaozhijian** [comment]
My environment:
Python: 3.8.5
Pytorch: 1.10.0
CUDA: 11.1
Ubuntu18.04
pccm: 0.2.22
cumm: 0.2.8

I try "pip install -U cumm-cu111". But it didn't work.

**Comment by FindDefinition** [comment]
Do you install spconv from source? if not, remove all cumm/spconv first, then install spconv by ```pip install -U spconv-cu111``` again.
If you install from source, new version of PCCM (a dependency of spconv) cause this problem and will be fixed soon.

**Comment by qiaozhijian** [comment]
I install from source. Now I solve it. Thank you.
