### ISSUE TITLE
python setup.py bdist_wheel ERROR

### ISSUE THREAD

**Issue by TianhaoFu** [traveller59/spconv#414]
Hi, when I was installing spconv, I came across such error:
```
running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/opt/conda/lib/python3.6/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/root/11/centerpoint/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- Caffe2: CUDA detected: 10.2
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.2
-- Found cuDNN: v8.0.3  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s):  6.0 6.0
-- Added CUDA NVCC flags for: -gencode;arch=compute_60,code=sm_60
-- pybind11 v2.3.dev0
-- Configuring done
CMake Warning (dev) in src/spconv/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/spconv/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/utils/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv_nms".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/utils/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv_nms".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /root/11/centerpoint/spconv/build/temp.linux-x86_64-3.6
Consolidate compiler generated dependencies of target spconv_nms
Consolidate compiler generated dependencies of target spconv
[ 15%] Built target spconv_nms
[ 23%] Building CXX object src/spconv/CMakeFiles/spconv.dir/all.cc.o
[ 30%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/reordering.cu.o
[ 38%] Building CXX object src/spconv/CMakeFiles/spconv.dir/maxpool.cc.o
[ 46%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/maxpool.cu.o
/root/11/centerpoint/spconv/src/spconv/all.cc:20:91: error: no matching function for call to ‘torch::jit::RegisterOperators::RegisterOperators(const char [28], <unresolved overloaded function type>)’
     torch::jit::RegisterOperators("spconv::get_indice_pairs_2d", &spconv::getIndicePair<2>)
                                                                                           ^
In file included from /opt/conda/lib/python3.6/site-packages/torch/include/torch/script.h:6:0,
                 from /root/11/centerpoint/spconv/include/spconv/pool_ops.h:20,
                 from /root/11/centerpoint/spconv/src/spconv/all.cc:16:
/opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/jit/runtime/custom_operator.h:22:3: note: candidate: torch::jit::RegisterOperators::RegisterOperators(std::vector<c10::optional<torch::jit::Operator> >)
   RegisterOperators(std::vector<c10::optional<Operator>> operators) {
   ^
/opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/jit/runtime/custom_operator.h:22:3: note:   candidate expects 1 argument, 2 provided
/opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/jit/runtime/custom_operator.h:17:3: note: candidate: constexpr torch::jit::RegisterOperators::RegisterOperators()
   RegisterOperators() = default;
   ^
/opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/jit/runtime/custom_operator.h:17:3: note:   candidate expects 0 arguments, 2 provided
/opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/jit/runtime/custom_operator.h:16:18: note: candidate: constexpr torch::jit::RegisterOperators::RegisterOperators(const torch::jit::RegisterOperators&)
 struct TORCH_API RegisterOperators {
                  ^
/opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/jit/runtime/custom_operator.h:16:18: note:   candidate expects 1 argument, 2 provided
/opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/jit/runtime/custom_operator.h:16:18: note: candidate: constexpr torch::jit::RegisterOperators::RegisterOperators(torch::jit::RegisterOperators&&)
/opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/jit/runtime/custom_operator.h:16:18: note:   candidate expects 1 argument, 2 provided
gmake[2]: *** [src/spconv/CMakeFiles/spconv.dir/all.cc.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
[ 53%] Building CXX object src/utils/CMakeFiles/spconv_utils.dir/all.cc.o
gmake[1]: *** [src/spconv/CMakeFiles/spconv.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 61%] Linking CXX shared library ../../../lib.linux-x86_64-3.6/spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so
[ 61%] Built target spconv_utils
gmake: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 89, in <module>
    zip_safe=False,
  File "/opt/conda/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/opt/conda/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/conda/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/conda/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 290, in run
    self.run_command('build')
  File "/opt/conda/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/conda/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/opt/conda/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 40, in run
    self.build_extension(ext)
  File "setup.py", line 73, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/opt/conda/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
```
Could you give me some ideas on how to fix it?

**Comment by jayadeepk** [comment]
Try this change:
```diff
diff --git a/src/spconv/all.cc b/src/spconv/all.cc
index f5aa966..1af3c60 100644
--- a/src/spconv/all.cc
+++ b/src/spconv/all.cc
@@ -17,7 +17,7 @@
 #include <spconv/spconv_ops.h>
 
 static auto registry =
-    torch::jit::RegisterOperators("spconv::get_indice_pairs_2d", &spconv::getIndicePair<2>)
+    torch::RegisterOperators("spconv::get_indice_pairs_2d", &spconv::getIndicePair<2>)
         .op("spconv::get_indice_pairs_3d", &spconv::getIndicePair<3>)
         .op("spconv::get_indice_pairs_grid_2d", &spconv::getIndicePairPreGrid<2>)
         .op("spconv::get_indice_pairs_grid_3d", &spconv::getIndicePairPreGrid<3>)
```
