### ISSUE TITLE
Error: python setup.py bdist_wheel

### ISSUE THREAD

**Issue by setBin** [traveller59/spconv#422]
The some error occurs when I execute the command 
`python setup.py bdist_wheel`

running bdist_wheel
running build
running build_py
running build_ext
/home/ubuntu/de/dyco3d/lib/spconv/build/lib.linux-x86_64-3.7
Release
-- The CXX compiler identification is GNU 5.4.0
-- The CUDA compiler identification is unknown
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /home/ubuntu/Downloads/yes/envs/dyco3d/bin/c++
-- Check for working CXX compiler: /home/ubuntu/Downloads/yes/envs/dyco3d/bin/c++ - broken
CMake Error at /home/ubuntu/Downloads/yes/envs/dyco3d/lib/python3.7/site-packages/cmake/data/share/cmake-3.22/Modules/CMakeTestCXXCompiler.cmake:62 (message):
  The C++ compiler

    `/home/ubuntu/Downloads/yes/envs/dyco3d/bin/c++`

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/ubuntu/de/dyco3d/lib/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/make -f Makefile cmTC_0ead2/fast && /usr/bin/make  -f CMakeFiles/cmTC_0ead2.dir/build.make CMakeFiles/cmTC_0ead2.dir/build
    make[1]: Entering directory '/home/ubuntu/de/dyco3d/lib/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_0ead2.dir/testCXXCompiler.cxx.o
    /home/ubuntu/Downloads/yes/envs/dyco3d/bin/c++   -DVERSION_INFO=\"1.0\"  -o CMakeFiles/cmTC_0ead2.dir/testCXXCompiler.cxx.o -c /home/ubuntu/de/dyco3d/lib/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    Linking CXX executable cmTC_0ead2
    /home/ubuntu/Downloads/yes/envs/dyco3d/lib/python3.7/site-packages/cmake/data/bin/cmake -E cmake_link_script CMakeFiles/cmTC_0ead2.dir/link.txt --verbose=1
    /home/ubuntu/Downloads/yes/envs/dyco3d/bin/c++ -DVERSION_INFO=\"1.0\"  CMakeFiles/cmTC_0ead2.dir/testCXXCompiler.cxx.o -o cmTC_0ead2
    /usr/bin/ld: cannot find crt1.o: No such file or directory
    /usr/bin/ld: cannot find crti.o: No such file or directory
    collect2: error: ld returned 1 exit status
    CMakeFiles/cmTC_0ead2.dir/build.make:98: recipe for target 'cmTC_0ead2' failed
    make[1]: *** [cmTC_0ead2] Error 1
    make[1]: Leaving directory '/home/ubuntu/de/dyco3d/lib/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeTmp'
    Makefile:127: recipe for target 'cmTC_0ead2/fast' failed
    make: *** [cmTC_0ead2/fast] Error 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/de/dyco3d/lib/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntu/de/dyco3d/lib/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 88, in <module>
    zip_safe=False,
  File "/home/ubuntu/Downloads/yes/envs/dyco3d/lib/python3.7/site-packages/setuptools/__init__.py", line 155, in setup
    return distutils.core.setup(**attrs)
  File "/home/ubuntu/Downloads/yes/envs/dyco3d/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/home/ubuntu/Downloads/yes/envs/dyco3d/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/home/ubuntu/Downloads/yes/envs/dyco3d/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/home/ubuntu/Downloads/yes/envs/dyco3d/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/ubuntu/Downloads/yes/envs/dyco3d/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/home/ubuntu/Downloads/yes/envs/dyco3d/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/ubuntu/Downloads/yes/envs/dyco3d/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/ubuntu/Downloads/yes/envs/dyco3d/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/ubuntu/Downloads/yes/envs/dyco3d/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/ubuntu/Downloads/yes/envs/dyco3d/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "setup.py", line 41, in run
    self.build_extension(ext)
  File "setup.py", line 71, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/ubuntu/Downloads/yes/envs/dyco3d/lib/python3.7/subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/ubuntu/de/dyco3d/lib/spconv', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/ubuntu/de/dyco3d/lib/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_PREFIX_PATH=/home/ubuntu/Downloads/yes/envs/dyco3d/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

**Comment by CatOneTwo** [comment]
Hi, did you fix this problem?

**Comment by xxp912** [comment]
Hi, did you fix this problem? @setBin
