### ISSUE TITLE
[Exception|implicit_gemm_backward], SPCONV_DEBUG_SAVE_PATH not found,

### ISSUE THREAD

**Issue by emilyemliyM** [traveller59/spconv#426]
[Exception|implicit_gemm_backward]feat=torch.Size([1882, 64]),w=torch.Size([64, 3, 3, 3, 64]),pair=torch.Size([27, 1882]),issubm=True,do=torch.Size([1882, 64])
SPCONV_DEBUG_SAVE_PATH not found, you can specify SPCONV_DEBUG_SAVE_PATH as debug data save path to save debug data which can be attached in a issue.
Traceback (most recent call last):

**Comment by sci-study-storage** [comment]
same problem

**Comment by 3bobo** [comment]
Hi, I meet the same problem, it seems that it is because the conflict of `cumm` and `cumm-cu111`,  so I  uninstall the two version of cumm and the `spconv-cu111`, and install spconv again by `pip install spconv-cu111` and it works.

**Comment by sci-study-storage** [comment]
> Hi, I meet the same problem, it seems that it is because the conflict of `cumm` and `cumm-cu111`, so I uninstall the two version of cumm and the `spconv-cu111`, and install spconv again by `pip install spconv-cu111` and it works.

For my case, I don't have an extra cumm. I deleted and reinstalled the package, it didn't work. Thank you for sharing though.

**Comment by harry1576** [comment]
Same problem too...

**Comment by harry1576** [comment]
> [Exception|implicit_gemm_backward]feat=torch.Size([1882, 64]),w=torch.Size([64, 3, 3, 3, 64]),pair=torch.Size([27, 1882]),issubm=True,do=torch.Size([1882, 64]) SPCONV_DEBUG_SAVE_PATH not found, you can specify SPCONV_DEBUG_SAVE_PATH as debug data save path to save debug data which can be attached in a issue. Traceback (most recent call last):

Same problem too - did you manage to resolve it ?

**Comment by Atopis** [comment]
Same problem.
In the same environment, one dataset is OK, other dataset have this problem.

**Comment by NingSara** [comment]
same problem，sometimes it's work when I use smaller batch size

**Comment by NingSara** [comment]
> same problem，sometimes it's work when I use smaller batch size . but i think it's not so good to solve it

my exception when i use batch_size == 8
[Exception|implicit_gemm_backward]feat=torch.Size([531333, 4]),w=torch.Size([80, 1, 5, 5, 4]),pair=torch.Size([25, 531333]),issubm=True,do=torch.Size([531333, 80])
it works when i reduce batch size to 4.
while i reduce the channel 4 to channel 2, it works too

**Comment by shenshanf** [comment]
> Hi, I meet the same problem, it seems that it is because the conflict of `cumm` and `cumm-cu111`, so I uninstall the two version of cumm and the `spconv-cu111`, and install spconv again by `pip install spconv-cu111` and it works.

yes, I follow your suggestion, uninstalled cumm-cuxxx, then install cumm-cuxxx again, and solved this problem

**Comment by OuYaozhong** [comment]
Same Problem.

```
SPCONV_DEBUG_SAVE_PATH not found, you can specify SPCONV_DEBUG_SAVE_PATH as debug data save path to save debug data which can be attached in a issue.                                                                                                                                                                                                                       
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                                          
  File "/home/$USER/tmp/$PROJECT/tools/test.py", line 210, in <module>                                                                                                                                                                                                                                                                                                    
    main()                                                                                                                                                                                                                                                                                                                                                                  
  File "/home/$USER/tmp/$PROJECT/tools/test.py", line 206, in main                                                                                                                                                                                                                                                                                                        
    eval_single_ckpt(model, test_loader, args, eval_output_dir, logger, epoch_id, dist_test=dist_test)                                                                                                                                                                                                                                                                      
  File "/home/$USER/tmp/$PROJECT/tools/test.py", line 68, in eval_single_ckpt                                                                                                                                                                                                                                                                                             
    eval_utils.eval_one_epoch(                                                                                                                                                                                                                                                                                                                                              
  File "/home/$USER/tmp/$PROJECT/tools/eval_utils/eval_utils.py", line 65, in eval_one_epoch                                                                                                                                                                                                                                                                              
    pred_dicts, ret_dict = model(batch_dict)
                           ^^^^^^^^^^^^^^^^^
  File "/home/$USER/.conda/envs/$PROJECT/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/$USER/.conda/envs/$PROJECT/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/$USER/.conda/envs/$PROJECT/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/$USER/.conda/envs/$PROJECT/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/$USER/tmp/$PROJECT/tools/../$PROJECT/models/detectors/centerpoint.py", line 11, in forward
    batch_dict = cur_module(batch_dict)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/$USER/.conda/envs/$PROJECT/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/$USER/tmp/$PROJECT/tools/../$PROJECT/models/backbones_3d/spconv_backbone.py", line 265, in forward
    x_conv2 = self.conv2(x_conv1)
              ^^^^^^^^^^^^^^^^^^^
  File "/home/$USER/.conda/envs/$PROJECT/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/$USER/.conda/envs/$PROJECT/lib/python3.11/site-packages/spconv/pytorch/modules.py", line 138, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/home/$USER/.conda/envs/$PROJECT/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/$USER/.conda/envs/$PROJECT/lib/python3.11/site-packages/spconv/pytorch/modules.py", line 138, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/home/$USER/.conda/envs/$PROJECT/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/$USER/.conda/envs/$PROJECT/lib/python3.11/site-packages/spconv/pytorch/conv.py", line 755, in forward
    return self._conv_forward(self.training,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/$USER/.conda/envs/$PROJECT/lib/python3.11/site-packages/spconv/pytorch/conv.py", line 408, in _conv_forward
    raise e
  File "/home/$USER/.conda/envs/$PROJECT/lib/python3.11/site-packages/spconv/pytorch/conv.py", line 385, in _conv_forward
    res = ops.get_indice_pairs_implicit_gemm(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/$USER/.conda/envs/$PROJECT/lib/python3.11/site-packages/spconv/pytorch/ops.py", line 773, in get_indice_pairs_implicit_gemm
    SpconvOps.sort_1d_by_key_allocator(
RuntimeError: merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
eval:   7%|█████████                                                  | 26/377 [00:47<10:39,  1.82s/it, recall_0.3=(0, 3950) / 5043]
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3990441 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3990440) of binary: /home/$USER/.conda/envs/$PROJECT/bin/python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/$USER/.conda/envs/$PROJECT/lib/python3.11/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/home/$USER/.conda/envs/$PROJECT/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/$USER/.conda/envs/$PROJECT/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/$USER/.conda/envs/$PROJECT/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/$USER/.conda/envs/$PROJECT/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/$USER/.conda/envs/$PROJECT/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:                                                                                                                                                                                                                                                                                                          
============================================================                                                                                                                                                                                                                                                                                                                
test.py FAILED                                                                                                                                                                                                                                                                                                                                                              
------------------------------------------------------------                                                                                                                                                                                                                                                                                                                
Failures:                                                                                                                                                                                                                                                                                                                                                                   
  <NO_OTHER_FAILURES>                                                                                                                                                                                                                                                                                                                                                       
------------------------------------------------------------                                                                                                                                                                                                                                                                                                                
Root Cause (first observed failure):                                                                                                                                                                                                                                                                                                                                        
[0]:                                                                                                                                                                                                                                                                                                                                                                        
  time      : 2023-07-11_17:51:54                                                                                                                                                                                                                                                                                                                                           
  host      : AI-3090                                                                                                                                                                                                                                                                                                                                                       
  rank      : 0 (local_rank: 0)                                                                                                                                                                                                                                                                                                                                             
  exitcode  : 1 (pid: 3990440)                                                                                                                                                                                                                                                                                                                                              
  error_file: <N/A>                                                                                                                                                                                                                                                                                                                                                         
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html                                                                                                                                                                                                                                                                                  
============================================================
```


**Environment:**
1. NVIDIA ETX 3090   x 2
2. conda environment about torch
```
ffmpeg                    4.3                  hf484d3e_0    pytorch
pytorch                   2.0.1           py3.11_cuda11.8_cudnn8.7.0_0    pytorch
pytorch-cuda              11.8                 h7e8668a_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
torchaudio                2.0.2               py311_cu118    pytorch
torchtriton               2.0.0                     py311    pytorch
torchvision               0.15.2              py311_cu118    pytorch
```
4. CUDA version
```
$ echo $CUDA_HOME
/usr/local/cuda-11.8/
```
5. spconv Edition 
`spconv-cu118              2.3.6                    pypi_0    pypi`
6. Only one cumm and spconv, instead of multiple one are installed.

**Phernomenon:**
Same as the above discussion.
Raise the error `SPCONV_DEBUG_SAVE_PATH not found, you can specify SPCONV_DEBUG_SAVE_PATH as debug data save path to save debug data which can be attached in a issue.`

Reduce the batch_size can release the problem. 
In my case, reduce the batch_size down to 8 can make it work. If over 8, it will fail and throw the error above.

Even setting the `batch_size = 128`, the maximal GPU memory per GPU is occupied by about 19G (Total is 24G).
Set the `batch_size = 8`, the maximal GPU memory per GPU is only 2.6G per GPU.

And set `batch_size = 8` and the program can be run without error, the result of the program can be reproduce correctly.

It seems not satisfying to ease this problem by reduce the batch_size down to so small that only use 2.6G/24G GPU memory
.
Could anyone tell what happen ? And how to solve it ?

@traveller59 @FindDefinition @xmyqsh

**Comment by ZhaoChuyang** [comment]
> Hi, I meet the same problem, it seems that it is because the conflict of `cumm` and `cumm-cu111`, so I uninstall the two version of cumm and the `spconv-cu111`, and install spconv again by `pip install spconv-cu111` and it works.

Thanks. It works for me!
