### ISSUE TITLE
Building spconv on jetson nano board (aarch64)

### ISSUE THREAD

**Issue by SmBito** [traveller59/spconv#435]
Hi, I'm trying to build spconv from source on jetson nano board without success, since there is no wheel for the jetson nano.

Is there a **specify cuda arch** for the jetson nano like for Xavier, TX2 and orin

> For NVIDIA Embedded Platforms, you need to specify cuda arch before build: export CUMM_CUDA_ARCH_LIST="7.2" for xavier, export CUMM_CUDA_ARCH_LIST="6.2" for TX2, export CUMM_CUDA_ARCH_LIST="8.7" for orin.

Environment：
NVIDIA Jetson Nano Developer Kit  (aarch64)
Python: 3.7.5
cumm: 0.3.0
cuda: 10.2

Please help me!!! Thank you!

**Comment by SmBito** [comment]
I installed PyTorch 1.7.0 and when I import spconv, I get: No such file or directory: 'nvidia-smi': 'nvidia-smi' :

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jetson/build_spconv/spconv4/spconv/spconv/__init__.py", line 15, in <module>
    from . import build as _build
  File "/home/jetson/build_spconv/spconv4/spconv/spconv/build.py", line 24, in <module>
    from spconv.core import SHUFFLE_SIMT_PARAMS, SHUFFLE_VOLTA_PARAMS, SHUFFLE_TURING_PARAMS
  File "/home/jetson/build_spconv/spconv4/spconv/spconv/core.py", line 15, in <module>
    from cumm.gemm.main import gen_shuffle_params_v2 as gen_shuffle_params, GemmAlgoParams
  File "/home/jetson/build_spconv/spconv4/cumm/cumm/__init__.py", line 33, in <module>
    verbose=True)
  File "/home/jetson/env_spconv_py36/lib/python3.6/site-packages/pccm/builder/pybind.py", line 56, in build_pybind
    user_cus = cg.build_graph(cus, namespace_root)
  File "/home/jetson/env_spconv_py36/lib/python3.6/site-packages/pccm/core/__init__.py", line 1903, in build_graph
    cu_type_to_cu[dep] = dep()
  File "/home/jetson/env_spconv_py36/lib/python3.6/site-packages/pccm/core/__init__.py", line 844, in wrapper
    func(self, *args, **kwargs)
  File "/home/jetson/build_spconv/spconv4/cumm/cumm/common.py", line 232, in __init__
    gpu_arch_flags, self.cuda_archs = _get_cuda_arch_flags()
  File "/home/jetson/build_spconv/spconv4/cumm/cumm/common.py", line 146, in _get_cuda_arch_flags
    "--format=csv,noheader"]).decode("utf-8")
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nvidia-smi': 'nvidia-smi' 
```
 
The problem, _**nvidia-smi**_ is not supported on Jetson Boards (Tegra-based platforms).

**Comment by gzchenjiajun** [comment]
same problem 
how  to solve ?
