### ISSUE TITLE
about installing setup.py

### ISSUE THREAD

**Issue by mzy97** [traveller59/spconv#44]
I encounter a error when running setup.py following the readme command line.
how to fix it?
Environment:
ubuntu 16.04
pytorch 1.0.1
cuda 9.0
cudnn 7.4.1
gcc/g++ 5.4

error message:
`Scanning dependencies of target spconv_nms
Scanning dependencies of target spconv
[  7%] Building CUDA object src/utils/CMakeFiles/spconv_nms.dir/nms.cu.o
[ 21%] Building CXX object src/spconv/CMakeFiles/spconv.dir/all.cc.o
[ 28%] Building CXX object src/spconv/CMakeFiles/spconv.dir/indice.cc.o
[ 28%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/indice.cu.o
[ 35%] Linking CUDA static library libspconv_nms.a
[ 35%] Built target spconv_nms
[ 42%] Building CXX object src/spconv/CMakeFiles/spconv.dir/reordering.cc.o
[ 50%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/reordering.cu.o
[ 57%] Building CXX object src/spconv/CMakeFiles/spconv.dir/maxpool.cc.o
[ 64%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/maxpool.cu.o
Scanning dependencies of target spconv_utils
[ 71%] Linking CUDA device code CMakeFiles/spconv.dir/cmake_device_link.o
[ 78%] Linking CXX shared library ../../../lib.linux-x86_64-3.7/spconv/libspconv.so
/usr/bin/ld: cannot find /usr/local/cudnn/lib64/: File format not recognized
collect2: error: ld returned 1 exit status
src/spconv/CMakeFiles/spconv.dir/build.make:238: recipe for target '../lib.linux-x86_64-3.7/spconv/libspconv.so' failed
make[2]: *** [../lib.linux-x86_64-3.7/spconv/libspconv.so] Error 1
CMakeFiles/Makefile2:108: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all' failed
make[1]: *** [src/spconv/CMakeFiles/spconv.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 85%] Building CXX object src/utils/CMakeFiles/spconv_utils.dir/all.cc.o
[ 92%] Linking CUDA device code CMakeFiles/spconv_utils.dir/cmake_device_link.o
[100%] Linking CXX shared library ../../../lib.linux-x86_64-3.7/spconv/spconv_utils.cpython-37m-x86_64-linux-gnu.so
[100%] Built target spconv_utils
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 89, in <module>
    zip_safe=False,
  File "/home/muzhengyang/anaconda3/envs/SECOND/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/muzhengyang/anaconda3/envs/SECOND/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/muzhengyang/anaconda3/envs/SECOND/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/muzhengyang/anaconda3/envs/SECOND/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/muzhengyang/anaconda3/envs/SECOND/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
    self.run_command('build')
  File "/home/muzhengyang/anaconda3/envs/SECOND/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/muzhengyang/anaconda3/envs/SECOND/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/muzhengyang/anaconda3/envs/SECOND/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/muzhengyang/anaconda3/envs/SECOND/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/muzhengyang/anaconda3/envs/SECOND/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 40, in run
    self.build_extension(ext)
  File "setup.py", line 73, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/muzhengyang/anaconda3/envs/SECOND/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.`

**Comment by mzy97** [comment]
the screenshot of error message
![屏幕快照 2019-04-30 下午5 42 37](https://user-images.githubusercontent.com/31816690/56953564-703b7f00-6b6f-11e9-9f39-488a24443bdb.png)

**Comment by traveller59** [comment]
I think this is due to wrong cudnn location. please install cudnn libs to /usr/local/cuda instead of /usr/local/cudnn.

**Comment by mzy97** [comment]
the file system in my server is read-only, i can't have the permission to change it. pls tell me how to change the cudnn settings in code to make it compile in the right way? @traveller59

**Comment by HenryJunW** [comment]
You can refer to #78
