### ISSUE TITLE
Got this error when try to build from source on Jetson Xavier NX

### ISSUE THREAD

**Issue by ChulanZhang** [traveller59/spconv#443]
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pengcheng/spconv/spconv/__init__.py", line 15, in <module>
    from . import build as _build
  File "/home/pengcheng/spconv/spconv/build.py", line 49, in <module>
    load_library=False)
  File "/home/pengcheng/archiconda3/envs/openpcdet/lib/python3.6/site-packages/pccm/builder/pybind.py", line 141, in build_pybind
    objects_folder=objects_folder)
  File "/home/pengcheng/archiconda3/envs/openpcdet/lib/python3.6/site-packages/ccimport/core.py", line 182, in ccimport
    linker_to_path=linker_to_path)
  File "/home/pengcheng/archiconda3/envs/openpcdet/lib/python3.6/site-packages/ccimport/buildtools/writer.py", line 997, in build_simple_ninja
    raise subprocess.CalledProcessError(proc.returncode, cmds)
subprocess.CalledProcessError: Command '['ninja']' returned non-zero exit status 1.

**Comment by SmBito** [comment]
I am facing the same problem on Jetson TX2: 


gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tx2/spconv/spconv/__init__.py", line 15, in <module>
    from . import build as _build
  File "/home/tx2/spconv/spconv/build.py", line 49, in <module>
    load_library=False)
  File "/usr/local/lib/python3.6/dist-packages/pccm/builder/pybind.py", line 141, in build_pybind
    objects_folder=objects_folder)
  File "/usr/local/lib/python3.6/dist-packages/ccimport/core.py", line 182, in ccimport
    linker_to_path=linker_to_path)
  File "/usr/local/lib/python3.6/dist-packages/ccimport/buildtools/writer.py", line 997, in build_simple_ninja
    raise subprocess.CalledProcessError(proc.returncode, cmds)
subprocess.CalledProcessError: Command '['ninja']' returned non-zero exit status 1.

**Comment by SmBito** [comment]
Until now I could only install spconv v1.2.1 on Jetson TX2
Here are the steps:
git clone -b v1.2.1 https://github.com/traveller59/spconv.git --recursive

sudo apt-get install libboost-all-dev
python3 setup.py bdist_wheel
export PYTHONPATH="/spconv/build/lib.linux-aarch64-3.6"

then in python: import spcovn

**Environment：**
NVIDIA Jetson TX2 (aarch64)
Ubuntu 18.04.6 LTS
JetPack 4.6 L4T 32.6.1
Python 3.6.9
cumm 0.2.8
spconv 1.2.1
cuda: 10.2
torch 1.9.0
gcc/g++ 7.5.0
cmake 3.10.2
ninja 1.10.0
