### ISSUE TITLE
ModuleNotFoundError: No module named 'spconv.core_cc.csrc.sparse.all.ops1d'; 'spconv.core_cc.csrc.sparse.all' is not a package

### ISSUE THREAD

**Issue by caozhe1011** [traveller59/spconv#453]
When I installed spconv(CPU), I found this problem:

> import spconv.pytorch as spconv
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/venv-py3/lib/python3.6/site-packages/spconv/pytorch/__init__.py", line 6, in <module>
>     from spconv.pytorch.core import SparseConvTensor
>   File "/home/venv-py3/lib/python3.6/site-packages/spconv/pytorch/core.py", line 21, in <module>
>     from spconv.tools import CUDAKernelTimer
>   File "/home/venv-py3/lib/python3.6/site-packages/spconv/tools.py", line 18, in <module>
>     from spconv.utils import nullcontext
>   File "/home/venv-py3/lib/python3.6/site-packages/spconv/utils/__init__.py", line 27, in <module>
>     from spconv.core_cc.csrc.sparse.all.ops1d import Point2Voxel as Point2VoxelGPU1d
> ModuleNotFoundError: No module named 'spconv.core_cc.csrc.sparse.all.ops1d'; 'spconv.core_cc.csrc.sparse.all' is not a package

And my pip list is :
![image](https://user-images.githubusercontent.com/49895732/159934282-53bdcf08-a5dc-4dd7-a52b-6e0b7e7ca0dd.png)
![image](https://user-images.githubusercontent.com/49895732/159934332-e8c49c96-ab87-4b3b-9e5a-56e731b0af99.png)
![image](https://user-images.githubusercontent.com/49895732/159934141-f40acf52-a1fb-4ff9-97a2-054271013d0b.png)

**Comment by Abbas-Syed** [comment]
I get the same error with spconv

**Comment by Abbas-Syed** [comment]
> same problem.

Hello Wang. I gave up and set up OpenPCDet on WSL2 for windows. I can get the demo working but need to test other things. Let me know if you want to try doing that  and I can help you

**Comment by mengmeng4263** [comment]
Same problem.

**Comment by lhy0807** [comment]
same problem

**Comment by lfxx** [comment]
same issue

**Comment by violin-tree** [comment]
is there any solutions? I 've got the same problem

**Comment by mrtpk123** [comment]
I'm facing the same problem

**Comment by mrtpk123** [comment]
I got this import error with `Pytorch 1.12` and `spconv 2.1.22`. Downgrading `spconv` to  `2.1.12` solved the issue.

**Comment by rohithsaro** [comment]
`I was using  `
