### ISSUE TITLE
ModuleNotFoundError: No module named 'spconv.modules'

### ISSUE THREAD

**Issue by Sandeepjalui93** [traveller59/spconv#459]
[2022-04-04 17:03:52,773  INFO  log.py  line 40  92724]  ************************ Start Logging ************************
'cp' is not recognized as an internal or external command,
operable program or batch file.
'cp' is not recognized as an internal or external command,
operable program or batch file.
'cp' is not recognized as an internal or external command,
operable program or batch file.
'cp' is not recognized as an internal or external command,
operable program or batch file.
[2022-04-04 17:03:52,839  INFO  test.py  line 32  92724]  Namespace(TEST_NMS_THRESH=0.3, TEST_NPOINT_THRESH=100, TEST_SCORE_THRESH=0.09, batch_size=4, bg_thresh=0.25, block_reps=2, block_residual=True, classes=20, cluster_meanActive=50, cluster_npoint_thre=50, cluster_radius=0.03, cluster_shift_meanActive=300, config='config/pointgroup_default_scannet.yaml', data_root='dataset', dataset='scannetv2', dataset_dir='data/scannetv2_inst.py', epochs=384, eval=True, exp_path='exp\\scannetv2\\pointgroup\\pointgroup_default_scannet', fg_thresh=0.75, filename_suffix='_inst_nostuff.pth', fix_module=[], full_scale=[128, 512], ignore_label=-100, input_channel=3, loss_weight=[1.0, 1.0, 1.0, 1.0], lr=0.001, m=16, manual_seed=123, max_npoint=250000, mode=4, model_dir='model/pointgroup/pointgroup.py', model_name='pointgroup', momentum=0.9, multiplier=0.5, optim='Adam', prepare_epochs=128, pretrain='', pretrain_module=[], pretrain_path=None, save_freq=16, save_instance=False, save_pt_offsets=False, save_semantic=False, scale=50, score_fullscale=14, score_mode=4, score_scale=50, split='val', step_epoch=384, task='test', test_epoch=384, test_seed=567, test_workers=16, train_workers=16, use_coords=True, weight_decay=0.0001)
[2022-04-04 17:03:52,841  INFO  test.py  line 188  92724]  => creating model ...
[2022-04-04 17:03:52,841  INFO  test.py  line 189  92724]  Classes: 20
Traceback (most recent call last):
  File "test.py", line 192, in <module>
    from model.pointgroup.pointgroup import PointGroup as Network
  File "C:\Users\sjalu\OneDrive\Desktop\OPS\PointGroup\model\pointgroup\pointgroup.py", line 9, in <module>
    from spconv.modules import SparseModule
ModuleNotFoundError: No module named 'spconv.modules'

Can anybody help me resolve the issue?

**Comment by shijinghuihub** [comment]
My problem is  ModuleNotFoundError: No module named 'spconv.SparseModule' and I use spconv 2.x . I solve the problem by changing import spconv to import spconv.pytorch as spconv
