### ISSUE TITLE
Build spconv 1.2.1 with python 3.9

### ISSUE THREAD

**Issue by Shawnxm** [traveller59/spconv#471]
I am trying to build spconv 1.2.1 with python 3.9 (conda) on ubuntu 18.04 (cmake v3.20.5) following the instructions in the v1.2.1 [README](https://github.com/traveller59/spconv/blob/v1.2.1/README.md).

After running `python setup.py bdist_wheel`, I got the following messages with errors.
```
running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/xxx/anaconda3/envs/myenv/lib/python3.9/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.9', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=11000', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/z/home/xxx/yyy/spconv/build/lib.linux-x86_64-3.9/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- Caffe2: CUDA detected: 10.2
-- Caffe2: CUDA nvcc is: /usr/local/cuda-10.2/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-10.2
-- Caffe2: Header version is: 10.2
-- Found cuDNN: v8.2.1  (include: /usr/local/cuda-10.2/include, library: /usr/local/cuda-10.2/lib64/libcudnn.so)
-- /usr/local/cuda-10.2/lib64/libnvrtc.so shorthash is 08c4863f
-- Autodetected CUDA architecture(s):  7.5 7.5 7.5 7.5
-- Added CUDA NVCC flags for: -gencode;arch=compute_75,code=sm_75
-- MKL_ARCH: intel64
-- MKL_ROOT /opt/intel/oneapi/mkl/2021.4.0
-- MKL_LINK: dynamic
-- MKL_INTERFACE_FULL: intel_ilp64
-- MKL_THREADING: intel_thread
-- MKL_MPI: intelmpi
CMake Warning at /home/xxx/anaconda3/envs/myenv/lib/python3.9/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  static library kineto_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  /home/xxx/anaconda3/envs/myenv/lib/python3.9/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
  CMakeLists.txt:22 (find_package)


-- Autodetected CUDA architecture(s):  7.5 7.5 7.5 7.5
-- Found PythonInterp: /home/xxx/anaconda3/envs/myenv/bin/python3.9 (found suitable version "3.9.12", minimum required is "3.9") 
-- pybind11 v2.5.0
-- Configuring done
CMake Warning (dev) in src/cuhash/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "cuhash".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/cuhash/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "cuhash".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/spconv/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/spconv/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/utils/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv_nms".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/utils/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv_nms".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /z/home/xxx/yyy/spconv/build/temp.linux-x86_64-3.9
Consolidate compiler generated dependencies of target spconv_nms
[  8%] Built target spconv_nms
Consolidate compiler generated dependencies of target spconv_utils
Consolidate compiler generated dependencies of target cuhash
[ 12%] Linking CXX shared library ../../../lib.linux-x86_64-3.9/spconv/libcuhash.so
[ 20%] Built target spconv_utils
/usr/bin/ld: cannot find -lmkl_intel_ilp64
/usr/bin/ld: cannot find -lmkl_core
/usr/bin/ld: cannot find -lmkl_intel_thread
collect2: error: ld returned 1 exit status
src/cuhash/CMakeFiles/cuhash.dir/build.make:202: recipe for target '../lib.linux-x86_64-3.9/spconv/libcuhash.so' failed
make[2]: *** [../lib.linux-x86_64-3.9/spconv/libcuhash.so] Error 1
CMakeFiles/Makefile2:153: recipe for target 'src/cuhash/CMakeFiles/cuhash.dir/all' failed
make[1]: *** [src/cuhash/CMakeFiles/cuhash.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/z/home/xxx/yyy/spconv/setup.py", line 96, in <module>
    setup(
  File "/home/xxx/anaconda3/envs/myenv/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/xxx/anaconda3/envs/myenv/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/home/xxx/anaconda3/envs/myenv/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/home/xxx/anaconda3/envs/myenv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/home/xxx/anaconda3/envs/myenv/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/xxx/anaconda3/envs/myenv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/xxx/anaconda3/envs/myenv/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/home/xxx/anaconda3/envs/myenv/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/xxx/anaconda3/envs/myenv/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/xxx/anaconda3/envs/myenv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/xxx/anaconda3/envs/myenv/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/xxx/anaconda3/envs/myenv/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/xxx/anaconda3/envs/myenv/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/xxx/anaconda3/envs/myenv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/z/home/xxx/yyy/spconv/setup.py", line 48, in run
    self.build_extension(ext)
  File "/z/home/xxx/yyy/spconv/setup.py", line 92, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/xxx/anaconda3/envs/myenv/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
```

Any thoughts on where the problem could be? Thanks!

**Comment by Shawnxm** [comment]
The problem comes from this part:
```
/usr/bin/ld: cannot find -lmkl_intel_ilp64
/usr/bin/ld: cannot find -lmkl_core
/usr/bin/ld: cannot find -lmkl_intel_thread
```

Fixed.

**Comment by CatOneTwo** [comment]
Hi, how did you fix these problems?

**Comment by Shawnxm** [comment]
There were two versions of lmkl installed on my machine. I removed the one with a wrong/incompatible version.
