### ISSUE TITLE
derivative for to_sparse is not implemented

### ISSUE THREAD

**Issue by Haoran-P** [traveller59/spconv#474]
Traceback (most recent call last):
File "main.py", line 113, in
main(config)
File "main.py", line 73, in main
solver.train()
File "/home/snap_user/Image_Segmentation/solver1.py", line 162, in train
loss.backward()
File "/home/snap_user/anaconda3/lib/python3.8/site-packages/torch/_tensor.py", line 255, in backward
torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
File "/home/snap_user/anaconda3/lib/python3.8/site-packages/torch/autograd/init.py", line 147, in backward
Variable._execution_engine.run_backward(
RuntimeError: derivative for to_sparse is not implemented

Hi, I met the problem when I added sparse Conv to my project.
While the MNIST example could run well in the same environment.

**Comment by dbraun-ub** [comment]
to_sparse is a pytorch function. I had the same issue and I've fixed it by updating my pytorch version. Works fine for me with pytorch 1.10.1.
