### ISSUE TITLE
Error 700 an illegal memory access was encountered when batch_size >= 4

### ISSUE THREAD

**Issue by Gofinge** [traveller59/spconv#481]
Hi, thanks for your work. But I am encountering an error when batch_size >= 4 on each GPU. Hope that I can figure out the reason.

My environment is:
```
CUDA: 10.2 (11.1)
PyTorch: 1.10.0
spconv: 2.1.21
```

Here is the detailed error report:

```{bash}
[Exception|implicit_gemm]feat=torch.Size([349459, 64]),w=torch.Size([32, 2, 2, 2, 64]),pair=torch.Size([8, 531843]),act=531843,issubm=False,istrain=True
SPCONV_DEBUG_SAVE_PATH not found, you can specify SPCONV_DEBUG_SAVE_PATH as debug data save path to save debug data which can be attached in a issue.
Traceback (most recent call last):
  File "/home/gofinge/Documents/projects/PointTransformerV2/tools/train.py", line 517, in <module>
    main()
  File "/home/gofinge/Documents/projects/PointTransformerV2/tools/train.py", line 117, in main
    main_worker(cfg.train_gpu, cfg.num_gpus_per_node, cfg)
  File "/home/gofinge/Documents/projects/PointTransformerV2/tools/train.py", line 246, in main_worker
    loss_train, mIoU_train, mAcc_train, allAcc_train = train(cfg, train_loader, model, criteria, optimizer,
  File "/home/gofinge/Documents/projects/PointTransformerV2/tools/train.py", line 325, in train
    output = model(input_dict)
  File "/home/gofinge/miniconda3/envs/pt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/gofinge/miniconda3/envs/pt/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/gofinge/miniconda3/envs/pt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/gofinge/Documents/projects/PointTransformerV2/pointseg/model/sparse_unet/spconv_unet.py", line 188, in forward
    x = self.up[s](x)
  File "/home/gofinge/miniconda3/envs/pt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/gofinge/miniconda3/envs/pt/lib/python3.8/site-packages/torch_points3d/core/data_transform/../../../spconv/pytorch/modules.py", line 137, in forward
    input = module(input)
  File "/home/gofinge/miniconda3/envs/pt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/gofinge/miniconda3/envs/pt/lib/python3.8/site-packages/torch_points3d/core/data_transform/../../../spconv/pytorch/conv.py", line 441, in forward
    out_features = Fsp.implicit_gemm(
  File "/home/gofinge/miniconda3/envs/pt/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 94, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/gofinge/miniconda3/envs/pt/lib/python3.8/site-packages/torch_points3d/core/data_transform/../../../spconv/pytorch/functional.py", line 200, in forward
    raise e 
  File "/home/gofinge/miniconda3/envs/pt/lib/python3.8/site-packages/torch_points3d/core/data_transform/../../../spconv/pytorch/functional.py", line 185, in forward
    out, mask_out, mask_width = ops.implicit_gemm(features, filters,
  File "/home/gofinge/miniconda3/envs/pt/lib/python3.8/site-packages/torch_points3d/core/data_transform/../../../spconv/pytorch/ops.py", line 1103, in implicit_gemm
    tune_res, _ = CONV.tune_and_cache(
  File "/home/gofinge/miniconda3/envs/pt/lib/python3.8/site-packages/torch_points3d/core/data_transform/../../../spconv/algo.py", line 660, in tune_and_cache
    ConvMainUnitTest.implicit_gemm2(params)
RuntimeError: /io/build/temp.linux-x86_64-3.8/spconv/build/src/cumm/conv/main/ConvMainUnitTest/ConvMainUnitTest_implicit_gemm2.cu 580
cuda execution failed with error 700 an illegal memory access was encountered
Simt_f32f32f32f32f32tnt_m32n128k16m32n32k8_200_C301LLLA1_SK error with params [349459, 64] [32, 8, 64] [531843, 32] [8, 531843] [531843] [531843] [] -1
```

**Comment by Gofinge** [comment]
Solved, too dense voxel size lead to out of bounds of int32
