### ISSUE TITLE
ValueError: your out spatial shape [0, 62, 62] reach zero!!! input shape: [1, 124, 124]

### ISSUE THREAD

**Issue by Stone-sy** [traveller59/spconv#506]
ValueError: your out spatial shape [0, 62, 62] reach zero!!! input shape: [1, 124, 124]
[Exception|implicit_gemm_pair]indices=torch.Size([2266, 4]),bs=1,ss=[1, 124, 124],algo=ConvAlgo.MaskImplicitGemm,ksize=[3, 3, 3],stride=[2, 2, 2],padding=[0, 1, 1],dilation=[1, 1, 1],subm=False,transpose=False
SPCONV_DEBUG_SAVE_PATH not found, you can specify SPCONV_DEBUG_SAVE_PATH as debug data save path to save debug data which can be attached in a issue.
Traceback (most recent call last):                                                                                                                                        
  File "train.py", line 201, in <module>
    main()
  File "train.py", line 153, in main
    train_model(
  File "/home/shi/mycode/OpenPCDet/tools/train_utils/train_utils.py", line 111, in train_model
    accumulated_iter = train_one_epoch(
  File "/home/shi/mycode/OpenPCDet/tools/train_utils/train_utils.py", line 47, in train_one_epoch
    loss, tb_dict, disp_dict = model_func(model, batch)
  File "../pcdet/models/__init__.py", line 42, in model_func
    ret_dict, tb_dict, disp_dict = model(batch_dict)
  File "/home/shi/miniconda3/envs/pcdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/shi/miniconda3/envs/pcdet/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/shi/miniconda3/envs/pcdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "../pcdet/models/detectors/pv_rcnn.py", line 11, in forward
    batch_dict = cur_module(batch_dict)
  File "/home/shi/miniconda3/envs/pcdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "../pcdet/models/backbones_3d/spconv_backbone.py", line 152, in forward
    x_conv4 = self.conv4(x_conv3)
  File "/home/shi/miniconda3/envs/pcdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/shi/miniconda3/envs/pcdet/lib/python3.8/site-packages/spconv/pytorch/modules.py", line 137, in forward
    input = module(input)
  File "/home/shi/miniconda3/envs/pcdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/shi/miniconda3/envs/pcdet/lib/python3.8/site-packages/spconv/pytorch/modules.py", line 137, in forward
    input = module(input)
  File "/home/shi/miniconda3/envs/pcdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/shi/miniconda3/envs/pcdet/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 404, in forward
    raise e
  File "/home/shi/miniconda3/envs/pcdet/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 381, in forward
    res = ops.get_indice_pairs_implicit_gemm(
  File "/home/shi/miniconda3/envs/pcdet/lib/python3.8/site-packages/spconv/pytorch/ops.py", line 280, in get_indice_pairs_implicit_gemm
    raise ValueError(
ValueError: your out spatial shape [0, 62, 62] reach zero!!! input shape: [1, 124, 124]
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/shi/miniconda3/envs/pcdet/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/home/shi/miniconda3/envs/pcdet/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1491968) is killed by signal: Terminated. 
                                                                                                                                                                         ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1489705) of binary: /home/shi/miniconda3/envs/pcdet/bin/python                
Traceback (most recent call last):
  File "/home/shi/miniconda3/envs/pcdet/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/shi/miniconda3/envs/pcdet/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/shi/miniconda3/envs/pcdet/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/shi/miniconda3/envs/pcdet/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/shi/miniconda3/envs/pcdet/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/shi/miniconda3/envs/pcdet/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/shi/miniconda3/envs/pcdet/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/shi/miniconda3/envs/pcdet/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-08-25_14:19:57
  host      : localhost
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1489706)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-08-25_14:19:57
  host      : localhost
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1489705)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by zhaowenZhou** [comment]
Hi! Did you solve it?

**Comment by lixiuyu-cumt** [comment]
I saw the same problem, had you solved it ?
