### ISSUE TITLE
ImportError: cannot import name 'NVRTCMode'

### ISSUE THREAD

**Issue by 954608128** [traveller59/spconv#508]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/spconv/__init__.py", line 15, in <module>
    from . import build as _build
  File "/opt/conda/lib/python3.6/site-packages/spconv/build.py", line 21, in <module>
    from .constants import PACKAGE_NAME, PACKAGE_ROOT, DISABLE_JIT
  File "/opt/conda/lib/python3.6/site-packages/spconv/constants.py", line 19, in <module>
    from cumm.gemm.constants import NVRTCMode

**Comment by wyw-dlut** [comment]
i meet the same problem. cy

**Comment by 954608128** [comment]
version problem.

**Comment by gbliao** [comment]
Please refer to https://github.com/traveller59/spconv. 

I solved this problem by referring to the following suggestions.

```
WARNING
Use spconv >= cu114 if possible. cuda 11.4 can compile greatly faster kernel in some situation.

Update Spconv: you MUST UNINSTALL all spconv/cumm/spconv-cuxxx/cumm-cuxxx first, use pip list | grep spconv and pip list | grep cumm to check all installed package. then use pip to install new spconv.
```

**Comment by zhangtingyu11** [comment]
> Please refer to https://github.com/traveller59/spconv.
> 
> I solved this problem by referring to the following suggestions.
> 
> ```
> WARNING
> Use spconv >= cu114 if possible. cuda 11.4 can compile greatly faster kernel in some situation.
> 
> Update Spconv: you MUST UNINSTALL all spconv/cumm/spconv-cuxxx/cumm-cuxxx first, 
> 
> use pip list | grep spconv and pip list | grep cumm to check all installed package. 
> 
> then use pip to install new spconv.
> ```

I use `pip list | grep cumm` and find two version cumm installed in the virtual environment. I uninstall the dismatched version and the error disappears.

**Comment by NNNNerd** [comment]
> pip list | grep cumm

May I ask what is the version of your spconv and cumm? My CUDA version is 11.6 therefore I got spconv-cu116 and cumm-cu116. And my environment contains only one cumm. However, the error exists.
