### ISSUE TITLE
cant remove spconv in conda list

### ISSUE THREAD

**Issue by ZhaoPeisen99** [traveller59/spconv#514]
_import spconv in python shows below :_
>>> import spconv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/noya/anaconda3/envs/CLOCs/lib/python3.6/site-packages/spconv/__init__.py", line 19, in <module>
    from spconv import utils
  File "/home/noya/anaconda3/envs/CLOCs/lib/python3.6/site-packages/spconv/utils/__init__.py", line 16, in <module>
    from spconv import spconv_utils
ImportError: libspconv_nms.so.1: cannot open shared object file: No such file or directory

_But it can be found in conda list:_ spconv                    1.0                       <pip>

_However when i conda remove:_
PackagesNotFoundError: The following packages are missing from the target environment:

_My enviroment_
pytorch 1.1
python 3.6

**Comment by ZhaoPeisen99** [comment]
Oh I just find those "spconv" file in python site_packages and delete it can work
