### ISSUE TITLE
error in setup spconv1.2.1

### ISSUE THREAD

**Issue by forcekkk** [traveller59/spconv#562]
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/spconv
copying spconv/__init__.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/conv.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/functional.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/identity.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/modules.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/ops.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/pool.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/tables.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/test_utils.py -> build/lib.linux-x86_64-3.6/spconv
creating build/lib.linux-x86_64-3.6/spconv/utils
copying spconv/utils/__init__.py -> build/lib.linux-x86_64-3.6/spconv/utils
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/weizikun/anaconda3/envs/py36_torch110/lib/python3.6/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=11000', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/weizikun/github/VOTR_quant/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- The CXX compiler identification is GNU 7.5.0
-- The CUDA compiler identification is NVIDIA 11.6.55
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /home/weizikun/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /home/weizikun/cuda (found version "11.6")
-- Caffe2: CUDA detected: 11.6
-- Caffe2: CUDA nvcc is: /home/weizikun/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /home/weizikun/cuda
-- Caffe2: Header version is: 11.6
-- Found CUDNN: /home/weizikun/cuda/lib64/libcudnn.so
-- Found cuDNN: v8.6.0  (include: /home/weizikun/cuda/include, library: /home/weizikun/cuda/lib64/libcudnn.so)
-- /home/weizikun/cuda/lib64/libnvrtc.so shorthash is 280a23f6
-- Autodetected CUDA architecture(s):  8.0 8.0
-- Added CUDA NVCC flags for: -gencode;arch=compute_80,code=sm_80
-- MKL_ARCH: None, set to ` intel64` by default
-- MKL_ROOT /opt/intel/oneapi/mkl/2022.2.1
-- MKL_LINK: None, set to ` dynamic` by default
-- MKL_INTERFACE_FULL: None, set to ` intel_ilp64` by default
-- MKL_THREADING: None, set to ` intel_thread` by default
-- MKL_MPI: None, set to ` intelmpi` by default
-- Found Torch: /home/weizikun/anaconda3/envs/py36_torch110/lib/python3.6/site-packages/torch/lib/libtorch.so
-- Autodetected CUDA architecture(s):  8.0 8.0
-- Found PythonInterp: /home/weizikun/anaconda3/envs/py36_torch110/bin/python3.6 (found suitable version "3.6.13", minimum required is "3.6")
-- Found PythonLibs: /home/weizikun/anaconda3/envs/py36_torch110/lib/libpython3.6m.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- pybind11 v2.5.0
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/weizikun/github/VOTR_quant/spconv/build/temp.
linux-x86_64-3.6
[  4%] Building CUDA object src/utils/CMakeFiles/spconv_nms.dir/nms.cu.o
[  8%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cu.o
[ 16%] Building CXX object src/cuhash/CMakeFiles/cuhash.dir/hash_table.cpp.o
[ 16%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_table.cu.o
[ 20%] Building CXX object src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cpp.o
[ 25%] Linking CUDA static library libspconv_nms.a
[ 25%] Built target spconv_nms
[ 29%] Building CXX object src/utils/CMakeFiles/spconv_utils.dir/all.cc.o
[ 33%] Linking CUDA device code CMakeFiles/cuhash.dir/cmake_device_link.o
[ 37%] Linking CXX shared library /home/weizikun/github/VOTR_quant/spconv/build/lib.linux-x86_64-3.6/spconv/libcuhash.so
/usr/bin/ld: cannot find -lmkl_intel_ilp64
/usr/bin/ld: cannot find -lmkl_core
/usr/bin/ld: cannot find -lmkl_intel_thread
collect2: error: ld returned 1 exit status
src/cuhash/CMakeFiles/cuhash.dir/build.make:204: recipe for target '/home/weizikun/github/VOTR_quant/spconv/build/lib.linux-x86_64-3.6/spconv/libcuhash.so' failed
make[2]: *** [/home/weizikun/github/VOTR_quant/spconv/build/lib.linux-x86_64-3.6/spconv/libcuhash.so] Error 1
CMakeFiles/Makefile2:153: recipe for target 'src/cuhash/CMakeFiles/cuhash.dir/all' failed
make[1]: *** [src/cuhash/CMakeFiles/cuhash.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 41%] Linking CXX shared library /home/weizikun/github/VOTR_quant/spconv/build/lib.linux-x86_64-3.6/spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so
[ 41%] Built target spconv_utils
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 108, in <module>
    zip_safe=False,
  File "/home/weizikun/anaconda3/envs/py36_torch110/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/weizikun/anaconda3/envs/py36_torch110/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/weizikun/anaconda3/envs/py36_torch110/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/weizikun/anaconda3/envs/py36_torch110/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/weizikun/anaconda3/envs/py36_torch110/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/home/weizikun/anaconda3/envs/py36_torch110/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
File "/home/weizikun/anaconda3/envs/py36_torch110/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/weizikun/anaconda3/envs/py36_torch110/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/weizikun/anaconda3/envs/py36_torch110/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/weizikun/anaconda3/envs/py36_torch110/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 48, in run
    self.build_extension(ext)
  File "setup.py", line 92, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/weizikun/anaconda3/envs/py36_torch110/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

**Comment by forcekkk** [comment]
my torch version is 1.10,python 3.6, cuda 11.6, cudnn 8.6

**Comment by forcekkk** [comment]
my torch version is 1.10, python 3.6, cuda 11.6, cudnn 8.6, and that's error is when run 'python setup.py bdist_wheel' for installing spconv1.2.1

**Comment by TinaLRJ** [comment]
Have you solved your problem? And how? I'm meeting the same problem.

**Comment by forcekkk** [comment]
> 
sorry, I have not solved this problem yet

**Comment by CBY-9527** [comment]
> my torch version is 1.10, python 3.6, cuda 11.6, cudnn 8.6, and that's error is when run 'python setup.py bdist_wheel' for installing spconv1.2.1

It may be because your python version is too low, you can try to upgrade the python version （>=3.7）
