### ISSUE TITLE
ConvTunerSimple_tune_and_cache.cc -> can't find suitable algorithm for 0

### ISSUE THREAD

**Issue by callzhang** [traveller59/spconv#563]
Ubuntu 20.04
Python: 3.10
CUDA: 12.0
GPU: 4090
Torch: 1.13 + cuda 11.7
Nvidia-driver: 525.85.12
Using: **fp16** mixed precision (fp32 is fine)

I have tried various methods:
- install spconv_cu117 and cumm_cu117
- install spconv_cu120 and cumm_cu120
- build spconv and cumm
- build with JIT: spconv_cu117 and cumm_cu117 / spconv_cu120 and cumm_cu120
- build wheel: spconv_cu117 and cumm_cu117 / spconv_cu120 and cumm_cu120

but all end up this:
```Python
Traceback (most recent call last):
  File "/home/lee/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/lee/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/derek/.vscode-server/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/derek/.vscode-server/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/derek/.vscode-server/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/derek/.vscode-server/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/derek/.vscode-server/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/derek/.vscode-server/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "main.py", line 177, in <module>
    trainer.fit(my_model, train_dataset_loader, val_dataset_loader)
  File "/home/lee/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/home/lee/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/lee/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/lee/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1103, in _run
    results = self._run_stage()
  File "/home/lee/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1182, in _run_stage
    self._run_train()
  File "/home/lee/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run_train
    self._run_sanity_check()
  File "/home/lee/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1267, in _run_sanity_check
    val_loop.run()
  File "/home/lee/miniconda3/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/lee/miniconda3/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/lee/miniconda3/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/lee/miniconda3/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 137, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/lee/miniconda3/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 234, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/home/lee/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1485, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/lee/miniconda3/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 390, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/derek/2DPASS/network/base_model.py", line 183, in validation_step
    data_dict = self.forward(data_dict)
  File "/home/derek/2DPASS/network/arch_2dpass.py", line 176, in forward
    data_dict = self.model_3d(data_dict)
  File "/home/lee/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/derek/2DPASS/network/spvcnn.py", line 175, in forward
    enc_feats.append(self.spv_enc[i](data_dict)) # found spv_env[4] produce nan
  File "/home/lee/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/derek/2DPASS/network/spvcnn.py", line 89, in forward
    v_fea = self.v_enc(data_dict['sparse_tensor'])
  File "/home/lee/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lee/miniconda3/lib/python3.10/site-packages/spconv/pytorch/modules.py", line 138, in forward
    input = module(input)
  File "/home/lee/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/derek/2DPASS/network/basic_block.py", line 35, in forward
    output = self.layers(x)
  File "/home/lee/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lee/miniconda3/lib/python3.10/site-packages/spconv/pytorch/modules.py", line 138, in forward
    input = module(input)
  File "/home/lee/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lee/miniconda3/lib/python3.10/site-packages/spconv/pytorch/conv.py", line 741, in forward
    return self._conv_forward(self.training, input, self.weight, self.bias, add_input,
  File "/home/lee/miniconda3/lib/python3.10/site-packages/spconv/pytorch/conv.py", line 477, in _conv_forward
    out_features, _, _ = ops.implicit_gemm(
  File "/home/lee/miniconda3/lib/python3.10/site-packages/spconv/pytorch/ops.py", line 1513, in implicit_gemm
    mask_width, tune_res_cpp = ConvGemmOps.implicit_gemm(
RuntimeError: /home/derek/tools/spconv/build/temp.linux-x86_64-cpython-310/spconv/build/core_cc/src/csrc/sparse/convops/convops/ConvTunerSimple/ConvTunerSimple_tune_and_cache.cc(103)
!all_profile_res.empty() assert faild. can't find suitable algorithm for 0
```

Few things to notice:
1. I reinstalled Ubuntu. It was working in previous Ubuntu system (22.04), I have copied previous miniconda folder over the new system. Maybe some residual file or corrupted file caused this?
2. The error message above is captured when using wheel built on my system, but the last line is still pointing to a local file, not to a system folder. Looks very suspicious.

**Comment by FindDefinition** [comment]
pytorch installed in conda will install a nvcc compiler (11.7 in your case), when you activate this environment, cuda 11.7 will override system cuda. so there are some ways to avoid this:
1. use prebuilt 
2. install pytorch + cuda 11.8 (pytorch-nightly) with conda
3. use pip instead to install pytorch

**Comment by callzhang** [comment]
Thanks @FindDefinition for your reply. However, 
1. I tried prebuilt but not working
2. Installed pytorch nightly but not working
3. I always use pip to install pytorch, maybe there are some residual files from conda?
Is there any other option you can suggest? Thanks!

**Comment by L-Reichardt** [comment]
I am getting the same issue with newer versions of the library. Downgraded to Version 2.2.3 and it is working.

Details:
CUDA 11.7 toolkit. Driver CUDA 11.7 515.86.01
RTX 3060

**Comment by rqbrother** [comment]
I got the same problem. Float64 input data maybe lead to this issue, when I check data as float32, it work finely.

**Comment by Zhongdao** [comment]
I have encountered the same issue. FP32 works fine during both training and inference. FP16 works fine during training, but will got this error when inference.

**Comment by FindDefinition** [comment]
@Zhongdao could you share a script to help me reproduce this? I can't reproduce in my environment.

**Comment by KickCellarDoor** [comment]
Same issue here. For me, it happens when part of the network is training with fp32 while the others are trained with fp16. The first fp32 op runs into error.

**Comment by sunjiahao1999** [comment]
@FindDefinition. I have encountered the same issue. FP32 works fine during both training and inference. FP16 works fine during training, but will got this error when inference. When using `torch.amp.autocast()`, SparseConvTensor's feature is not automatically converted to `torch.float16` after sparse convolution during inference (It will be converted to `torch.float16` during training). This bug is reported when using `x=x.replace_feature(x.features.half())` to force a conversion to the fp16 data type.

**Comment by Deephome** [comment]
> 

Hi, do you have any idea to solve this problem?

**Comment by FindDefinition** [comment]
@Deephome could you provide a minimal reproduce script for this problem? I can't fix this without reproduce it in my development environment.

**Comment by Deephome** [comment]
@FindDefinition I encountered this problem when I use `https://github.com/mit-han-lab/bevfusion` . I replace the bevfusion's spconv with spconv-cu113 (installed by pip). The error occurs at sparse_encoder.py, as follows
```
File "/home/bevfusion/mmdet3d/models/backbones/sparse_encoder.py", line 117, in forward
    x = self.conv_input(input_sp_tensor)
  File "/home/ubuntu/anaconda3/envs/bevfusion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/bevfusion/lib/python3.8/site-packages/spconv/pytorch/modules.py", line 138, in forward
    input = module(input)
  File "/home/ubuntu/anaconda3/envs/bevfusion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/bevfusion/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 755, in forward
    return self._conv_forward(self.training,
  File "/home/ubuntu/anaconda3/envs/bevfusion/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 467, in _conv_forward
    out_features, _, _ = ops.implicit_gemm(
  File "/home/ubuntu/anaconda3/envs/bevfusion/lib/python3.8/site-packages/spconv/pytorch/ops.py", line 1513, in implicit_gemm
    mask_width, tune_res_cpp = ConvGemmOps.implicit_gemm(
RuntimeError: /io/build/temp.linux-x86_64-cpython-38/spconv/build/core_cc/src/csrc/sparse/convops/convops/ConvTunerSimple/ConvTunerSimple_tune_and_cache.cc(103)
!all_profile_res.empty() assert faild. can't find suitable algorithm for 0
```

but when I comment `@auto_fp16(apply_to=("voxel_features",))` above forward() function, the error disappears!

**Comment by pjlearning** [comment]
Hi, @FindDefinition

I met this error when I ran the following script. It looks like it is related to the kernel size of SubMConv3d and SparseConv3d. Is there some restriction about the kernel size of the SubMConv3d?
```
spconv-cu117==2.3.6
torch==2.0.1
```
```
python train_pl.py --model_type fail
```

```
import torch
from torch import nn
from torch.nn import functional as F
import pytorch_lightning as pl
from pytorch_lightning.callbacks import LearningRateMonitor
import spconv.pytorch as spconv
from torchvision import datasets, transforms

class Net(nn.Module):
    def __init__(self,kernel_size1=7,kernel_size2=5):
        super(Net, self).__init__()
        input_ch = 1
        output_ch = 32
        self.net = spconv.SparseSequential(
            nn.BatchNorm1d(input_ch),
            spconv.SparseConv3d(input_ch, output_ch, kernel_size=kernel_size1,stride=2, padding=kernel_size1//2),
            nn.ReLU(),
            spconv.SubMConv3d(32, 64,kernel_size2, 1),
            nn.ReLU(),
            spconv.ToDense(),
        )
        self.fc1 = nn.Linear(14*14 * 14 * 64, 128)
        self.fc2 = nn.Linear(128, 10)
        self.dropout1 = nn.Dropout3d(0.25)
        self.dropout2 = nn.Dropout3d(0.5)

    def forward(self, x: torch.Tensor):
        # x: [N, 28, 28, 1], must be NHWC tensor
        x_sp = spconv.SparseConvTensor.from_dense(x.reshape(-1, 28, 28,28, 1))
        # create SparseConvTensor manually: see SparseConvTensor.from_dense
        x = self.net(x_sp)
        x = torch.flatten(x, 1)
        x = self.dropout1(x)
        x = self.fc1(x)
        x = F.relu(x)
        x = self.dropout2(x)
        x = self.fc2(x)
        output = F.log_softmax(x, dim=1)
        return output

class LitAutoEncoder(pl.LightningModule):
    def __init__(self,model_type="fail"):
        super().__init__()
        if model_type == "fail":
            self.model = Net(7,3)
        else:
            self.model = Net(7,7)

    def forward(self, x):
        x = self.model(x)
        return x

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=1e-3)
        lr_scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, factor=0.5, patience=10, verbose=True)
        lr_scheduler_config = {
            "scheduler": lr_scheduler,
            "interval": "epoch",
            "frequency": 1,
            "monitor": "val_loss",
            "strict": True,
             "name": None,
        }

        return {"optimizer": optimizer, "lr_scheduler": lr_scheduler_config}

    def training_step(self, train_batch, batch_idx):
        data, target = train_batch
        data = torch.concatenate([data]*28, dim=1)
        output = self.model(data)
        loss = F.nll_loss(output, target)
        self.log('train_loss', loss)
        return loss

    def validation_step(self, val_batch, batch_idx):
        data, target = val_batch
        data = torch.concatenate([data]*28, dim=1)

        output = self.model(data)
        loss = F.nll_loss(output, target)
        self.log('val_loss', loss)
        return loss

def get_args():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('--data_root', type=str,
                        default='data/data_odometry_voxels/dataset')
    parser.add_argument('--batch_size', type=int, default=4)
    parser.add_argument('--test_batch_size', type=int, default=8)
    parser.add_argument('--num_workers', type=int, default=8)
    parser.add_argument('--test_num_workers', type=int, default=8)
    parser.add_argument('--max_epochs', type=int, default=1000)
    parser.add_argument('--devices', type=int,nargs="+" ,default=[1])
    parser.add_argument('--accelerator', type=str, default='auto')
    parser.add_argument('--precision', type=str, default='16-mixed')
    parser.add_argument('--model_type', type=str, default='fail')
    parser.add_argument('--lr', type=float, default=1e-3)
    parser.add_argument('--mode', type=str, default='train')
    parser.add_argument('--default_root_dir', type=str, default=None)
    parser.add_argument('--checkpoint_path', type=str, default=None)
    args = parser.parse_args()
    # print args
    print(args)
    return args


def main():
    args = get_args()

    torch.set_float32_matmul_precision('medium')
    # model
    model = LitAutoEncoder(args.model_type)


    strategy='ddp_find_unused_parameters_true'

    train_loader = torch.utils.data.DataLoader(
        datasets.MNIST(
            '../data',
            train=True,
            download=True,
            transform=transforms.Compose([
                transforms.ToTensor(),
                # here we remove norm to get sparse tensor with lots of zeros
                # transforms.Normalize((0.1307,), (0.3081,))
            ])),
        batch_size=args.batch_size,
        shuffle=True)
    test_loader = torch.utils.data.DataLoader(
        datasets.MNIST(
            '../data',
            train=False,
            transform=transforms.Compose([
                transforms.ToTensor(),
                # here we remove norm to get sparse tensor with lots of zeros
                # transforms.Normalize((0.1307,), (0.3081,))
            ])),
        batch_size=args.test_batch_size,
        shuffle=False)
    lr_logger = LearningRateMonitor(logging_interval='epoch')
    trainer = pl.Trainer(devices=args.devices,
                            accelerator=args.accelerator,
                            strategy=strategy,
                            precision=args.precision,
                            max_epochs=args.max_epochs,
                            default_root_dir=args.default_root_dir,
                            callbacks=[lr_logger])
    trainer.fit(model, train_loader, test_loader,ckpt_path=args.checkpoint_path)


if __name__ == '__main__':
    main()
```

**Comment by pjlearning** [comment]
> @Deephome could you provide a minimal reproduce script for this problem? I can't fix this without reproduce it in my development environment.

Hi, @FindDefinition,

Would you happen to have any updates about this error? Are you able to reproduce the error using the script I provided?

Thank you!

Best wishes!

**Comment by pjlearning** [comment]
I checked the script I provided. When I used 16-mixed precision training, the [ConvTunerSimple.get_all_available](https://github.com/traveller59/spconv/blob/125a194d895b1bc3ad6ff907bc72641548397b32/spconv/csrc/sparse/convops.py#L1044) returned an empty ```finally_algos```. It's because ```static_key_t static_key = std::make_tuple(layout_i, layout_w, layout_o,interleave_i, interleave_w, interleave_o, inp.dtype(),weight.dtype(), out.dtype(), op_type)``` I got is ```(1,1,1,1,1,1,7,0,0,0)``` which is not in ```static_key_to_desps_```. The input is f16, but the weight and output are f32. 

Because ```implicit_gemm``` only used when ```algo= spconv.ConvAlgo.MaskImplicitGemm```, to avoid it, I need manually set all ```algo=spconv.ConvAlgo.Native```.

Hope this helps somebody meet the same error.

**Comment by mcmingchang** [comment]
> 我遇到了同样的问题。FP32 在训练和推理期间都能正常工作。FP16 在训练期间工作正常，但在推理时会出现此错误。

model.eval()

**Comment by xiaoxiaosuaxuan** [comment]
I met this error during fp16 inference, too.  Does anyone know to fix it?

**Comment by xiaoxiaosuaxuan** [comment]
> I met this error during fp16 inference, too. Does anyone know to fix it?

my solution: manually convert both model and inputs to torch.half,
```
with torch.autocast(device_type='cuda', dtype=torch.half), torch.no_grad():
    pts_feature = model.pts_middle_encoder.half()(feats.half(), coords.half(), batch_size)
  
```

**Comment by ChrisDong-THU** [comment]
I've soloved this problem with the follow changes:
```
self.conv = SubMConv2d(in_channels, out_channels, kernel_size=kernel_size, padding=(kernel_size-1) // 2, bias=False).to(torch.half)
...
with torch.autocast(device_type='cuda', dtype=torch.half):
            input = SparseConvTensor(instance_feature.flatten(0, 1), indices=batch_indices, spatial_shape=spatial_shape, batch_size=b)
            output = self.conv(input)
```
Hope it helpful for you.

**Comment by uygnef** [comment]
@FindDefinition 
Hi, is there an official solution available?

**Comment by libo87** [comment]
"manually set all `algo=spconv.ConvAlgo.Native`." @pjlearning  
this works for me

Ubuntu 22.04
Python 3.10
Pytorch 2.1.2
CUDA 12.1 
spconv+cu121

set all spconv modules like this:
conv=spconv.SubMConv3d(
                in_channels,
                embed_channels,
                kernel_size=5,
                padding=1,
                bias=False,
                indice_key="stem",
                algo=spconv.ConvAlgo.Native
            )

**Comment by hawl666** [comment]
> I checked the script I provided. When I used 16-mixed precision training, the [ConvTunerSimple.get_all_available](https://github.com/traveller59/spconv/blob/125a194d895b1bc3ad6ff907bc72641548397b32/spconv/csrc/sparse/convops.py#L1044) returned an empty `finally_algos`. It's because `static_key_t static_key = std::make_tuple(layout_i, layout_w, layout_o,interleave_i, interleave_w, interleave_o, inp.dtype(),weight.dtype(), out.dtype(), op_type)` I got is `(1,1,1,1,1,1,7,0,0,0)` which is not in `static_key_to_desps_`. The input is f16, but the weight and output are f32.
> 
> Because `implicit_gemm` only used when `algo= spconv.ConvAlgo.MaskImplicitGemm`, to avoid it, I need manually set all `algo=spconv.ConvAlgo.Native`.
> 
> Hope this helps somebody meet the same error.



> I checked the script I provided. When I used 16-mixed precision training, the [ConvTunerSimple.get_all_available](https://github.com/traveller59/spconv/blob/125a194d895b1bc3ad6ff907bc72641548397b32/spconv/csrc/sparse/convops.py#L1044) returned an empty `finally_algos`. It's because `static_key_t static_key = std::make_tuple(layout_i, layout_w, layout_o,interleave_i, interleave_w, interleave_o, inp.dtype(),weight.dtype(), out.dtype(), op_type)` I got is `(1,1,1,1,1,1,7,0,0,0)` which is not in `static_key_to_desps_`. The input is f16, but the weight and output are f32.
> 
> Because `implicit_gemm` only used when `algo= spconv.ConvAlgo.MaskImplicitGemm`, to avoid it, I need manually set all `algo=spconv.ConvAlgo.Native`.
> 
> Hope this helps somebody meet the same error.

hi,how can i do in C++?i try to add libspconv.so trtexec as plugins on jetson orin ,but error with:can't find suitable algorithm for 0
my env:
Hardware: NVIDIA Jetson AGX Orin
OS: Ubuntu 22.04
ROS 2 Distribution: Humble Hawksbill
JetPack Version: 6.2

**Comment by hitbuyi** [comment]
I meet same problem

**Comment by DanielEbert** [comment]
> "manually set all `algo=spconv.ConvAlgo.Native`." [@pjlearning](https://github.com/pjlearning) this works for me
> 
> Ubuntu 22.04 Python 3.10 Pytorch 2.1.2 CUDA 12.1 spconv+cu121
> 
> set all spconv modules like this: conv=spconv.SubMConv3d( in_channels, embed_channels, kernel_size=5, padding=1, bias=False, indice_key="stem", algo=spconv.ConvAlgo.Native )

Thanks, this worked for me

**Comment by SadilKhan** [comment]
> > 我遇到了同样的问题。FP32 在训练和推理期间都能正常工作。FP16 在训练期间工作正常，但在推理时会出现此错误。
> 
> use model.eval() and dont use fp16 dont use model.eval() and use fp16

This worked for me.
