### ISSUE TITLE
indice_conv() issue 

### ISSUE THREAD

**Issue by TmacTmac1992** [traveller59/spconv#591]
Hi,  I am using spconv-cu114 and cumm-114,  I got this issue: 

[Exception|indice_conv]feat=torch.Size([17253, 16]),w=torch.Size([32, 3, 3, 3, 16]),pair=torch.Size([2, 27, 17253]),pairnum=tensor([2347, 2262, 2347, 2341, 2380, 2341, 2347, 2262, 2347, 1977, 2015, 1977,
        1901, 2030, 1901, 1977, 2015, 1977, 2347, 2262, 2347, 2341, 2380, 2341,
        2347, 2262, 2347], dtype=torch.int32),act=25964,algo=ConvAlgo.Native
SPCONV_DEBUG_SAVE_PATH not found, you can specify SPCONV_DEBUG_SAVE_PATH as debug data save path to save debug data which can be attached in a issue.
Traceback (most recent call last):
  File "/home/hj002/anaconda3/envs/3d_labeling/lib/python3.7/site-packages/spconv/pytorch/conv.py", line 343, in _conv_forward
    act_type)
  File "/home/hj002/anaconda3/envs/3d_labeling/lib/python3.7/site-packages/torch/cuda/amp/autocast_mode.py", line 94, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/hj002/anaconda3/envs/3d_labeling/lib/python3.7/site-packages/spconv/pytorch/functional.py", line 92, in forward
    raise e
  File "/home/hj002/anaconda3/envs/3d_labeling/lib/python3.7/site-packages/spconv/pytorch/functional.py", line 85, in forward
    act_type=act_type)
  File "/home/hj002/anaconda3/envs/3d_labeling/lib/python3.7/site-packages/spconv/pytorch/ops.py", line 865, in indice_conv
    use_tf32=constants.SPCONV_ALLOW_TF32)
TypeError: indice_conv(): incompatible function arguments. The following argument types are supported:
    1. (allocator: spconv.core_cc.csrc.sparse.alloc.ExternalAllocator, ext_mm: spconv.core_cc.csrc.sparse.convops.ExternalSpconvMatmul, gemm_tuner: spconv.core_cc.csrc.sparse.convops.gemmops.GemmTunerSimple, all_w_is_krsc: bool, filter_hwio: bool, features: cumm.core_cc.tensorview_bind.Tensor, filters: cumm.core_cc.tensorview_bind.Tensor, indice_pairs: cumm.core_cc.tensorview_bind.Tensor, indice_pair_num: cumm.core_cc.tensorview_bind.Tensor, arch: Tuple[int, int], num_activate_out: int, inverse: bool = False, subm: bool = False, algo: int = 0, stream_int: int = 0, bias: cumm.core_cc.tensorview_bind.Tensor = <cumm.core_cc.tensorview_bind.Tensor object at 0x7f1fa1fd32f0>, act_alpha: float = 0.0, act_beta: float = 0.0, act_type: cumm.core_cc.tensorview_bind.Activation = <Activation.None_: 0>, use_tf32: bool = True) -> None

**Comment by FindDefinition** [comment]
could you share a minimal reproduce script?
Try '''python -m spconv.benchmark bench_basic f16''' and check if the error still exists.
I guess you forget to uninstall cpu version of cumm/spconv, use '''pip list | grep cumm''' to check.

**Comment by TmacTmac1992** [comment]
I did't install cpu version of cumm/spconv.  

When I run '''python -m spconv.benchmark bench_basic f16''',  I got the follow error: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hj002/anaconda3/envs/3d_labeling/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/hj002/anaconda3/envs/3d_labeling/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hj002/anaconda3/envs/3d_labeling/lib/python3.7/site-packages/spconv/benchmark/__main__.py", line 6, in <module>
    fire.Fire()
  File "/home/hj002/anaconda3/envs/3d_labeling/lib/python3.7/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/hj002/anaconda3/envs/3d_labeling/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/hj002/anaconda3/envs/3d_labeling/lib/python3.7/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/hj002/anaconda3/envs/3d_labeling/lib/python3.7/site-packages/spconv/benchmark/basic.py", line 167, in bench_basic
    (voxels, coors, spatial_shape) = get_voxel_data()
  File "/home/hj002/anaconda3/envs/3d_labeling/lib/python3.7/site-packages/spconv/benchmark/core.py", line 19, in get_voxel_data
    with requests.get(RAW_TEST_DATA_PATH, stream=True) as req:
  File "/home/hj002/.local/lib/python3.7/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/hj002/.local/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/hj002/.local/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/hj002/.local/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/hj002/.local/lib/python3.7/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /traveller59/spconv/v2.1.10/test/data/test_spconv.pkl (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb6471540d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by FindDefinition** [comment]
You can modify benchmark code by yourself, the benchmark code fetch data from github raw content, which may be unavailable in some country.

**Comment by dingfengshi** [comment]
this is a bug for Spconv. Change the ```act_type, act_beta,``` to ```act_alpha, act_beta,``` in line 342 in  spconv/pytorch/conv.py file can fix this.
