### ISSUE TITLE
CMake Error when run "python setup.py bdist_wheel"

### ISSUE THREAD

**Issue by ChadZhongqiangChen** [traveller59/spconv#60]
Hello:

When I ran "python setup.py bdist_wheel", and I met the following errors. I am running in Anaconda Powershell Prompt on Windows 10, and I am using Cuda 10.1.  Does anyone encounter these errors?

(pointpillars) PS>python setup.py bdist_wheel
running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=D:\\Engineering_Software\\Anaconda\\envs\\pointpillars\\lib\\site-packages\\torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\asus\\AI_Project\\SECOND\\spconv\\build\\lib.win-amd64-3.6\\spconv', '-DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\asus\\AI_Project\\SECOND\\spconv\\build\\lib.win-amd64-3.6\\spconv', '-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE', '-A', 'x64']
**CMake Error** at CMakeLists.txt:7 (project):
  Generator

    NMake Makefiles

  does not support platform specification, but platform

    x64

  was specified.

**CMake Error**: CMAKE_CXX_COMPILER not set, after EnableLanguage
**CMake Error**: CMAKE_CUDA_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/Users/asus/AI_Project/SECOND/spconv/build/temp.win-amd64-3.6/Release/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 99, in <module>
    zip_safe=False,
  File "D:\Engineering_Software\Anaconda\envs\pointpillars\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "D:\Engineering_Software\Anaconda\envs\pointpillars\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Engineering_Software\Anaconda\envs\pointpillars\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\Engineering_Software\Anaconda\envs\pointpillars\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Engineering_Software\Anaconda\envs\pointpillars\lib\site-packages\wheel\bdist_wheel.py", line 192, in run
    self.run_command('build')
  File "D:\Engineering_Software\Anaconda\envs\pointpillars\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Engineering_Software\Anaconda\envs\pointpillars\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Engineering_Software\Anaconda\envs\pointpillars\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "D:\Engineering_Software\Anaconda\envs\pointpillars\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Engineering_Software\Anaconda\envs\pointpillars\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 40, in run
    self.build_extension(ext)
  File "setup.py", line 82, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "D:\Engineering_Software\Anaconda\envs\pointpillars\lib\subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\asus\\AI_Project\\SECOND\\spconv', '-DCMAKE_PREFIX_PATH=D:\\Engineering_Software\\Anaconda\\envs\\pointpillars\\lib\\site-packages\\torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\asus\\AI_Project\\SECOND\\spconv\\build\\lib.win-amd64-3.6\\spconv', '-DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\asus\\AI_Project\\SECOND\\spconv\\build\\lib.win-amd64-3.6\\spconv', '-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE', '-A', 'x64']' returned non-zero exit status 1.
(pointpillars) PS>

**Comment by sylarchen1389** [comment]
Hi，i got the same problem too, have you found any solution?

**Comment by neverstoplearn** [comment]
i have get the same error as you ? have you solve it?

**Comment by MuneebZafar00713** [comment]
I had the same problem. You need to install CUDA compiler driver from https://developer.nvidia.com/cuda-downloads
Then you need to verify if its installed by typing command nvcc --version in terminal.
My output is as follows
nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2019 NVIDIA Corporation Built on Wed_Oct_23_19:32:27_Pacific_Daylight_Time_2019 Cuda compilation tools, release 10.2, V10.2.89
