### ISSUE TITLE
ERROR in import spconv.pytorch as spconv

### ISSUE THREAD

**Issue by ZTalex** [traveller59/spconv#621]
The following problem occurred when I tried to import spconv.pytorch as spconv.
My environment is:
WINDOWS 10 
python 3.8
torch               1.13.1+cu116
torchaudio          0.13.1+cu116
torchvision         0.14.1+cu116
spconv-cu116        2.3.6
cumm-cu116          0.4.10

![image](https://github.com/traveller59/spconv/assets/58802602/2bb3daa6-1f72-43ca-9a7e-2c542ee70f8f)

![image](https://github.com/traveller59/spconv/assets/58802602/607e5858-0614-4893-a15b-775a4284faef)

Traceback (most recent call last):
  File "E:/DESKTOP/yolo_csq/ANYTHING2.py", line 1, in <module>
    import spconv.pytorch as spconv
  File "D:\MINICONDA\envs\yolo_csq\lib\site-packages\spconv\__init__.py", line 17, in <module>
    from .core import ConvAlgo, AlgoHint
  File "D:\MINICONDA\envs\yolo_csq\lib\site-packages\spconv\core.py", line 15, in <module>
    from cumm.gemm.main import gen_shuffle_params_v2 as gen_shuffle_params, GemmAlgoParams
  File "D:\MINICONDA\envs\yolo_csq\lib\site-packages\cumm\gemm\main.py", line 30, in <module>
    from cumm import tensorview as tv
  File "D:\MINICONDA\envs\yolo_csq\lib\site-packages\cumm\tensorview\__init__.py", line 27, in <module>
    from cumm.core_cc import tensorview_bind
ImportError: DLL load failed while importing core_cc: 找不到指定的模块。

**Comment by ZTalex** [comment]
> 

No, but I tried it on linux with no problems

**Comment by kang-qingjiu** [comment]
好像是只能在linux环境

**Comment by Feez2403** [comment]
I have the same problem on windows, but the code runs on linux
