### ISSUE TITLE
[Exception|implicit_gemm_pair] then leads to ValueError: your out spatial shape [0, 188, 188] reach zero!!! input shape: [2, 188, 188]

### ISSUE THREAD

**Issue by zhaowenZhou** [traveller59/spconv#623]
I changed my voxel size from [0.1, 0.1, 0.15] to [0.3, 0.3, 0.45] trying to reduce GPU memory usage then occured this error
Below is whole error message

[Exception|implicit_gemm_pair]indices=torch.Size([17820, 4]),bs=2,ss=[2, 188, 188],algo=ConvAlgo.MaskImplicitGemm,ksize=[3, 1, 1],stride=[2, 1, 1],padding=[0, 0, 0],dilation=[1, 1, 1],subm=False,transpose=False
SPCONV_DEBUG_SAVE_PATH not found, you can specify SPCONV_DEBUG_SAVE_PATH as debug data save path to save debug data which can be attached in a issue.
Traceback (most recent call last):
File "tools/train.py", line 150, in <module>
    main()
  File "tools/train.py", line 139, in main
    train_detector(
  File "/home/zhouzhaowen/centerformer/det3d/torchie/apis/train.py", line 342, in train_detector
    trainer.run(data_loaders, cfg.workflow, cfg.total_epochs, local_rank=cfg.local_rank)
  File "/home/zhouzhaowen/centerformer/det3d/torchie/trainer/trainer.py", line 557, in run
    epoch_runner(data_loaders[i], self.epoch, **kwargs)
  File "/home/zhouzhaowen/centerformer/det3d/torchie/trainer/trainer.py", line 426, in train
    outputs = self.batch_processor_inline(
  File "/home/zhouzhaowen/centerformer/det3d/torchie/trainer/trainer.py", line 382, in batch_processor_inline
    losses = model(example, return_loss=True)
  File "/home/stardust/miniconda3/envs/ct2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhouzhaowen/centerformer/det3d/models/detectors/voxelnet_dynamic.py", line 54, in forward
    x, _ = self.extract_feat(example)
  File "/home/zhouzhaowen/centerformer/det3d/models/detectors/voxelnet_dynamic.py", line 37, in extract_feat
    x, voxel_feature = self.backbone(
  File "/home/stardust/miniconda3/envs/ct2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhouzhaowen/centerformer/det3d/models/backbones/scn.py", line 226, in forward
    ret = self.extra_conv(x_conv4)
  File "/home/stardust/miniconda3/envs/ct2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/stardust/miniconda3/envs/ct2/lib/python3.8/site-packages/spconv/pytorch/modules.py", line 138, in forward
    input = module(input)
  File "/home/stardust/miniconda3/envs/ct2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/stardust/miniconda3/envs/ct2/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 755, in forward
    return self._conv_forward(self.training,
  File "/home/stardust/miniconda3/envs/ct2/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 408, in _conv_forward
    raise e
  File "/home/stardust/miniconda3/envs/ct2/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 385, in _conv_forward
    res = ops.get_indice_pairs_implicit_gemm(
  File "/home/stardust/miniconda3/envs/ct2/lib/python3.8/site-packages/spconv/pytorch/ops.py", line 460, in get_indice_pairs_implicit_gemm
    raise ValueError(
ValueError: your out spatial shape [0, 188, 188] reach zero!!! input shape: [2, 188, 188]

**Comment by ZoangX** [comment]
Hello, I have the same problem as you, have you solved this problem?

**Comment by ZoangX** [comment]
With the help of my brother, I finally solved this problem, in your dataset.yaml, be sure to guarantee the following:
![image](https://github.com/traveller59/spconv/assets/58078383/2b758687-d978-436e-85a0-32d7a393f1c8)
What I mean is to make sure that the ratio of point_cloud_range to voxel_size matches the figure above. Or match the original official datasets.YAML

**Comment by lixiuyu-cumt** [comment]
> With the help of my brother, I finally solved this problem, in your dataset.yaml, be sure to guarantee the following: ![image](https://private-user-images.githubusercontent.com/58078383/269315546-2b758687-d978-436e-85a0-32d7a393f1c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MDc2ODMsIm5iZiI6MTcwMjYwNzM4MywicGF0aCI6Ii81ODA3ODM4My8yNjkzMTU1NDYtMmI3NTg2ODctZDk3OC00MzZlLTg1YTAtMzJkN2EzOTNmMWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDAyMjk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5MjBjMDUwM2ZkNGZlM2M5MTI3NjI4ZjdlZWNkYWNiZDIxMjA2OTFkNWQxMzVhMWVhMmU4MDA4NmFhNWFkNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i41_bT1pqhS1X98ifG1KNZ75zDZ_kl_dafF6DMzVqfE) What I mean is to make sure that the ratio of point_cloud_range to voxel_size matches the figure above. Or match the original official datasets.YAML

solved my problem!! thank you
