### ISSUE TITLE
import spconv.pytorch as spconv ERROR

### ISSUE THREAD

**Issue by wangjuansan** [traveller59/spconv#630]
Hi SpConv author,
Thank you for your great job! I try to `import spconv.pytorch as spconv` but there is always an import error after installing spconv

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/usrs/wangjuan/anaconda3/envs/PLA/lib/python3.7/site-packages/spconv/pytorch/__init__.py", line 6, in <module>
    from spconv.pytorch.core import SparseConvTensor
  File "/home/usrs/wangjuan/anaconda3/envs/PLA/lib/python3.7/site-packages/spconv/pytorch/core.py", line 21, in <module>
    from spconv.tools import CUDAKernelTimer
  File "/home/usrs/wangjuan/anaconda3/envs/PLA/lib/python3.7/site-packages/spconv/tools.py", line 16, in <module>
    from spconv.cppconstants import CPU_ONLY_BUILD
  File "/home/usrs/wangjuan/anaconda3/envs/PLA/lib/python3.7/site-packages/spconv/cppconstants.py", line 15, in <module>
    import spconv.core_cc as _ext
ImportError: generic_type: cannot initialize type "GemmAlgoDesp": an object with that name is already defined
```
BTW, I have alread tried pip `install -U cumm-cu111`.I use python3.7

```
torch                   1.8.2
torch-scatter           2.0.6
torch-sparse            0.6.10
torchaudio              0.8.2
torchvision             0.9.2
spconv                  2.3.6
spconv-cu111            2.1.25
```
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:18:20_PST_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0
```
```
>>> import spconv
>>> print(spconv.__version__)
2.3.6
```

I look forward to any suggestions.

**Comment by wangjuansan** [comment]
That problem is solved, thanks!

**Comment by xuldor** [comment]
same question，how to solve it？ @wangjuansan
