### ISSUE TITLE
No module named 'cumm' when building spconv from source on AGX Orin

### ISSUE THREAD

**Issue by eugenebak** [traveller59/spconv#639]
Hi,

I run this commands

```shell
export CUMM_CUDA_ARCH_LIST="8.7"
git clone https://github.com/FindDefinition/cumm
cd cumm
pip install -e .

git clone https://github.com/traveller59/spconv
cd spconv
```

And I've removed the `cumm` in `requires` section in `pyproject.toml`

When I run `pip install -e .`, the below error occurs

```
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Obtaining file:///home/tisc/Downloads/cumm/spconv
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/home/tisc/.local/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/tisc/.local/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/tisc/.local/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-4n4s5_3g/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 468, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-4n4s5_3g/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-4n4s5_3g/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-4n4s5_3g/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 154, in <module>
      ModuleNotFoundError: No module named 'cumm'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

How can I solve it? 

Thank you in advance!

**Comment by rem821** [comment]
Did you manage to solve this? I'm running into the same issue, I can import cumm and its install location is in PYTHONPATH .. Still, spconv instalation cannot find it.

**Comment by eugenebak** [comment]
Hi, I can't remember how I resolve 'this' issue.

But, I've installed spconv just using `pip install spconv-cuxxx`

**Comment by Hberto** [comment]
@eugenebak Did you solve it? I run into the same problem. I managed to solve it where i build cumm from source and also removed from the toml project

**Comment by eugenebak** [comment]
I just used `pip install spconv-cuxxx`

**Comment by Tony-syr** [comment]
You may have permission issue, or can't find the path to cumm/include
Try to using this
```
# you should be inside your spconv folder.
spconv$ export CUMM_INCLUDE_PATH="/home_path/cumm/include"
spconv$ sudo pip install -e . 
```
