### ISSUE TITLE
Command '['ninja', '-v']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by delightsomeness** [traveller59/spconv#676]
Please help me,I encountered an error while compiling the spconv library on Jeston Xavier NX. It seems that there is not enough running memory, but my running memory is 8GB. The error description is as follows:

[554/555] nvcc -MMD -MT objects/ConvMainUnitTest_implicit_gemm2.cu.o -MF objects/ConvMainUnitTest_implicit_gemm2.cu.o.d -I "/home/wheeltec/Downloads/spconv-2.1.25/build/temp.linux-aarch64-3.6/spconv/build/include" -I "/usr/local/cuda-10.2/targets/aarch64-linux/include" -I "/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/cumm/include" -I "/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/pybind11/include" -I "/home/wheeltec/miniforge3/envs/det/include/python3.6m" -I "/home/wheeltec/miniforge3/envs/det/include/python3.6m" -gencode=arch=compute_72,code=sm_72 -Xcudafe "--diag_suppress=implicit_return_from_non_void_function" -Xcompiler -fno-gnu-unique -std=c++14 -O3 -DTV_CUDA -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -Xcompiler="-fPIC" -Xcompiler='-O3' -c /home/wheeltec/Downloads/spconv-2.1.25/build/temp.linux-aarch64-3.6/spconv/build/src/cumm/conv/main/ConvMainUnitTest/ConvMainUnitTest_implicit_gemm2.cu -o objects/ConvMainUnitTest_implicit_gemm2.cu.o 
FAILED: objects/ConvMainUnitTest_implicit_gemm2.cu.o 
nvcc -MMD -MT objects/ConvMainUnitTest_implicit_gemm2.cu.o -MF objects/ConvMainUnitTest_implicit_gemm2.cu.o.d -I "/home/wheeltec/Downloads/spconv-2.1.25/build/temp.linux-aarch64-3.6/spconv/build/include" -I "/usr/local/cuda-10.2/targets/aarch64-linux/include" -I "/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/cumm/include" -I "/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/pybind11/include" -I "/home/wheeltec/miniforge3/envs/det/include/python3.6m" -I "/home/wheeltec/miniforge3/envs/det/include/python3.6m" -gencode=arch=compute_72,code=sm_72 -Xcudafe "--diag_suppress=implicit_return_from_non_void_function" -Xcompiler -fno-gnu-unique -std=c++14 -O3 -DTV_CUDA -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -Xcompiler="-fPIC" -Xcompiler='-O3' -c /home/wheeltec/Downloads/spconv-2.1.25/build/temp.linux-aarch64-3.6/spconv/build/src/cumm/conv/main/ConvMainUnitTest/ConvMainUnitTest_implicit_gemm2.cu -o objects/ConvMainUnitTest_implicit_gemm2.cu.o 
/home/wheeltec/Downloads/spconv-2.1.25/build/temp.linux-aarch64-3.6/spconv/build/include/cumm/conv/main/Simt_f32f32f32f32f32ntt_m32n128k16m32n32k8_210_C321LLLA1_SK/mma/Mma.h(53): warning: variable "total_skip_count" was declared but never referenced

/home/wheeltec/Downloads/spconv-2.1.25/build/temp.linux-aarch64-3.6/spconv/build/include/cumm/conv/main/Simt_f16f16f16f32f32ntt_m32n128k16m32n32k8_210_C321LLLA1_SK/mma/Mma.h(53): warning: variable "total_skip_count" was declared but never referenced

/home/wheeltec/Downloads/spconv-2.1.25/build/temp.linux-aarch64-3.6/spconv/build/include/cumm/conv/main/Simt_f32f32f32f32f32ntt_m32n64k16m32n32k8_210_C321LLLA1_SK/mma/Mma.h(53): warning: variable "total_skip_count" was declared but never referenced

/home/wheeltec/Downloads/spconv-2.1.25/build/temp.linux-aarch64-3.6/spconv/build/include/cumm/conv/main/Simt_f16f16f16f32f32ntt_m32n64k16m32n32k8_210_C321LLLA1_SK/mma/Mma.h(53): warning: variable "total_skip_count" was declared but never referenced

/home/wheeltec/Downloads/spconv-2.1.25/build/temp.linux-aarch64-3.6/spconv/build/include/cumm/conv/main/Simt_f32f32f32f32f32ntt_m32n32k32m32n32k8_210_C321LLLA1_SK/mma/Mma.h(53): warning: variable "total_skip_count" was declared but never referenced

/home/wheeltec/Downloads/spconv-2.1.25/build/temp.linux-aarch64-3.6/spconv/build/src/cumm/conv/main/ConvMainUnitTest/ConvMainUnitTest_implicit_gemm2.cu(13055): warning: variable "input_dims" was declared but never referenced

/home/wheeltec/Downloads/spconv-2.1.25/build/temp.linux-aarch64-3.6/spconv/build/src/cumm/conv/main/ConvMainUnitTest/ConvMainUnitTest_implicit_gemm2.cu(13055): warning: variable "output_dims" was declared but never referenced

/home/wheeltec/Downloads/spconv-2.1.25/build/temp.linux-aarch64-3.6/spconv/build/src/cumm/conv/main/ConvMainUnitTest/ConvMainUnitTest_implicit_gemm2.cu(13151): warning: variable "input_dims" was declared but never referenced

/home/wheeltec/Downloads/spconv-2.1.25/build/temp.linux-aarch64-3.6/spconv/build/src/cumm/conv/main/ConvMainUnitTest/ConvMainUnitTest_implicit_gemm2.cu(13151): warning: variable "output_dims" was declared but never referenced

/home/wheeltec/Downloads/spconv-2.1.25/build/temp.linux-aarch64-3.6/spconv/build/src/cumm/conv/main/ConvMainUnitTest/ConvMainUnitTest_implicit_gemm2.cu(13245): warning: variable "input_dims" was declared but never referenced

/home/wheeltec/Downloads/spconv-2.1.25/build/temp.linux-aarch64-3.6/spconv/build/src/cumm/conv/main/ConvMainUnitTest/ConvMainUnitTest_implicit_gemm2.cu(13245): warning: variable "output_dims" was declared but never referenced

/home/wheeltec/Downloads/spconv-2.1.25/build/temp.linux-aarch64-3.6/spconv/build/src/cumm/conv/main/ConvMainUnitTest/ConvMainUnitTest_implicit_gemm2.cu(13348): warning: variable "input_dims" was declared but never referenced

/home/wheeltec/Downloads/spconv-2.1.25/build/temp.linux-aarch64-3.6/spconv/build/src/cumm/conv/main/ConvMainUnitTest/ConvMainUnitTest_implicit_gemm2.cu(13348): warning: variable "output_dims" was declared but never referenced

/home/wheeltec/Downloads/spconv-2.1.25/build/temp.linux-aarch64-3.6/spconv/build/src/cumm/conv/main/ConvMainUnitTest/ConvMainUnitTest_implicit_gemm2.cu(13442): warning: variable "input_dims" was declared but never referenced

/home/wheeltec/Downloads/spconv-2.1.25/build/temp.linux-aarch64-3.6/spconv/build/src/cumm/conv/main/ConvMainUnitTest/ConvMainUnitTest_implicit_gemm2.cu(13442): warning: variable "output_dims" was declared but never referenced

/home/wheeltec/Downloads/spconv-2.1.25/build/temp.linux-aarch64-3.6/spconv/build/src/cumm/conv/main/ConvMainUnitTest/ConvMainUnitTest_implicit_gemm2.cu(13539): warning: variable "input_dims" was declared but never referenced

/home/wheeltec/Downloads/spconv-2.1.25/build/temp.linux-aarch64-3.6/spconv/build/src/cumm/conv/main/ConvMainUnitTest/ConvMainUnitTest_implicit_gemm2.cu(13539): warning: variable "output_dims" was declared but never referenced

/home/wheeltec/Downloads/spconv-2.1.25/build/temp.linux-aarch64-3.6/spconv/build/src/cumm/conv/main/ConvMainUnitTest/ConvMainUnitTest_implicit_gemm2.cu(13633): warning: variable "input_dims" was declared but never referenced

/home/wheeltec/Downloads/spconv-2.1.25/build/temp.linux-aarch64-3.6/spconv/build/src/cumm/conv/main/ConvMainUnitTest/ConvMainUnitTest_implicit_gemm2.cu(13633): warning: variable "output_dims" was declared but never referenced

/home/wheeltec/Downloads/spconv-2.1.25/build/temp.linux-aarch64-3.6/spconv/build/src/cumm/conv/main/ConvMainUnitTest/ConvMainUnitTest_implicit_gemm2.cu(482): warning: variable "iter_algo" was declared but never referenced

/home/wheeltec/Downloads/spconv-2.1.25/build/temp.linux-aarch64-3.6/spconv/build/src/cumm/conv/main/ConvMainUnitTest/ConvMainUnitTest_implicit_gemm2.cu(484): warning: variable "i_ltype" was declared but never referenced

/home/wheeltec/Downloads/spconv-2.1.25/build/temp.linux-aarch64-3.6/spconv/build/src/cumm/conv/main/ConvMainUnitTest/ConvMainUnitTest_implicit_gemm2.cu(485): warning: variable "w_ltype" was declared but never referenced

/home/wheeltec/Downloads/spconv-2.1.25/build/temp.linux-aarch64-3.6/spconv/build/src/cumm/conv/main/ConvMainUnitTest/ConvMainUnitTest_implicit_gemm2.cu(486): warning: variable "o_ltype" was declared but never referenced

/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/cumm/include/tensorview/tensor.h(353): warning: variable "tv::type_v [with T=int16_t]" is used before its value is set
          detected during:
            instantiation of function "lambda [](auto)->auto [with <auto-1>=int16_t]" 
/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/cumm/include/tensorview/core/mp_helper.h(97): here
            instantiation of "F tv::detail::mp_for_each_impl(tv::mp_list<Ts...>, F &&) [with Ts=<int32_t, int16_t, int8_t, uint32_t, uint16_t, uint8_t>, F=lambda [](auto)->auto]" 
/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/cumm/include/tensorview/core/mp_helper.h(159): here
            instantiation of "F tv::mp_for_each<L,F>(F &&) [with L=tv::mp_list<int32_t, int16_t, int8_t, uint32_t, uint16_t, uint8_t>, F=lambda [](auto)->auto]" 
(357): here
            instantiation of "__nv_bool tv::dispatch_noexcept<Ts...,F>(tv::DType, F &&) [with Ts=<int32_t, int16_t, int8_t, uint32_t, uint16_t, uint8_t>, F=lambda [](auto)->void]" 
(362): here
            instantiation of "void tv::dispatch<Ts...,F>(tv::DType, F &&) [with Ts=<int32_t, int16_t, int8_t, uint32_t, uint16_t, uint8_t>, F=lambda [](auto)->void]" 
(504): here
            instantiation of "void tv::Dispatch<T<Args...>>::operator()(tv::DType, F &&) [with T=std::tuple, Args=<int32_t, int16_t, int8_t, uint32_t, uint16_t, uint8_t>, F=lambda [](auto)->void]" 
(1095): here

/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/cumm/include/tensorview/tensor.h(353): warning: variable "tv::type_v [with T=int8_t]" is used before its value is set
          detected during:
            instantiation of function "lambda [](auto)->auto [with <auto-1>=int8_t]" 
/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/cumm/include/tensorview/core/mp_helper.h(97): here
            instantiation of "F tv::detail::mp_for_each_impl(tv::mp_list<Ts...>, F &&) [with Ts=<int32_t, int16_t, int8_t, uint32_t, uint16_t, uint8_t>, F=lambda [](auto)->auto]" 
/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/cumm/include/tensorview/core/mp_helper.h(159): here
            instantiation of "F tv::mp_for_each<L,F>(F &&) [with L=tv::mp_list<int32_t, int16_t, int8_t, uint32_t, uint16_t, uint8_t>, F=lambda [](auto)->auto]" 
(357): here
            instantiation of "__nv_bool tv::dispatch_noexcept<Ts...,F>(tv::DType, F &&) [with Ts=<int32_t, int16_t, int8_t, uint32_t, uint16_t, uint8_t>, F=lambda [](auto)->void]" 
(362): here
            instantiation of "void tv::dispatch<Ts...,F>(tv::DType, F &&) [with Ts=<int32_t, int16_t, int8_t, uint32_t, uint16_t, uint8_t>, F=lambda [](auto)->void]" 
(504): here
            instantiation of "void tv::Dispatch<T<Args...>>::operator()(tv::DType, F &&) [with T=std::tuple, Args=<int32_t, int16_t, int8_t, uint32_t, uint16_t, uint8_t>, F=lambda [](auto)->void]" 
(1095): here

/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/cumm/include/tensorview/tensor.h(353): warning: variable "tv::type_v [with T=uint32_t]" is used before its value is set
          detected during:
            instantiation of function "lambda [](auto)->auto [with <auto-1>=uint32_t]" 
/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/cumm/include/tensorview/core/mp_helper.h(97): here
            instantiation of "F tv::detail::mp_for_each_impl(tv::mp_list<Ts...>, F &&) [with Ts=<int32_t, int16_t, int8_t, uint32_t, uint16_t, uint8_t>, F=lambda [](auto)->auto]" 
/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/cumm/include/tensorview/core/mp_helper.h(159): here
            instantiation of "F tv::mp_for_each<L,F>(F &&) [with L=tv::mp_list<int32_t, int16_t, int8_t, uint32_t, uint16_t, uint8_t>, F=lambda [](auto)->auto]" 
(357): here
            instantiation of "__nv_bool tv::dispatch_noexcept<Ts...,F>(tv::DType, F &&) [with Ts=<int32_t, int16_t, int8_t, uint32_t, uint16_t, uint8_t>, F=lambda [](auto)->void]" 
(362): here
            instantiation of "void tv::dispatch<Ts...,F>(tv::DType, F &&) [with Ts=<int32_t, int16_t, int8_t, uint32_t, uint16_t, uint8_t>, F=lambda [](auto)->void]" 
(504): here
            instantiation of "void tv::Dispatch<T<Args...>>::operator()(tv::DType, F &&) [with T=std::tuple, Args=<int32_t, int16_t, int8_t, uint32_t, uint16_t, uint8_t>, F=lambda [](auto)->void]" 
(1095): here

/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/cumm/include/tensorview/tensor.h(353): warning: variable "tv::type_v [with T=uint16_t]" is used before its value is set
          detected during:
            instantiation of function "lambda [](auto)->auto [with <auto-1>=uint16_t]" 
/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/cumm/include/tensorview/core/mp_helper.h(97): here
            instantiation of "F tv::detail::mp_for_each_impl(tv::mp_list<Ts...>, F &&) [with Ts=<int32_t, int16_t, int8_t, uint32_t, uint16_t, uint8_t>, F=lambda [](auto)->auto]" 
/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/cumm/include/tensorview/core/mp_helper.h(159): here
            instantiation of "F tv::mp_for_each<L,F>(F &&) [with L=tv::mp_list<int32_t, int16_t, int8_t, uint32_t, uint16_t, uint8_t>, F=lambda [](auto)->auto]" 
(357): here
            instantiation of "__nv_bool tv::dispatch_noexcept<Ts...,F>(tv::DType, F &&) [with Ts=<int32_t, int16_t, int8_t, uint32_t, uint16_t, uint8_t>, F=lambda [](auto)->void]" 
(362): here
            instantiation of "void tv::dispatch<Ts...,F>(tv::DType, F &&) [with Ts=<int32_t, int16_t, int8_t, uint32_t, uint16_t, uint8_t>, F=lambda [](auto)->void]" 
(504): here
            instantiation of "void tv::Dispatch<T<Args...>>::operator()(tv::DType, F &&) [with T=std::tuple, Args=<int32_t, int16_t, int8_t, uint32_t, uint16_t, uint8_t>, F=lambda [](auto)->void]" 
(1095): here

/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/cumm/include/tensorview/tensor.h(353): warning: variable "tv::type_v [with T=uint8_t]" is used before its value is set
          detected during:
            instantiation of function "lambda [](auto)->auto [with <auto-1>=uint8_t]" 
/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/cumm/include/tensorview/core/mp_helper.h(97): here
            instantiation of "F tv::detail::mp_for_each_impl(tv::mp_list<Ts...>, F &&) [with Ts=<int32_t, int16_t, int8_t, uint32_t, uint16_t, uint8_t>, F=lambda [](auto)->auto]" 
/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/cumm/include/tensorview/core/mp_helper.h(159): here
            instantiation of "F tv::mp_for_each<L,F>(F &&) [with L=tv::mp_list<int32_t, int16_t, int8_t, uint32_t, uint16_t, uint8_t>, F=lambda [](auto)->auto]" 
(357): here
            instantiation of "__nv_bool tv::dispatch_noexcept<Ts...,F>(tv::DType, F &&) [with Ts=<int32_t, int16_t, int8_t, uint32_t, uint16_t, uint8_t>, F=lambda [](auto)->void]" 
(362): here
            instantiation of "void tv::dispatch<Ts...,F>(tv::DType, F &&) [with Ts=<int32_t, int16_t, int8_t, uint32_t, uint16_t, uint8_t>, F=lambda [](auto)->void]" 
(504): here
            instantiation of "void tv::Dispatch<T<Args...>>::operator()(tv::DType, F &&) [with T=std::tuple, Args=<int32_t, int16_t, int8_t, uint32_t, uint16_t, uint8_t>, F=lambda [](auto)->void]" 
(1095): here

/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/cumm/include/tensorview/tensor.h(353): warning: variable "tv::type_v [with T=uint64_t]" is used before its value is set
          detected during:
            instantiation of function "lambda [](auto)->auto [with <auto-1>=uint64_t]" 
/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/cumm/include/tensorview/core/mp_helper.h(97): here
            instantiation of "F tv::detail::mp_for_each_impl(tv::mp_list<Ts...>, F &&) [with Ts=<float, double, int8_t, int16_t, int32_t, int64_t, uint8_t, uint16_t, uint32_t, uint64_t, __nv_bool, __half>, F=lambda [](auto)->auto]" 
/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/cumm/include/tensorview/core/mp_helper.h(159): here
            instantiation of "F tv::mp_for_each<L,F>(F &&) [with L=tv::mp_list<float, double, int8_t, int16_t, int32_t, int64_t, uint8_t, uint16_t, uint32_t, uint64_t, __nv_bool, __half>, F=lambda [](auto)->auto]" 
(357): here
            instantiation of "__nv_bool tv::dispatch_noexcept<Ts...,F>(tv::DType, F &&) [with Ts=<float, double, int8_t, int16_t, int32_t, int64_t, uint8_t, uint16_t, uint32_t, uint64_t, __nv_bool, __half>, F=lambda [](auto)->auto]" 
(362): here
            instantiation of "void tv::dispatch<Ts...,F>(tv::DType, F &&) [with Ts=<float, double, int8_t, int16_t, int32_t, int64_t, uint8_t, uint16_t, uint32_t, uint64_t, __nv_bool, __half>, F=lambda [](auto)->auto]" 
(504): here
            instantiation of "void tv::Dispatch<T<Args...>>::operator()(tv::DType, F &&) [with T=std::tuple, Args=<float, double, int8_t, int16_t, int32_t, int64_t, uint8_t, uint16_t, uint32_t, uint64_t, __nv_bool, __half>, F=lambda [](auto)->auto]" 
(1218): here

/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/cumm/include/tensorview/tensor.h(353): warning: variable "tv::type_v [with T=__nv_bool]" is used before its value is set
          detected during:
            instantiation of function "lambda [](auto)->auto [with <auto-1>=__nv_bool]" 
/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/cumm/include/tensorview/core/mp_helper.h(97): here
            instantiation of "F tv::detail::mp_for_each_impl(tv::mp_list<Ts...>, F &&) [with Ts=<float, double, int8_t, int16_t, int32_t, int64_t, uint8_t, uint16_t, uint32_t, uint64_t, __nv_bool, __half>, F=lambda [](auto)->auto]" 
/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/cumm/include/tensorview/core/mp_helper.h(159): here
            instantiation of "F tv::mp_for_each<L,F>(F &&) [with L=tv::mp_list<float, double, int8_t, int16_t, int32_t, int64_t, uint8_t, uint16_t, uint32_t, uint64_t, __nv_bool, __half>, F=lambda [](auto)->auto]" 
(357): here
            instantiation of "__nv_bool tv::dispatch_noexcept<Ts...,F>(tv::DType, F &&) [with Ts=<float, double, int8_t, int16_t, int32_t, int64_t, uint8_t, uint16_t, uint32_t, uint64_t, __nv_bool, __half>, F=lambda [](auto)->auto]" 
(362): here
            instantiation of "void tv::dispatch<Ts...,F>(tv::DType, F &&) [with Ts=<float, double, int8_t, int16_t, int32_t, int64_t, uint8_t, uint16_t, uint32_t, uint64_t, __nv_bool, __half>, F=lambda [](auto)->auto]" 
(504): here
            instantiation of "void tv::Dispatch<T<Args...>>::operator()(tv::DType, F &&) [with T=std::tuple, Args=<float, double, int8_t, int16_t, int32_t, int64_t, uint8_t, uint16_t, uint32_t, uint64_t, __nv_bool, __half>, F=lambda [](auto)->auto]" 
(1218): here

/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/cumm/include/tensorview/tensor.h(353): warning: variable "tv::type_v [with T=__half]" is used before its value is set
          detected during:
            instantiation of function "lambda [](auto)->auto [with <auto-1>=__half]" 
/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/cumm/include/tensorview/core/mp_helper.h(97): here
            instantiation of "F tv::detail::mp_for_each_impl(tv::mp_list<Ts...>, F &&) [with Ts=<float, double, int8_t, int16_t, int32_t, int64_t, uint8_t, uint16_t, uint32_t, uint64_t, __nv_bool, __half>, F=lambda [](auto)->auto]" 
/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/cumm/include/tensorview/core/mp_helper.h(159): here
            instantiation of "F tv::mp_for_each<L,F>(F &&) [with L=tv::mp_list<float, double, int8_t, int16_t, int32_t, int64_t, uint8_t, uint16_t, uint32_t, uint64_t, __nv_bool, __half>, F=lambda [](auto)->auto]" 
(357): here
            instantiation of "__nv_bool tv::dispatch_noexcept<Ts...,F>(tv::DType, F &&) [with Ts=<float, double, int8_t, int16_t, int32_t, int64_t, uint8_t, uint16_t, uint32_t, uint64_t, __nv_bool, __half>, F=lambda [](auto)->auto]" 
(362): here
            instantiation of "void tv::dispatch<Ts...,F>(tv::DType, F &&) [with Ts=<float, double, int8_t, int16_t, int32_t, int64_t, uint8_t, uint16_t, uint32_t, uint64_t, __nv_bool, __half>, F=lambda [](auto)->auto]" 
(504): here
            instantiation of "void tv::Dispatch<T<Args...>>::operator()(tv::DType, F &&) [with T=std::tuple, Args=<float, double, int8_t, int16_t, int32_t, int64_t, uint8_t, uint16_t, uint32_t, uint64_t, __nv_bool, __half>, F=lambda [](auto)->auto]" 
(1218): here

gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 224, in <module>
    ext_modules=ext_modules,
  File "/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/wheeltec/miniforge3/envs/det/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/wheeltec/miniforge3/envs/det/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/wheeltec/miniforge3/envs/det/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/home/wheeltec/miniforge3/envs/det/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/wheeltec/miniforge3/envs/det/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/wheeltec/miniforge3/envs/det/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/wheeltec/miniforge3/envs/det/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/wheeltec/miniforge3/envs/det/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/pccm/extension.py", line 59, in run
    self.build_extension(ext)
  File "/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/pccm/extension.py", line 90, in build_extension
    debug_file_gen=ext.debug_file_gen)
  File "/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/pccm/builder/pybind.py", line 141, in build_pybind
    objects_folder=objects_folder)
  File "/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/ccimport/core.py", line 182, in ccimport
    linker_to_path=linker_to_path)
  File "/home/wheeltec/miniforge3/envs/det/lib/python3.6/site-packages/ccimport/buildtools/writer.py", line 997, in build_simple_ninja
    raise subprocess.CalledProcessError(proc.returncode, cmds)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

**Comment by RONGSHENG0404** [comment]
Hello, I also occurred this issue. Have you solve it?
