### ISSUE TITLE
Could not find suitable distribution for Requirement.parse('torch>=1.0.0')

### ISSUE THREAD

**Issue by Guo13** [traveller59/spconv#68]
Hello,
My os is under: 
CUDA9.0
cudnn7.0
pytorch'1.0.0a0+8322165'
cmake 3.13.3
python 3.6.8
I run python setup.py bdist_wheel command but it comes out this error:

No local packages or working download links found for torch>=1.0.0
Traceback (most recent call last):
  File "setup.py", line 99, in <module>
    zip_safe=False,
  File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 144, in setup
    _install_setup_requires(attrs)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 139, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/dist.py", line 717, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/dist.py", line 784, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py", line 673, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('torch>=1.0.0')

**Comment by qiyayun** [comment]
I have the same error ,have you work out?
