### ISSUE TITLE
How can I solve this issue..

### ISSUE THREAD

**Issue by jeajin99** [traveller59/spconv#681]
python setup.py develop
running develop
/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  easy_install.initialize_options(self)
/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
running egg_info
writing pcdet.egg-info/PKG-INFO
writing dependency_links to pcdet.egg-info/dependency_links.txt
writing requirements to pcdet.egg-info/requires.txt
writing top-level names to pcdet.egg-info/top_level.txt
reading manifest file 'pcdet.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'pcdet.egg-info/SOURCES.txt'
running build_ext
building 'pcdet.ops.iou3d_nms.iou3d_nms_cuda' extension
creating /home/jaejin/바탕화면/Open/OpenPCDet/build
creating /home/jaejin/바탕화면/Open/OpenPCDet/build/temp.linux-x86_64-cpython-38
creating /home/jaejin/바탕화면/Open/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet
creating /home/jaejin/바탕화면/Open/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops
creating /home/jaejin/바탕화면/Open/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms
creating /home/jaejin/바탕화면/Open/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src
Emitting ninja build file /home/jaejin/바탕화면/Open/OpenPCDet/build/temp.linux-x86_64-cpython-38/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/4] /usr/local/cuda-11.3/bin/nvcc  -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/TH -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/jaejin/anaconda3/envs/OpenPCDet/include/python3.8 -c -c '/home/jaejin/바탕화면/Open/OpenPCDet/pcdet/ops/iou3d_nms/src/iou3d_nms_kernel.cu' -o '/home/jaejin/바탕화면/Open/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_nms_kernel.o' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=iou3d_nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -ccbin /usr/bin/gcc-9 -std=c++14
FAILED: /home/jaejin/바탕화면/Open/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_nms_kernel.o 
/usr/local/cuda-11.3/bin/nvcc  -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/TH -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/jaejin/anaconda3/envs/OpenPCDet/include/python3.8 -c -c '/home/jaejin/바탕화면/Open/OpenPCDet/pcdet/ops/iou3d_nms/src/iou3d_nms_kernel.cu' -o '/home/jaejin/바탕화면/Open/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_nms_kernel.o' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=iou3d_nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -ccbin /usr/bin/gcc-9 -std=c++14
cc1plus: fatal error: cuda_runtime.h: 그런 파일이나 디렉터리가 없습니다
compilation terminated.
[2/4] /usr/bin/g++-9 -MMD -MF '/home/jaejin/바탕화면/Open/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_nms_api.o'.d -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/TH -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/jaejin/anaconda3/envs/OpenPCDet/include/python3.8 -c -c '/home/jaejin/바탕화면/Open/OpenPCDet/pcdet/ops/iou3d_nms/src/iou3d_nms_api.cpp' -o '/home/jaejin/바탕화면/Open/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_nms_api.o' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=iou3d_nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/jaejin/바탕화면/Open/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_nms_api.o 
/usr/bin/g++-9 -MMD -MF '/home/jaejin/바탕화면/Open/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_nms_api.o'.d -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/TH -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/jaejin/anaconda3/envs/OpenPCDet/include/python3.8 -c -c '/home/jaejin/바탕화면/Open/OpenPCDet/pcdet/ops/iou3d_nms/src/iou3d_nms_api.cpp' -o '/home/jaejin/바탕화면/Open/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_nms_api.o' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=iou3d_nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/home/jaejin/바탕화면/Open/OpenPCDet/pcdet/ops/iou3d_nms/src/iou3d_nms_api.cpp:4:10: fatal error: cuda.h: 그런 파일이나 디렉터리가 없습니다
    4 | #include <cuda.h>
      |          ^~~~~~~~
compilation terminated.
[3/4] /usr/bin/g++-9 -MMD -MF '/home/jaejin/바탕화면/Open/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_cpu.o'.d -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/TH -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/jaejin/anaconda3/envs/OpenPCDet/include/python3.8 -c -c '/home/jaejin/바탕화면/Open/OpenPCDet/pcdet/ops/iou3d_nms/src/iou3d_cpu.cpp' -o '/home/jaejin/바탕화면/Open/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_cpu.o' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=iou3d_nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/jaejin/바탕화면/Open/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_cpu.o 
/usr/bin/g++-9 -MMD -MF '/home/jaejin/바탕화면/Open/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_cpu.o'.d -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/TH -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/jaejin/anaconda3/envs/OpenPCDet/include/python3.8 -c -c '/home/jaejin/바탕화면/Open/OpenPCDet/pcdet/ops/iou3d_nms/src/iou3d_cpu.cpp' -o '/home/jaejin/바탕화면/Open/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_cpu.o' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=iou3d_nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/home/jaejin/바탕화면/Open/OpenPCDet/pcdet/ops/iou3d_nms/src/iou3d_cpu.cpp:12:10: fatal error: cuda.h: 그런 파일이나 디렉터리가 없습니다
   12 | #include <cuda.h>
      |          ^~~~~~~~
compilation terminated.
[4/4] /usr/bin/g++-9 -MMD -MF '/home/jaejin/바탕화면/Open/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_nms.o'.d -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/TH -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/jaejin/anaconda3/envs/OpenPCDet/include/python3.8 -c -c '/home/jaejin/바탕화면/Open/OpenPCDet/pcdet/ops/iou3d_nms/src/iou3d_nms.cpp' -o '/home/jaejin/바탕화면/Open/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_nms.o' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=iou3d_nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/jaejin/바탕화면/Open/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_nms.o 
/usr/bin/g++-9 -MMD -MF '/home/jaejin/바탕화면/Open/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_nms.o'.d -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/TH -I/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/jaejin/anaconda3/envs/OpenPCDet/include/python3.8 -c -c '/home/jaejin/바탕화면/Open/OpenPCDet/pcdet/ops/iou3d_nms/src/iou3d_nms.cpp' -o '/home/jaejin/바탕화면/Open/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_nms.o' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=iou3d_nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/home/jaejin/바탕화면/Open/OpenPCDet/pcdet/ops/iou3d_nms/src/iou3d_nms.cpp:10:10: fatal error: cuda.h: 그런 파일이나 디렉터리가 없습니다
   10 | #include <cuda.h>
      |          ^~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1808, in _run_ninja_build
    subprocess.run(
  File "/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    setup(
  File "/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/setuptools/command/develop.py", line 109, in install_for_development
    self.run_command('build_ext')
  File "/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 88, in run
    _build_ext.run(self)
  File "/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
    build_ext.build_extensions(self)
  File "/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 586, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1487, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/jaejin/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1824, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by ggonu** [comment]
I tried `pip install -e .` instead python setup.py develop. It seems work but not sure that will be work as well.
