### ISSUE TITLE
import spconv.core_cc as _ext ImportError: arg(): could not convert default argument 'workspace: tv::Tensor' in method '<class 'spconv.core_cc.csrc.sparse.convops.gemmops.GemmTunerSimple'>.run_with_tuned_result' into a Python object (type not registered yet?

### ISSUE THREAD

**Issue by niranyingluofen** [traveller59/spconv#682]
Hi SpConv author, thanks for your excellent work!
My spconv version is spconv-cu113 2.3.6. My cuda version is cu11.3
When I test my model but there is always an import error after installing spconv :
Traceback (most recent call last):
  File "tools/create_data.py", line 13, in <module>
    from det3d.datasets.utils.create_gt_database import create_groundtruth_database
  File "/media/wxr/work/lidar_detection/CenterPoint/CenterPoint/Det3D/det3d/datasets/__init__.py", line 4, in <module>
    from .kitti import KittiDataset
  File "/media/wxr/work/lidar_detection/CenterPoint/CenterPoint/Det3D/det3d/datasets/kitti/__init__.py", line 1, in <module>
    from .kitti import KittiDataset
  File "/media/wxr/work/lidar_detection/CenterPoint/CenterPoint/Det3D/det3d/datasets/kitti/kitti.py", line 7, in <module>
    from det3d.core import box_np_ops
  File "/media/wxr/work/lidar_detection/CenterPoint/CenterPoint/Det3D/det3d/core/__init__.py", line 4, in <module>
    from .anchor import *
  File "/media/wxr/work/lidar_detection/CenterPoint/CenterPoint/Det3D/det3d/core/anchor/__init__.py", line 1, in <module>
    from .anchor_generator import (
  File "/media/wxr/work/lidar_detection/CenterPoint/CenterPoint/Det3D/det3d/core/anchor/anchor_generator.py", line 2, in <module>
    from det3d.core.bbox import box_np_ops
  File "/media/wxr/work/lidar_detection/CenterPoint/CenterPoint/Det3D/det3d/core/bbox/__init__.py", line 42, in <module>
    from . import box_coders, box_np_ops, box_torch_ops, geometry, region_similarity
  File "/media/wxr/work/lidar_detection/CenterPoint/CenterPoint/Det3D/det3d/core/bbox/box_coders.py", line 5, in <module>
    from . import box_np_ops, box_torch_ops
  File "/media/wxr/work/lidar_detection/CenterPoint/CenterPoint/Det3D/det3d/core/bbox/box_np_ops.py", line 9, in <module>
    from spconv.utils import rbbox_intersection, rbbox_iou
  File "/home/wxr/anaconda3/envs/mmdetection/lib/python3.8/site-packages/spconv/utils/__init__.py", line 18, in <module>
    from spconv.cppconstants import CPU_ONLY_BUILD
  File "/home/wxr/anaconda3/envs/mmdetection/lib/python3.8/site-packages/spconv/cppconstants.py", line 15, in <module>
    import spconv.core_cc as _ext
ImportError: arg(): could not convert default argument 'workspace: tv::Tensor' in method '<class 'spconv.core_cc.csrc.sparse.convops.gemmops.GemmTunerSimple'>.run_with_tuned_result' into a Python object (type not registered yet?)

**Comment by niranyingluofen** [comment]
I have another question：
Traceback (most recent call last):
  File "tools/test.py", line 12, in <module>
    from mmdet3d.apis import single_gpu_test
  File "/media/wxr/work/work/SST_maybe_ok/SST/mmdet3d/apis/__init__.py", line 1, in <module>
    from .inference import (convert_SyncBN, inference_detector,
  File "/media/wxr/work/work/SST_maybe_ok/SST/mmdet3d/apis/inference.py", line 10, in <module>
    from mmdet3d.core import (Box3DMode, DepthInstance3DBoxes,
  File "/media/wxr/work/work/SST_maybe_ok/SST/mmdet3d/core/__init__.py", line 2, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/media/wxr/work/work/SST_maybe_ok/SST/mmdet3d/core/bbox/__init__.py", line 4, in <module>
    from .iou_calculators import (AxisAlignedBboxOverlaps3D, BboxOverlaps3D,
  File "/media/wxr/work/work/SST_maybe_ok/SST/mmdet3d/core/bbox/iou_calculators/__init__.py", line 1, in <module>
    from .iou3d_calculator import (AxisAlignedBboxOverlaps3D, BboxOverlaps3D,
  File "/media/wxr/work/work/SST_maybe_ok/SST/mmdet3d/core/bbox/iou_calculators/iou3d_calculator.py", line 5, in <module>
    from ..structures import get_box_type
  File "/media/wxr/work/work/SST_maybe_ok/SST/mmdet3d/core/bbox/structures/__init__.py", line 1, in <module>
    from .base_box3d import BaseInstance3DBoxes
  File "/media/wxr/work/work/SST_maybe_ok/SST/mmdet3d/core/bbox/structures/base_box3d.py", line 5, in <module>
    from mmdet3d.ops.iou3d import iou3d_cuda
  File "/media/wxr/work/work/SST_maybe_ok/SST/mmdet3d/ops/__init__.py", line 21, in <module>
    from .sparse_block import (SparseBasicBlock, SparseBottleneck,
  File "/media/wxr/work/work/SST_maybe_ok/SST/mmdet3d/ops/sparse_block.py", line 7, in <module>
    from spconv.pytorch import SparseModule, SparseSequential
  File "/home/wxr/anaconda3/envs/mmdetection/lib/python3.8/site-packages/spconv/pytorch/__init__.py", line 7, in <module>
    from spconv.pytorch.core import SparseConvTensor
  File "/home/wxr/anaconda3/envs/mmdetection/lib/python3.8/site-packages/spconv/pytorch/core.py", line 21, in <module>
    from spconv.tools import CUDAKernelTimer
  File "/home/wxr/anaconda3/envs/mmdetection/lib/python3.8/site-packages/spconv/tools.py", line 16, in <module>
    from spconv.cppconstants import CPU_ONLY_BUILD
  File "/home/wxr/anaconda3/envs/mmdetection/lib/python3.8/site-packages/spconv/cppconstants.py", line 15, in <module>
    import spconv.core_cc as _ext
ImportError: generic_type: cannot initialize type "ExternalAllocator": an object with that name is already defined

**Comment by nooneAB** [comment]
> 嗨，SpConv作者，感谢您的出色工作！我的spconv版本是spconv-cu113 2.3.6。我的 cuda 版本是 cu11.3 当我测试我的模型时，但安装 spconv 后总是出现导入错误： 回溯（最近一次调用）：文件“tools/create_data.py”，第 13 行，从 det3d.datasets.utils.create_gt_database 导入 create_groundtruth_database 文件“/media/wxr/work/lidar_detection/CenterPoint/CenterPoint/Det3D/det3d/datasets/**init**.py”，第 4 行，从 .kitti 导入 KittiDataset文件“/media/wxr/work/lidar_detection/CenterPoint/CenterPoint/Det3D/det3d/datasets/kitti/**init**.py”，第 1 行，从 .kitti 导入 KittiDataset 文件“/media/wxr/work/lidar_detection/CenterPoint/CenterPoint/Det3D/det3d/datasets/kitti/kitti.py”，第 7 行，从 det3d.core 导入 box_np_ops 文件“/media/wxr/work/lidar_detection/CenterPoint/CenterPoint/Det3D/det3d/core/**init**.py”， 第 4 行，从 .anchor 导入 * 文件“/media/wxr/work/lidar_detection/CenterPoint/CenterPoint/Det3D/det3d/core/anchor/**init**.py”，第 1 行，从 .anchor_generator 导入（文件“/media/wxr/work/lidar_detection/CenterPoint/CenterPoint/Det3D/det3d/core/anchor/anchor_generator.py”，第 2 行，从 det3d.core.bbox 导入box_np_ops文件“/media/wxr/work/lidar_detection/CenterPoint/CenterPoint/Det3D/det3d/core/bbox/**init**.py”，第 42 行，从 。import box_coders， box_np_ops， box_torch_ops， geometry， region_similarity File “/media/wxr/work/lidar_detection/CenterPoint/CenterPoint/Det3D/det3d/core/bbox/box_coders.py”， 第 5 行， in from .import box_np_ops，box_torch_ops文件“/media/wxr/work/lidar_detection/CenterPoint/CenterPoint/Det3D/det3d/core/bbox/box_np_ops.py”，第 9 行，来自 spconv.utils 导入rbbox_intersection，rbbox_iou文件“/home/wxr/anaconda3/envs/mmdetection/lib/python3.8/site-packages/spconv/utils/**init**.py”，第 18 行，来自 spconv.cppconstants 导入CPU_ONLY_BUILD导入spconv.core_cc中的文件“/home/wxr/anaconda3/envs/mmdetection/lib/python3.8/site-packages/spconv/cppconstants.py”，第 15 行，_ext ImportError：arg（）：无法将方法“<类”spconv.core_cc.csrc.sparse.convops.gemmops.GemmTunerSimple“>.run_with_tuned_result”中的默认参数“workspace： tv：：Tensor”转换为 Python 对象（类型尚未注册？
I have the same problem, how did you solve it？thanks!

**Comment by LuckyDush** [comment]
> I have another question： Traceback (most recent call last): File "tools/test.py", line 12, in from mmdet3d.apis import single_gpu_test File "/media/wxr/work/work/SST_maybe_ok/SST/mmdet3d/apis/**init**.py", line 1, in from .inference import (convert_SyncBN, inference_detector, File "/media/wxr/work/work/SST_maybe_ok/SST/mmdet3d/apis/inference.py", line 10, in from mmdet3d.core import (Box3DMode, DepthInstance3DBoxes, File "/media/wxr/work/work/SST_maybe_ok/SST/mmdet3d/core/**init**.py", line 2, in from .bbox import * # noqa: F401, F403 File "/media/wxr/work/work/SST_maybe_ok/SST/mmdet3d/core/bbox/**init**.py", line 4, in from .iou_calculators import (AxisAlignedBboxOverlaps3D, BboxOverlaps3D, File "/media/wxr/work/work/SST_maybe_ok/SST/mmdet3d/core/bbox/iou_calculators/**init**.py", line 1, in from .iou3d_calculator import (AxisAlignedBboxOverlaps3D, BboxOverlaps3D, File "/media/wxr/work/work/SST_maybe_ok/SST/mmdet3d/core/bbox/iou_calculators/iou3d_calculator.py", line 5, in from ..structures import get_box_type File "/media/wxr/work/work/SST_maybe_ok/SST/mmdet3d/core/bbox/structures/**init**.py", line 1, in from .base_box3d import BaseInstance3DBoxes File "/media/wxr/work/work/SST_maybe_ok/SST/mmdet3d/core/bbox/structures/base_box3d.py", line 5, in from mmdet3d.ops.iou3d import iou3d_cuda File "/media/wxr/work/work/SST_maybe_ok/SST/mmdet3d/ops/**init**.py", line 21, in from .sparse_block import (SparseBasicBlock, SparseBottleneck, File "/media/wxr/work/work/SST_maybe_ok/SST/mmdet3d/ops/sparse_block.py", line 7, in from spconv.pytorch import SparseModule, SparseSequential File "/home/wxr/anaconda3/envs/mmdetection/lib/python3.8/site-packages/spconv/pytorch/**init**.py", line 7, in from spconv.pytorch.core import SparseConvTensor File "/home/wxr/anaconda3/envs/mmdetection/lib/python3.8/site-packages/spconv/pytorch/core.py", line 21, in from spconv.tools import CUDAKernelTimer File "/home/wxr/anaconda3/envs/mmdetection/lib/python3.8/site-packages/spconv/tools.py", line 16, in from spconv.cppconstants import CPU_ONLY_BUILD File "/home/wxr/anaconda3/envs/mmdetection/lib/python3.8/site-packages/spconv/cppconstants.py", line 15, in import spconv.core_cc as _ext ImportError: generic_type: cannot initialize type "ExternalAllocator": an object with that name is already defined

Have you solved the problem? I had the same problem

**Comment by colorfulandcjy0806** [comment]
Perhaps everyone can try this. My environment is ubuntu20.04 and cuda is 11.4. Although I tried many methods but found them ineffective, I successfully solved the above problem through pip install spconv-cu102. I hope it is helpful to everyone.😄

**Comment by leiwanrobotics** [comment]
I have same issues:
bash scripts/det_inference_intersection_nofusion.sh
['/home/lei-wan/workspace/dataset_kit/DAIR-RCooper/codes/v2v4real_plugin/opencood/tools', '/opt/ros/humble/lib/python3.10/site-packages', '/opt/ros/humble/local/lib/python3.10/dist-packages', '/home/lei-wan/anaconda3/envs/v2v4real/lib/python37.zip', '/home/lei-wan/anaconda3/envs/v2v4real/lib/python3.7', '/home/lei-wan/anaconda3/envs/v2v4real/lib/python3.7/lib-dynload', '/home/lei-wan/anaconda3/envs/v2v4real/lib/python3.7/site-packages', '/home/lei-wan/workspace/dataset_kit/DAIR-RCooper/codes/v2v4real_plugin', '/home/lei-wan/anaconda3/envs/v2v4real/lib/python3.7/site-packages/IPython/extensions']
Traceback (most recent call last):
  File "v2v4real_plugin/opencood/tools/inference.py", line 16, in <module>
    from opencood.data_utils.datasets import build_dataset
  File "/home/lei-wan/workspace/dataset_kit/DAIR-RCooper/codes/v2v4real_plugin/opencood/data_utils/datasets/__init__.py", line 1, in <module>
    from opencood.data_utils.datasets.late_fusion_dataset import LateFusionDataset
  File "/home/lei-wan/workspace/dataset_kit/DAIR-RCooper/codes/v2v4real_plugin/opencood/data_utils/datasets/late_fusion_dataset.py", line 15, in <module>
    from opencood.data_utils.pre_processor import build_preprocessor
  File "/home/lei-wan/workspace/dataset_kit/DAIR-RCooper/codes/v2v4real_plugin/opencood/data_utils/pre_processor/__init__.py", line 4, in <module>
    from opencood.data_utils.pre_processor.sp_voxel_preprocessor import SpVoxelPreprocessor
  File "/home/lei-wan/workspace/dataset_kit/DAIR-RCooper/codes/v2v4real_plugin/opencood/data_utils/pre_processor/sp_voxel_preprocessor.py", line 9, in <module>
    from spconv.utils import Point2VoxelCPU3d
  File "/home/lei-wan/anaconda3/envs/v2v4real/lib/python3.7/site-packages/spconv/utils/__init__.py", line 18, in <module>
    from spconv.cppconstants import CPU_ONLY_BUILD
  File "/home/lei-wan/anaconda3/envs/v2v4real/lib/python3.7/site-packages/spconv/cppconstants.py", line 15, in <module>
    import spconv.core_cc as _ext
ImportError: arg(): could not convert default argument 'workspace: tv::Tensor' in method '<class 'spconv.core_cc.csrc.sparse.convops.gemmops.GemmTunerSimple'>.run_with_tuned_result' into a Python object (type not registered yet?)

**Comment by vpeiyun97** [comment]
> Perhaps everyone can try this. My environment is ubuntu20.04 and cuda is 11.4. Although I tried many methods but found them ineffective, I successfully solved the above problem through pip install spconv-cu102. I hope it is helpful to everyone.😄或许大家都可以尝试一下这个。我的环境是ubuntu20.04，cuda是11.4。虽然我尝试了很多方法但发现都没有效果，但是我通过pip install spconv-cu102成功解决了上述问题。希望对大家有帮助。😄

按照这个操作，的确就可以了。很神奇

**Comment by Rwang0208** [comment]
omg its so useful

**Comment by Qingyang-Liu** [comment]
really useful!

**Comment by Wistrong** [comment]
> Perhaps everyone can try this. My environment is ubuntu20.04 and cuda is 11.4. Although I tried many methods but found them ineffective, I successfully solved the above problem through pip install spconv-cu102. I hope it is helpful to everyone.😄

the most 👍， the best solutoion 😊
