### ISSUE TITLE
conv3d after .dense() function

### ISSUE THREAD

**Issue by eunseon02** [traveller59/spconv#717]
i got this error

```python
        dec_0 = self.Decoder2(dec_1)
        dense = dec_0.dense()
        out = self.conv(dense)
```

```bash
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [16,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [17,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [18,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [19,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [20,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [21,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [22,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [23,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [24,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [25,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [26,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [27,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [28,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [29,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [30,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [31,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [96,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [97,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [98,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [99,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [100,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [101,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [102,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [103,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [104,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [105,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [106,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [107,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [108,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [109,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [110,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [111,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [112,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [113,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [114,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [115,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [116,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [117,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [118,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [119,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [120,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [121,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [122,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [123,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [124,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [125,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [126,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [127,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [64,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [65,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [66,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [67,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [68,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [69,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [70,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [71,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [72,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [73,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [74,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [75,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [76,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [77,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [78,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [79,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [80,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [81,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [82,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [83,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [84,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [85,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [86,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [87,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [88,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [89,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [90,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [91,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [92,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [93,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [94,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [95,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [32,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [33,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [34,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [35,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [36,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [37,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [38,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [39,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [40,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [41,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [42,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [43,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [44,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [45,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [46,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [47,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [48,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [49,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [50,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [51,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [52,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [53,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [54,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [55,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [56,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [57,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [58,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [59,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [60,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [61,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [62,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1712608885084/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [71,0,0], thread: [63,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
Epoch 1/300:   0%|                                                                                                                                 | 0/51 [00:01<?, ?batch/s]
Traceback (most recent call last):
  File "/root/PointTransformer/train_spconv.py", line 443, in <module>
    main()
  File "/root/PointTransformer/train_spconv.py", line 441, in main
    main_worker(args)
  File "/root/PointTransformer/train_spconv.py", line 437, in main_worker
    trainer.run()
  File "/root/PointTransformer/train_spconv.py", line 108, in run
    train_loss, epoch_time, prev_preds = self.train_epoch(epoch, prev_preds)
  File "/root/PointTransformer/train_spconv.py", line 246, in train_epoch
    preds = self.model(sptensor)
  File "/root/anaconda3/envs/pointcept/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/pointcept/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/PointTransformer/model_spconv.py", line 150, in forward
    out = self.conv(dec_0.dense())
  File "/root/anaconda3/envs/pointcept/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/pointcept/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/pointcept/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 610, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/anaconda3/envs/pointcept/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 605, in _conv_forward
    return F.conv3d(
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
```

**Comment by eunseon02** [comment]
it is because of wrong indices batch_idx of sparse tensor.
