### ISSUE TITLE
setup.py bdist_wheel with CUDNN 

### ISSUE THREAD

**Issue by AhmedMagdyHendawy** [traveller59/spconv#83]
I have a problem with running setup.py bdist_wheel, the error that I found is as follows:
running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/usr/local/lib/python3.6/dist-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6','-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- Caffe2: CUDA detected: 9.2
-- Caffe2: CUDA nvcc is: /usr/local/cuda-9.2/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-9.2
-- Caffe2: Header version is: 9.2
-- Found cuDNN: v7.6.3  (include: /usr/local/cuda-9.2/include, library: /usr/local/cuda-9.2/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s):  3.7
-- Added CUDA NVCC flags for: -gencode;arch=compute_37,code=sm_37
-- Autodetected CUDA architecture(s):  3.7
-- pybind11 v2.3.dev1
-- Configuring done
-- Generating done
-- Build files have been written to: /spconv/build/temp.linux-x86_64-3.6
[ 31%] Built target cuhash
[ 36%] Built target spconv_nms
[ 50%] Built target spconv_utils
[ 54%] Linking CXX shared library ../../../lib.linux-x86_64-3.6/spconv/libspconv.so
/usr/local/cuda-9.2/lib64/libcudnn.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
src/spconv/CMakeFiles/spconv.dir/build.make:296: recipe for target '../lib.linux-x86_64-3.6/spconv/libspconv.so' failed
make[2]: *** [../lib.linux-x86_64-3.6/spconv/libspconv.so] Error 1
CMakeFiles/Makefile2:163: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all' failed
make[1]: *** [src/spconv/CMakeFiles/spconv.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 99, in <module>
    zip_safe=False,
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 204, in run
    self.run_command('build')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 40, in run
    self.build_extension(ext)
  File "setup.py", line 83, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

**Comment by Kumuj** [comment]
I also have the same issue.

**Comment by haoliangjiang** [comment]
Seems that we have the same problem. Did you figure it out?

**Comment by haoliangjiang** [comment]
May I ask what cmake version is it?
