### ISSUE TITLE
Can't get anything after run "python setup.py install"

### ISSUE THREAD

**Issue by lh0616** [traveller59/spconv#9]
I have downloaded libtorch and
 `export LIBTORCH_ROOT=/media/omnisky/data/liuhao/libtorch/`
and installed camke3.13.3 and 
`export PATH=/media/omnisky/data/liuhao/cmake-3.13.3/bin/cmake:$PATH`
then i run `python setup.py install` but got nothing 
![image](https://user-images.githubusercontent.com/39039745/51522612-bee8c700-1e64-11e9-9958-3d0b0a32c077.png)
I have waited about one hour, is there anything wrong?Should i wait so long time?

**Comment by lh0616** [comment]
I found that python version had been changed to 3.5 , now i have upgrade python to 3,6 and get new problem：
`No local packages or download links found for torch>=1.0.0
Traceback (most recent call last):
  File "setup.py", line 82, in <module>
    zip_safe=False,
  File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 269, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 826, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
    return installer(requirement)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 657, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('torch>=1.0.0')
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "setup.py", line 82, in <module>
    zip_safe=False,
  File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 269, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 826, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
    return installer(requirement)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 657, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('torch>=1.0.0')
` 

I have download stable libtorch and export LIBTORCH_ROOT="/media/omnisky/data/liuhao/libtorch/", can you give me some advices?thank you very much

**Comment by traveller59** [comment]
you need to install pytorch 1.0 in your python environment first. I am trying to build spconv against pytorch instead of libtorch.

**Comment by lh0616** [comment]
Do you means that i should install pytorch1.0 and libtorch in the meantimes.

**Comment by traveller59** [comment]
no, newest code don't require libtorch anymore. just install pytorch.

**Comment by jinfagang** [comment]
@traveller59  Same issue here:

```
python3 setup.py bdist_wheel
```

has not effect, no logs, no prints.

![image](https://user-images.githubusercontent.com/21303438/56486220-814e1580-6509-11e9-826d-53d1a8585d4f.png)


I have already installed pytorch from pip.

**Comment by dekura** [comment]
You can refer to #152
