### ISSUE TITLE
ModuleNotFoundError: No module named 'second'

### ISSUE THREAD

**Issue by TangeniThePyGuru** [traveller59/spconv#98]
(p36) tangos@ubuntu:~/second.pytorch/second$ python create_data.py nuscenes_data_prep --data_path=NUSCENES_TRAINVAL_DATASET_ROOT --version="v1.0-trainval" --max_sweeps=1Traceback (most recent call last):  File "create_data.py", line 8, in <module>
    import data.kitti_dataset as kitti_ds
  File "/home/tangos/second.pytorch/second/data/__init__.py", line 1, in <module>
    from . import kitti_dataset
  File "/home/tangos/second.pytorch/second/data/kitti_dataset.py", line 10, in <module>
    from .core import box_np_ops
ModuleNotFoundError: No module named 'data.core'
(p36) tangos@ubuntu:~/second.pytorch/second$ python create_data.py nuscenes_data_prep --data_path=NUSCENES_TRAINVAL_DATASET_ROOT --version="v1.0-trainval" --max_sweeps=1
Traceback (most recent call last):
  File "create_data.py", line 8, in <module>
    import data.kitti_dataset as kitti_ds
  File "/home/tangos/second.pytorch/second/data/__init__.py", line 1, in <module>
    from . import kitti_dataset
  File "/home/tangos/second.pytorch/second/data/kitti_dataset.py", line 9, in <module>
    from second.core import box_np_ops
ModuleNotFoundError: No module named 'second'

**Comment by TangeniThePyGuru** [comment]
> (p36) tangos@ubuntu:~/second.pytorch/second$ python create_data.py nuscenes_data_prep --data_path=NUSCENES_TRAINVAL_DATASET_ROOT --version="v1.0-trainval" --max_sweeps=1Traceback (most recent call last): File "create_data.py", line 8, in import data.kitti_dataset as kitti_ds File "/home/tangos/second.pytorch/second/data/**init**.py", line 1, in from . import kitti_dataset File "/home/tangos/second.pytorch/second/data/kitti_dataset.py", line 10, in from .core import box_np_ops ModuleNotFoundError: No module named 'data.core' (p36) tangos@ubuntu:~/second.pytorch/second$ python create_data.py nuscenes_data_prep --data_path=NUSCENES_TRAINVAL_DATASET_ROOT --version="v1.0-trainval" --max_sweeps=1
> Traceback (most recent call last):
> File "create_data.py", line 8, in
> import data.kitti_dataset as kitti_ds
> File "/home/tangos/second.pytorch/second/data/**init**.py", line 1, in
> from . import kitti_dataset
> File "/home/tangos/second.pytorch/second/data/kitti_dataset.py", line 9, in
> from second.core import box_np_ops
> ModuleNotFoundError: No module named 'second'

Ooops! Sorry wrong package
